// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.adminListEventsStmt, err = db.PrepareContext(ctx, adminListEvents); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListEvents: %w", err)
	}
	if q.adminMarkEventOKStmt, err = db.PrepareContext(ctx, adminMarkEventOK); err != nil {
		return nil, fmt.Errorf("error preparing query AdminMarkEventOK: %w", err)
	}
	if q.adminMarkEventRejectStmt, err = db.PrepareContext(ctx, adminMarkEventReject); err != nil {
		return nil, fmt.Errorf("error preparing query AdminMarkEventReject: %w", err)
	}
	if q.adminResetExpiredProcessingStmt, err = db.PrepareContext(ctx, adminResetExpiredProcessing); err != nil {
		return nil, fmt.Errorf("error preparing query AdminResetExpiredProcessing: %w", err)
	}
	if q.adminRetryEventNowStmt, err = db.PrepareContext(ctx, adminRetryEventNow); err != nil {
		return nil, fmt.Errorf("error preparing query AdminRetryEventNow: %w", err)
	}
	if q.createEventStmt, err = db.PrepareContext(ctx, createEvent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateEvent: %w", err)
	}
	if q.getEventStmt, err = db.PrepareContext(ctx, getEvent); err != nil {
		return nil, fmt.Errorf("error preparing query GetEvent: %w", err)
	}
	if q.listDueEventsForUpdateStmt, err = db.PrepareContext(ctx, listDueEventsForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query ListDueEventsForUpdate: %w", err)
	}
	if q.markEventFailedStmt, err = db.PrepareContext(ctx, markEventFailed); err != nil {
		return nil, fmt.Errorf("error preparing query MarkEventFailed: %w", err)
	}
	if q.markEventOKStmt, err = db.PrepareContext(ctx, markEventOK); err != nil {
		return nil, fmt.Errorf("error preparing query MarkEventOK: %w", err)
	}
	if q.markEventProcessingStmt, err = db.PrepareContext(ctx, markEventProcessing); err != nil {
		return nil, fmt.Errorf("error preparing query MarkEventProcessing: %w", err)
	}
	if q.markEventRejectStmt, err = db.PrepareContext(ctx, markEventReject); err != nil {
		return nil, fmt.Errorf("error preparing query MarkEventReject: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.adminListEventsStmt != nil {
		if cerr := q.adminListEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListEventsStmt: %w", cerr)
		}
	}
	if q.adminMarkEventOKStmt != nil {
		if cerr := q.adminMarkEventOKStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminMarkEventOKStmt: %w", cerr)
		}
	}
	if q.adminMarkEventRejectStmt != nil {
		if cerr := q.adminMarkEventRejectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminMarkEventRejectStmt: %w", cerr)
		}
	}
	if q.adminResetExpiredProcessingStmt != nil {
		if cerr := q.adminResetExpiredProcessingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminResetExpiredProcessingStmt: %w", cerr)
		}
	}
	if q.adminRetryEventNowStmt != nil {
		if cerr := q.adminRetryEventNowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminRetryEventNowStmt: %w", cerr)
		}
	}
	if q.createEventStmt != nil {
		if cerr := q.createEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createEventStmt: %w", cerr)
		}
	}
	if q.getEventStmt != nil {
		if cerr := q.getEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEventStmt: %w", cerr)
		}
	}
	if q.listDueEventsForUpdateStmt != nil {
		if cerr := q.listDueEventsForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listDueEventsForUpdateStmt: %w", cerr)
		}
	}
	if q.markEventFailedStmt != nil {
		if cerr := q.markEventFailedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markEventFailedStmt: %w", cerr)
		}
	}
	if q.markEventOKStmt != nil {
		if cerr := q.markEventOKStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markEventOKStmt: %w", cerr)
		}
	}
	if q.markEventProcessingStmt != nil {
		if cerr := q.markEventProcessingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markEventProcessingStmt: %w", cerr)
		}
	}
	if q.markEventRejectStmt != nil {
		if cerr := q.markEventRejectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markEventRejectStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                              DBTX
	tx                              *sql.Tx
	adminListEventsStmt             *sql.Stmt
	adminMarkEventOKStmt            *sql.Stmt
	adminMarkEventRejectStmt        *sql.Stmt
	adminResetExpiredProcessingStmt *sql.Stmt
	adminRetryEventNowStmt          *sql.Stmt
	createEventStmt                 *sql.Stmt
	getEventStmt                    *sql.Stmt
	listDueEventsForUpdateStmt      *sql.Stmt
	markEventFailedStmt             *sql.Stmt
	markEventOKStmt                 *sql.Stmt
	markEventProcessingStmt         *sql.Stmt
	markEventRejectStmt             *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                              tx,
		tx:                              tx,
		adminListEventsStmt:             q.adminListEventsStmt,
		adminMarkEventOKStmt:            q.adminMarkEventOKStmt,
		adminMarkEventRejectStmt:        q.adminMarkEventRejectStmt,
		adminResetExpiredProcessingStmt: q.adminResetExpiredProcessingStmt,
		adminRetryEventNowStmt:          q.adminRetryEventNowStmt,
		createEventStmt:                 q.createEventStmt,
		getEventStmt:                    q.getEventStmt,
		listDueEventsForUpdateStmt:      q.listDueEventsForUpdateStmt,
		markEventFailedStmt:             q.markEventFailedStmt,
		markEventOKStmt:                 q.markEventOKStmt,
		markEventProcessingStmt:         q.markEventProcessingStmt,
		markEventRejectStmt:             q.markEventRejectStmt,
	}
}
