// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type ClbEvent struct {
	ID                 int64          `json:"id"`
	WorkspaceID        string         `json:"workspace_id"`
	SourceService      string         `json:"source_service"`
	EventType          string         `json:"event_type"`
	EventKey           string         `json:"event_key"`
	IdempotencyKey     string         `json:"idempotency_key"`
	Payload            []byte         `json:"payload"`
	PayloadContentType string         `json:"payload_content_type"`
	Status             string         `json:"status"`
	AttemptCount       int32          `json:"attempt_count"`
	NextAttemptAt      time.Time      `json:"next_attempt_at"`
	LockedBy           sql.NullString `json:"locked_by"`
	LockedUntil        sql.NullTime   `json:"locked_until"`
	DeliveredAt        sql.NullTime   `json:"delivered_at"`
	RejectedAt         sql.NullTime   `json:"rejected_at"`
	LastError          sql.NullString `json:"last_error"`
	RejectReason       sql.NullString `json:"reject_reason"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}
