// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const adminListEvents = `-- name: AdminListEvents :many
SELECT
    id,
    workspace_id,
    source_service,
    event_type,
    event_key,
    idempotency_key,
    payload,
    payload_content_type,
    status,
    attempt_count,
    next_attempt_at,
    locked_by,
    locked_until,
    delivered_at,
    rejected_at,
    last_error,
    reject_reason,
    created_at,
    updated_at
FROM clb_event
WHERE workspace_id = $1
  AND ($2 = '' OR source_service = $3)
  AND ($4 = '' OR event_type = $5)
  AND ($6 = '' OR status = $7)
ORDER BY created_at DESC, id DESC
LIMIT $8 OFFSET $9
`

type AdminListEventsParams struct {
	WorkspaceID   string      `json:"workspace_id"`
	Column2       interface{} `json:"column_2"`
	SourceService string      `json:"source_service"`
	Column4       interface{} `json:"column_4"`
	EventType     string      `json:"event_type"`
	Column6       interface{} `json:"column_6"`
	Status        string      `json:"status"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) AdminListEvents(ctx context.Context, arg AdminListEventsParams) ([]ClbEvent, error) {
	rows, err := q.query(ctx, q.adminListEventsStmt, adminListEvents,
		arg.WorkspaceID,
		arg.Column2,
		arg.SourceService,
		arg.Column4,
		arg.EventType,
		arg.Column6,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClbEvent
	for rows.Next() {
		var i ClbEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceService,
			&i.EventType,
			&i.EventKey,
			&i.IdempotencyKey,
			&i.Payload,
			&i.PayloadContentType,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LockedBy,
			&i.LockedUntil,
			&i.DeliveredAt,
			&i.RejectedAt,
			&i.LastError,
			&i.RejectReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminMarkEventOK = `-- name: AdminMarkEventOK :execrows
UPDATE clb_event
SET status = 'ok',
    delivered_at = NOW(),
    locked_by = NULL,
    locked_until = NULL,
    last_error = NULL,
    updated_at = NOW()
WHERE workspace_id = $1
  AND id = $2
  AND status IN ('pending', 'processing')
`

type AdminMarkEventOKParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          int64  `json:"id"`
}

func (q *Queries) AdminMarkEventOK(ctx context.Context, arg AdminMarkEventOKParams) (int64, error) {
	result, err := q.exec(ctx, q.adminMarkEventOKStmt, adminMarkEventOK, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminMarkEventReject = `-- name: AdminMarkEventReject :execrows
UPDATE clb_event
SET status = 'reject',
    rejected_at = NOW(),
    reject_reason = $1,
    locked_by = NULL,
    locked_until = NULL,
    updated_at = NOW()
WHERE workspace_id = $2
  AND id = $3
  AND status IN ('pending', 'processing')
`

type AdminMarkEventRejectParams struct {
	RejectReason sql.NullString `json:"reject_reason"`
	WorkspaceID  string         `json:"workspace_id"`
	ID           int64          `json:"id"`
}

func (q *Queries) AdminMarkEventReject(ctx context.Context, arg AdminMarkEventRejectParams) (int64, error) {
	result, err := q.exec(ctx, q.adminMarkEventRejectStmt, adminMarkEventReject, arg.RejectReason, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminResetExpiredProcessing = `-- name: AdminResetExpiredProcessing :execrows
UPDATE clb_event
SET status = 'pending',
    locked_by = NULL,
    locked_until = NULL,
    next_attempt_at = NOW(),
    updated_at = NOW()
WHERE workspace_id = $1
  AND status = 'processing'
  AND locked_until IS NOT NULL
  AND locked_until <= NOW()
`

func (q *Queries) AdminResetExpiredProcessing(ctx context.Context, workspaceID string) (int64, error) {
	result, err := q.exec(ctx, q.adminResetExpiredProcessingStmt, adminResetExpiredProcessing, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminRetryEventNow = `-- name: AdminRetryEventNow :execrows
UPDATE clb_event
SET status = 'pending',
    next_attempt_at = NOW(),
    locked_by = NULL,
    locked_until = NULL,
    last_error = NULL,
    updated_at = NOW()
WHERE workspace_id = $1
  AND id = $2
  AND status IN ('pending', 'processing')
`

type AdminRetryEventNowParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          int64  `json:"id"`
}

func (q *Queries) AdminRetryEventNow(ctx context.Context, arg AdminRetryEventNowParams) (int64, error) {
	result, err := q.exec(ctx, q.adminRetryEventNowStmt, adminRetryEventNow, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO clb_event (
    workspace_id,
    source_service,
    event_type,
    event_key,
    idempotency_key,
    payload,
    payload_content_type,
    next_attempt_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (idempotency_key) DO UPDATE SET
    idempotency_key = EXCLUDED.idempotency_key
RETURNING id
`

type CreateEventParams struct {
	WorkspaceID        string    `json:"workspace_id"`
	SourceService      string    `json:"source_service"`
	EventType          string    `json:"event_type"`
	EventKey           string    `json:"event_key"`
	IdempotencyKey     string    `json:"idempotency_key"`
	Payload            []byte    `json:"payload"`
	PayloadContentType string    `json:"payload_content_type"`
	NextAttemptAt      time.Time `json:"next_attempt_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (int64, error) {
	row := q.queryRow(ctx, q.createEventStmt, createEvent,
		arg.WorkspaceID,
		arg.SourceService,
		arg.EventType,
		arg.EventKey,
		arg.IdempotencyKey,
		arg.Payload,
		arg.PayloadContentType,
		arg.NextAttemptAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getEvent = `-- name: GetEvent :one
SELECT
    id,
    workspace_id,
    source_service,
    event_type,
    event_key,
    idempotency_key,
    payload,
    payload_content_type,
    status,
    attempt_count,
    next_attempt_at,
    locked_by,
    locked_until,
    delivered_at,
    rejected_at,
    last_error,
    reject_reason,
    created_at,
    updated_at
FROM clb_event
WHERE workspace_id = $1
  AND id = $2
LIMIT 1
`

type GetEventParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          int64  `json:"id"`
}

func (q *Queries) GetEvent(ctx context.Context, arg GetEventParams) (ClbEvent, error) {
	row := q.queryRow(ctx, q.getEventStmt, getEvent, arg.WorkspaceID, arg.ID)
	var i ClbEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SourceService,
		&i.EventType,
		&i.EventKey,
		&i.IdempotencyKey,
		&i.Payload,
		&i.PayloadContentType,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LockedBy,
		&i.LockedUntil,
		&i.DeliveredAt,
		&i.RejectedAt,
		&i.LastError,
		&i.RejectReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueEventsForUpdate = `-- name: ListDueEventsForUpdate :many
SELECT
    id,
    workspace_id,
    source_service,
    event_type,
    event_key,
    idempotency_key,
    payload,
    payload_content_type,
    status,
    attempt_count,
    next_attempt_at,
    locked_by,
    locked_until,
    delivered_at,
    rejected_at,
    last_error,
    reject_reason,
    created_at,
    updated_at
FROM clb_event
WHERE ($1 = '' OR source_service = $2)
  AND status IN ('pending', 'processing')
  AND next_attempt_at <= NOW()
  AND (locked_until IS NULL OR locked_until <= NOW())
ORDER BY next_attempt_at, id
LIMIT $3
FOR UPDATE SKIP LOCKED
`

type ListDueEventsForUpdateParams struct {
	Column1       interface{} `json:"column_1"`
	SourceService string      `json:"source_service"`
	Limit         int32       `json:"limit"`
}

func (q *Queries) ListDueEventsForUpdate(ctx context.Context, arg ListDueEventsForUpdateParams) ([]ClbEvent, error) {
	rows, err := q.query(ctx, q.listDueEventsForUpdateStmt, listDueEventsForUpdate, arg.Column1, arg.SourceService, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClbEvent
	for rows.Next() {
		var i ClbEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SourceService,
			&i.EventType,
			&i.EventKey,
			&i.IdempotencyKey,
			&i.Payload,
			&i.PayloadContentType,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LockedBy,
			&i.LockedUntil,
			&i.DeliveredAt,
			&i.RejectedAt,
			&i.LastError,
			&i.RejectReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventFailed = `-- name: MarkEventFailed :execrows
UPDATE clb_event
SET status = 'pending',
    attempt_count = attempt_count + 1,
    next_attempt_at = $1,
    locked_by = NULL,
    locked_until = NULL,
    last_error = $2,
    updated_at = NOW()
WHERE id = $3
  AND status = 'processing'
  AND locked_by = $4
`

type MarkEventFailedParams struct {
	NextAttemptAt time.Time      `json:"next_attempt_at"`
	LastError     sql.NullString `json:"last_error"`
	ID            int64          `json:"id"`
	LockedBy      sql.NullString `json:"locked_by"`
}

func (q *Queries) MarkEventFailed(ctx context.Context, arg MarkEventFailedParams) (int64, error) {
	result, err := q.exec(ctx, q.markEventFailedStmt, markEventFailed,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
		arg.LockedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markEventOK = `-- name: MarkEventOK :execrows
UPDATE clb_event
SET status = 'ok',
    delivered_at = NOW(),
    locked_by = NULL,
    locked_until = NULL,
    last_error = NULL,
    updated_at = NOW()
WHERE id = $1
  AND status = 'processing'
  AND locked_by = $2
`

type MarkEventOKParams struct {
	ID       int64          `json:"id"`
	LockedBy sql.NullString `json:"locked_by"`
}

func (q *Queries) MarkEventOK(ctx context.Context, arg MarkEventOKParams) (int64, error) {
	result, err := q.exec(ctx, q.markEventOKStmt, markEventOK, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markEventProcessing = `-- name: MarkEventProcessing :execrows
UPDATE clb_event
SET status = 'processing',
    locked_by = $1,
    locked_until = $2,
    updated_at = NOW()
WHERE id = $3
  AND status IN ('pending', 'processing')
  AND (locked_until IS NULL OR locked_until <= NOW())
`

type MarkEventProcessingParams struct {
	LockedBy    sql.NullString `json:"locked_by"`
	LockedUntil sql.NullTime   `json:"locked_until"`
	ID          int64          `json:"id"`
}

func (q *Queries) MarkEventProcessing(ctx context.Context, arg MarkEventProcessingParams) (int64, error) {
	result, err := q.exec(ctx, q.markEventProcessingStmt, markEventProcessing, arg.LockedBy, arg.LockedUntil, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markEventReject = `-- name: MarkEventReject :execrows
UPDATE clb_event
SET status = 'reject',
    rejected_at = NOW(),
    reject_reason = $1,
    locked_by = NULL,
    locked_until = NULL,
    updated_at = NOW()
WHERE id = $2
  AND status = 'processing'
  AND locked_by = $3
`

type MarkEventRejectParams struct {
	RejectReason sql.NullString `json:"reject_reason"`
	ID           int64          `json:"id"`
	LockedBy     sql.NullString `json:"locked_by"`
}

func (q *Queries) MarkEventReject(ctx context.Context, arg MarkEventRejectParams) (int64, error) {
	result, err := q.exec(ctx, q.markEventRejectStmt, markEventReject, arg.RejectReason, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
