CREATE TABLE IF NOT EXISTS task_group (
    workspace_id VARCHAR(36) NOT NULL,
    key VARCHAR(100) NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    deleted_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, key)
);


CREATE TABLE IF NOT EXISTS task_group_localization (
    workspace_id VARCHAR(36) NOT NULL,
    group_key VARCHAR(100) NOT NULL,
    locale VARCHAR(16) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, group_key, locale),
    CONSTRAINT task_group_localization_group_fk
        FOREIGN KEY (workspace_id, group_key)
        REFERENCES task_group (workspace_id, key) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS task_sequence (
    workspace_id VARCHAR(36) NOT NULL,
    key VARCHAR(100) NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    deleted_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, key)
);


CREATE TABLE IF NOT EXISTS task_definition (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    workspace_id VARCHAR(36) NOT NULL,
    key VARCHAR(100) NOT NULL,
    group_key VARCHAR(100) NOT NULL,
    sequence_key VARCHAR(100) NULL,
    sequence_position INTEGER NULL,
    task_kind VARCHAR(64) NOT NULL DEFAULT 'internal',
    action_key VARCHAR(150) NOT NULL,
    action_kind VARCHAR(64) NOT NULL,
    claim_mode VARCHAR(64) NOT NULL DEFAULT 'manual',
    start_mode VARCHAR(64) NOT NULL DEFAULT 'none',
    target_count BIGINT NOT NULL DEFAULT 1,
    reset_unit VARCHAR(64) NOT NULL DEFAULT 'never',
    reset_every INTEGER NOT NULL DEFAULT 1,
    position INTEGER NOT NULL DEFAULT 0,
    payload JSONB NULL,
    target JSONB NULL,
    integration_kind VARCHAR(64) NULL,
    integration_provider VARCHAR(64) NULL,
    integration_payload JSONB NULL,
    image_url VARCHAR(1024) NULL,
    is_visible BOOLEAN NOT NULL DEFAULT true,
    is_active BOOLEAN NOT NULL DEFAULT true,
    start_at TIMESTAMPTZ NULL,
    end_at TIMESTAMPTZ NULL,
    deleted_at TIMESTAMPTZ NULL,
    branch_sort_key VARCHAR(101)
        GENERATED ALWAYS AS (COALESCE(sequence_key, '~' || key)) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT task_definition_workspace_id_uq UNIQUE (workspace_id, id),
    CONSTRAINT task_definition_key_uq UNIQUE (workspace_id, key),
    CONSTRAINT task_definition_sequence_position_uq UNIQUE (workspace_id, sequence_key, sequence_position),
    CONSTRAINT task_definition_group_fk
        FOREIGN KEY (workspace_id, group_key)
        REFERENCES task_group (workspace_id, key) ON DELETE RESTRICT,
    CONSTRAINT task_definition_sequence_fk
        FOREIGN KEY (workspace_id, sequence_key)
        REFERENCES task_sequence (workspace_id, key) ON DELETE RESTRICT,
    CONSTRAINT task_definition_sequence_chk CHECK (
        (sequence_key IS NULL AND sequence_position IS NULL) OR
        (sequence_key IS NOT NULL AND sequence_position IS NOT NULL AND sequence_position > 0)
    ),
    CONSTRAINT task_definition_target_chk CHECK (target_count > 0),
    CONSTRAINT task_definition_reset_chk CHECK (reset_every > 0),
    CONSTRAINT task_definition_window_chk CHECK (start_at IS NULL OR end_at IS NULL OR start_at < end_at)
);


CREATE TABLE IF NOT EXISTS task_complex_condition (
    workspace_id VARCHAR(36) NOT NULL,
    parent_task_id BIGINT NOT NULL,
    condition_task_id BIGINT NOT NULL,
    required_status VARCHAR(64) NOT NULL DEFAULT 'ready',
    position INTEGER NOT NULL DEFAULT 0,
    is_required BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, parent_task_id, condition_task_id),
    CONSTRAINT task_complex_condition_parent_fk
        FOREIGN KEY (workspace_id, parent_task_id)
        REFERENCES task_definition (workspace_id, id) ON DELETE RESTRICT,
    CONSTRAINT task_complex_condition_condition_fk
        FOREIGN KEY (workspace_id, condition_task_id)
        REFERENCES task_definition (workspace_id, id) ON DELETE RESTRICT,
    CONSTRAINT task_complex_condition_not_self_chk CHECK (parent_task_id <> condition_task_id)
);


CREATE TABLE IF NOT EXISTS task_localization (
    workspace_id VARCHAR(36) NOT NULL,
    task_id BIGINT NOT NULL,
    locale VARCHAR(16) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, task_id, locale),
    CONSTRAINT task_localization_definition_fk
        FOREIGN KEY (workspace_id, task_id)
        REFERENCES task_definition (workspace_id, id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS task_reward (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    workspace_id VARCHAR(36) NOT NULL,
    task_id BIGINT NOT NULL,
    reward_key VARCHAR(150) NOT NULL,
    reward_type VARCHAR(64) NOT NULL DEFAULT 'quantity',
    quantity BIGINT NOT NULL,
    scale SMALLINT NOT NULL DEFAULT 0,
    duration_unit VARCHAR(64) NULL,
    position INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT task_reward_workspace_id_uq UNIQUE (workspace_id, task_id, id),
    CONSTRAINT task_reward_key_uq UNIQUE (workspace_id, task_id, reward_key),
    CONSTRAINT task_reward_definition_fk
        FOREIGN KEY (workspace_id, task_id)
        REFERENCES task_definition (workspace_id, id) ON DELETE RESTRICT,
    CONSTRAINT task_reward_positive_quantity_chk CHECK (quantity > 0),
    CONSTRAINT task_reward_type_chk CHECK (
        (reward_type = 'quantity' AND duration_unit IS NULL)
        OR (reward_type = 'duration' AND duration_unit IS NOT NULL)
    )
);


CREATE TABLE IF NOT EXISTS task_progress (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    workspace_id VARCHAR(36) NOT NULL,
    task_id BIGINT NOT NULL,
    app_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    platform_user_id VARCHAR(255) NOT NULL,
    period_start_at TIMESTAMPTZ NOT NULL,
    period_end_at TIMESTAMPTZ NOT NULL,
    progress BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(64) NOT NULL DEFAULT 'open',
    ready_at TIMESTAMPTZ NULL,
    claimed_at TIMESTAMPTZ NULL,
    operation_id VARCHAR(128) NULL,
    rewards_snapshot JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT task_progress_identity_uq UNIQUE (
        workspace_id, task_id, app_id, platform_id, platform_user_id, period_start_at
    ),
    CONSTRAINT task_progress_definition_fk
        FOREIGN KEY (workspace_id, task_id)
        REFERENCES task_definition (workspace_id, id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS task_progress_missing_reward_snapshot_idx
    ON task_progress (id)
    WHERE rewards_snapshot IS NULL;

-- Preserve the catalog reward visible when legacy progress was first created.
-- New writes populate rewards_snapshot directly.
UPDATE task_progress AS progress
SET rewards_snapshot = COALESCE(
    (
        SELECT jsonb_agg(
            jsonb_strip_nulls(
                jsonb_build_object(
                    'key', reward.reward_key,
                    'type', reward.reward_type,
                    'quantity', reward.quantity,
                    'scale', reward.scale,
                    'unit', reward.duration_unit
                )
            )
            ORDER BY reward.position, reward.id
        )
        FROM task_reward AS reward
        WHERE reward.workspace_id = progress.workspace_id
          AND reward.task_id = progress.task_id
    ),
    '[]'::jsonb
)
WHERE progress.rewards_snapshot IS NULL;


CREATE TABLE IF NOT EXISTS task_sequence_state (
    workspace_id VARCHAR(36) NOT NULL,
    sequence_key VARCHAR(100) NOT NULL,
    app_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    platform_user_id VARCHAR(255) NOT NULL,
    current_task_id BIGINT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, sequence_key, app_id, platform_id, platform_user_id),
    CONSTRAINT task_sequence_state_sequence_fk
        FOREIGN KEY (workspace_id, sequence_key)
        REFERENCES task_sequence (workspace_id, key) ON DELETE RESTRICT,
    CONSTRAINT task_sequence_state_current_task_fk
        FOREIGN KEY (workspace_id, current_task_id)
        REFERENCES task_definition (workspace_id, id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS task_progress_event (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    workspace_id VARCHAR(36) NOT NULL,
    app_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    platform_user_id VARCHAR(255) NOT NULL,
    source VARCHAR(64) NOT NULL,
    external_event_key VARCHAR(255) NOT NULL,
    action_key VARCHAR(150) NOT NULL,
    amount BIGINT NOT NULL DEFAULT 1,
    payload JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT task_progress_event_uq UNIQUE (
        workspace_id, source, external_event_key, app_id, platform_id, platform_user_id
    )
);


CREATE TABLE IF NOT EXISTS task_stats_event (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(36) NOT NULL,
    task_id BIGINT NOT NULL,
    progress_id BIGINT NOT NULL,
    app_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    platform_user_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    claim_mode VARCHAR(64) NULL,
    amount BIGINT NOT NULL DEFAULT 0,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT task_stats_event_definition_fk
        FOREIGN KEY (workspace_id, task_id)
        REFERENCES task_definition (workspace_id, id) ON DELETE RESTRICT,
    CONSTRAINT task_stats_event_progress_fk
        FOREIGN KEY (progress_id)
        REFERENCES task_progress (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS task_stats_daily (
    workspace_id VARCHAR(36) NOT NULL,
    task_id BIGINT NOT NULL,
    stats_date DATE NOT NULL,
    progress_created BIGINT NOT NULL DEFAULT 0,
    progress_amount BIGINT NOT NULL DEFAULT 0,
    ready_count BIGINT NOT NULL DEFAULT 0,
    claimed_count BIGINT NOT NULL DEFAULT 0,
    manual_claimed_count BIGINT NOT NULL DEFAULT 0,
    auto_claimed_count BIGINT NOT NULL DEFAULT 0,
    unique_participants BIGINT NOT NULL DEFAULT 0,
    unique_claimers BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, task_id, stats_date),
    CONSTRAINT task_stats_daily_definition_fk
        FOREIGN KEY (workspace_id, task_id)
        REFERENCES task_definition (workspace_id, id) ON DELETE RESTRICT
);


CREATE TABLE IF NOT EXISTS task_stats_daily_overview (
    workspace_id VARCHAR(36) NOT NULL,
    stats_date DATE NOT NULL,
    tasks_total BIGINT NOT NULL DEFAULT 0,
    active_tasks BIGINT NOT NULL DEFAULT 0,
    visible_tasks BIGINT NOT NULL DEFAULT 0,
    progress_created BIGINT NOT NULL DEFAULT 0,
    progress_amount BIGINT NOT NULL DEFAULT 0,
    ready_count BIGINT NOT NULL DEFAULT 0,
    claimed_count BIGINT NOT NULL DEFAULT 0,
    manual_claimed_count BIGINT NOT NULL DEFAULT 0,
    auto_claimed_count BIGINT NOT NULL DEFAULT 0,
    unique_participants BIGINT NOT NULL DEFAULT 0,
    unique_claimers BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, stats_date)
);


CREATE TABLE IF NOT EXISTS task_partner_config (
    workspace_id VARCHAR(36) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    group_key VARCHAR(100) NOT NULL,
    platform VARCHAR(64) NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT true,
    secret TEXT NULL,
    webhook_secret VARCHAR(128) NULL,
    target JSONB NULL,
    settings JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, provider, group_key, platform),
    CONSTRAINT task_partner_config_webhook_secret_uq UNIQUE (workspace_id, webhook_secret)
);


CREATE TABLE IF NOT EXISTS task_partner_script (
    provider VARCHAR(64) NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT true,
    version VARCHAR(64) NOT NULL,
    source TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (provider)
);


CREATE TABLE IF NOT EXISTS task_partner_reward_rule (
    workspace_id VARCHAR(36) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    group_key VARCHAR(100) NOT NULL,
    external_type VARCHAR(64) NOT NULL DEFAULT '*',
    reward_key VARCHAR(150) NOT NULL,
    reward_type VARCHAR(64) NOT NULL DEFAULT 'quantity',
    quantity BIGINT NOT NULL,
    scale SMALLINT NOT NULL DEFAULT 0,
    duration_unit VARCHAR(64) NULL,
    position INTEGER NOT NULL DEFAULT 0,
    is_enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, provider, group_key, external_type, reward_key),
    CONSTRAINT task_partner_reward_rule_positive_quantity_chk CHECK (quantity > 0),
    CONSTRAINT task_partner_reward_rule_type_chk CHECK (
        (reward_type = 'quantity' AND duration_unit IS NULL)
        OR (reward_type = 'duration' AND duration_unit IS NOT NULL)
    )
);


CREATE TABLE IF NOT EXISTS task_partner_issue (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    workspace_id VARCHAR(36) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    group_key VARCHAR(100) NOT NULL,
    platform VARCHAR(64) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    external_type VARCHAR(64) NOT NULL,
    external_click_id VARCHAR(255) NULL,
    start_mode VARCHAR(64) NOT NULL DEFAULT 'none',
    issue_key VARCHAR(255) NOT NULL,
    app_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    platform_user_id VARCHAR(255) NOT NULL,
    public_payload JSONB NULL,
    private_payload JSONB NULL,
    rewards_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(32) NOT NULL DEFAULT 'issued',
    issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    claimed_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT task_partner_issue_key_uq UNIQUE (workspace_id, issue_key),
    CONSTRAINT task_partner_issue_click_uq UNIQUE (workspace_id, provider, external_click_id),
    CONSTRAINT task_partner_issue_workspace_id_uq UNIQUE (workspace_id, id)
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'task_partner_issue'::regclass
          AND conname = 'task_partner_issue_click_uq'
          AND pg_get_constraintdef(oid) NOT LIKE '%workspace_id, provider, external_click_id%'
    ) THEN
        ALTER TABLE task_partner_issue DROP CONSTRAINT task_partner_issue_click_uq;
        ALTER TABLE task_partner_issue
            ADD CONSTRAINT task_partner_issue_click_uq UNIQUE (
                workspace_id,
                provider,
                external_click_id
            );
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS task_partner_issue_start_lease (
    workspace_id VARCHAR(36) NOT NULL,
    issue_id BIGINT NOT NULL,
    lease_token VARCHAR(36) NOT NULL,
    lease_until TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, issue_id),
    CONSTRAINT task_partner_issue_start_lease_issue_fk
        FOREIGN KEY (workspace_id, issue_id)
        REFERENCES task_partner_issue (workspace_id, id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS task_partner_reward_grant (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    workspace_id VARCHAR(36) NOT NULL,
    issue_id BIGINT NOT NULL,
    provider VARCHAR(64) NOT NULL,
    group_key VARCHAR(100) NOT NULL,
    external_type VARCHAR(64) NOT NULL,
    app_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    platform_user_id VARCHAR(255) NOT NULL,
    operation_id VARCHAR(128) NOT NULL,
    reward_snapshot JSONB NOT NULL,
    claimed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT task_partner_reward_grant_issue_uq UNIQUE (workspace_id, issue_id),
    CONSTRAINT task_partner_reward_grant_operation_uq UNIQUE (workspace_id, operation_id),
    CONSTRAINT task_partner_reward_grant_issue_fk
        FOREIGN KEY (workspace_id, issue_id)
        REFERENCES task_partner_issue (workspace_id, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS task_reward_operation (
    workspace_id VARCHAR(36) NOT NULL,
    operation_id VARCHAR(128) NOT NULL,
    source_kind VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, operation_id)
);

INSERT INTO task_reward_operation (workspace_id, operation_id, source_kind, source_id)
SELECT workspace_id, operation_id, 'task_progress', id
FROM task_progress
WHERE operation_id IS NOT NULL
  AND operation_id <> ''
ON CONFLICT (workspace_id, operation_id) DO NOTHING;

INSERT INTO task_reward_operation (workspace_id, operation_id, source_kind, source_id)
SELECT workspace_id, operation_id, 'partner_issue', issue_id
FROM task_partner_reward_grant
WHERE operation_id <> ''
ON CONFLICT (workspace_id, operation_id) DO NOTHING;

ALTER TABLE task_partner_issue
    ADD COLUMN IF NOT EXISTS rewards_snapshot JSONB NULL;

UPDATE task_partner_issue AS issue
SET rewards_snapshot = COALESCE(
    (
        SELECT reward_grant.reward_snapshot
        FROM task_partner_reward_grant AS reward_grant
        WHERE reward_grant.workspace_id = issue.workspace_id
          AND reward_grant.issue_id = issue.id
        LIMIT 1
    ),
    (
        SELECT jsonb_agg(
            jsonb_build_object(
                'key', selected.reward_key,
                'type', selected.reward_type,
                'quantity', selected.quantity,
                'scale', selected.scale,
                'unit', selected.duration_unit
            )
            ORDER BY selected.position, selected.reward_key
        )
        FROM (
            SELECT DISTINCT ON (rule.reward_key)
                rule.reward_key,
                rule.reward_type,
                rule.quantity,
                rule.scale,
                rule.duration_unit,
                rule.position
            FROM task_partner_reward_rule AS rule
            WHERE rule.workspace_id = issue.workspace_id
              AND rule.provider = issue.provider
              AND rule.group_key = issue.group_key
              AND rule.external_type IN (issue.external_type, '*')
              AND rule.is_enabled = true
            ORDER BY
                rule.reward_key,
                CASE WHEN rule.external_type = issue.external_type THEN 0 ELSE 1 END,
                rule.position
        ) AS selected
    ),
    '[]'::jsonb
)
WHERE issue.rewards_snapshot IS NULL;

ALTER TABLE task_partner_issue
    ALTER COLUMN rewards_snapshot SET DEFAULT '[]'::jsonb,
    ALTER COLUMN rewards_snapshot SET NOT NULL;


CREATE TABLE IF NOT EXISTS task_partner_stats_event (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    workspace_id VARCHAR(36) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    group_key VARCHAR(100) NOT NULL,
    external_type VARCHAR(64) NOT NULL,
    issue_id BIGINT NULL,
    external_id VARCHAR(255) NULL,
    app_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    platform_user_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    event_key VARCHAR(255) NOT NULL,
    status VARCHAR(64) NULL,
    payload JSONB NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT task_partner_stats_event_key_uq UNIQUE (workspace_id, event_key)
);


CREATE TABLE IF NOT EXISTS task_partner_stats_daily (
    workspace_id VARCHAR(36) NOT NULL,
    stats_date DATE NOT NULL,
    provider VARCHAR(64) NOT NULL,
    group_key VARCHAR(100) NOT NULL,
    external_type VARCHAR(64) NOT NULL,
    issued_count BIGINT NOT NULL DEFAULT 0,
    completed_count BIGINT NOT NULL DEFAULT 0,
    claimed_count BIGINT NOT NULL DEFAULT 0,
    revoked_count BIGINT NOT NULL DEFAULT 0,
    revoked_after_claim_count BIGINT NOT NULL DEFAULT 0,
    failed_count BIGINT NOT NULL DEFAULT 0,
    fake_count BIGINT NOT NULL DEFAULT 0,
    expired_count BIGINT NOT NULL DEFAULT 0,
    unique_issued_users BIGINT NOT NULL DEFAULT 0,
    unique_completed_users BIGINT NOT NULL DEFAULT 0,
    unique_claimers BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, stats_date, provider, group_key, external_type)
);


CREATE TABLE IF NOT EXISTS task_partner_stats_unique_user (
    workspace_id VARCHAR(36) NOT NULL,
    stats_date DATE NOT NULL,
    provider VARCHAR(64) NOT NULL,
    group_key VARCHAR(100) NOT NULL,
    external_type VARCHAR(64) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    app_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    platform_user_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (
        workspace_id, stats_date, provider, group_key, external_type,
        event_type, app_id, platform_id, platform_user_id
    )
);

CREATE INDEX IF NOT EXISTS task_group_list_idx ON task_group (workspace_id, is_active, deleted_at, position, key);
CREATE INDEX IF NOT EXISTS task_sequence_list_idx ON task_sequence (workspace_id, is_active, deleted_at, position, key);
CREATE INDEX IF NOT EXISTS task_definition_action_idx ON task_definition (workspace_id, action_key, is_active, deleted_at, start_at, end_at, position, id);
CREATE INDEX IF NOT EXISTS task_definition_admin_list_idx ON task_definition (workspace_id, deleted_at, position, id);
CREATE INDEX IF NOT EXISTS task_definition_admin_group_list_idx ON task_definition (workspace_id, group_key, deleted_at, position, id);
CREATE INDEX IF NOT EXISTS task_definition_active_branch_idx ON task_definition (workspace_id, is_active, deleted_at, branch_sort_key, sequence_position, position, id);
CREATE INDEX IF NOT EXISTS task_definition_visible_list_idx ON task_definition (workspace_id, is_visible, is_active, deleted_at, position, id);
CREATE INDEX IF NOT EXISTS task_definition_visible_user_list_idx ON task_definition (workspace_id, is_visible, is_active, deleted_at, position, id, key, group_key);
CREATE INDEX IF NOT EXISTS task_definition_group_idx ON task_definition (workspace_id, group_key, is_visible, is_active, deleted_at, position, id);
CREATE INDEX IF NOT EXISTS task_definition_sequence_idx ON task_definition (workspace_id, sequence_key, sequence_position, id);
CREATE INDEX IF NOT EXISTS task_complex_condition_parent_idx ON task_complex_condition (workspace_id, parent_task_id, position, condition_task_id);
CREATE INDEX IF NOT EXISTS task_complex_condition_condition_idx ON task_complex_condition (workspace_id, condition_task_id, parent_task_id);
CREATE INDEX IF NOT EXISTS task_reward_list_idx ON task_reward (workspace_id, task_id, position, id);
CREATE INDEX IF NOT EXISTS task_progress_user_idx ON task_progress (workspace_id, app_id, platform_id, platform_user_id, period_start_at, task_id);
CREATE INDEX IF NOT EXISTS task_progress_current_user_idx ON task_progress (workspace_id, app_id, platform_id, platform_user_id, period_start_at, period_end_at, task_id);
CREATE INDEX IF NOT EXISTS task_progress_task_idx ON task_progress (workspace_id, task_id, period_start_at, status);
CREATE INDEX IF NOT EXISTS task_sequence_state_current_idx ON task_sequence_state (workspace_id, app_id, platform_id, platform_user_id, status, current_task_id);
CREATE INDEX IF NOT EXISTS task_progress_event_external_user_idx ON task_progress_event (workspace_id, app_id, platform_id, platform_user_id, source, external_event_key);
CREATE INDEX IF NOT EXISTS task_stats_event_workspace_idx ON task_stats_event (workspace_id, occurred_at, event_type);
CREATE INDEX IF NOT EXISTS task_stats_event_task_idx ON task_stats_event (workspace_id, task_id, occurred_at, event_type);
CREATE INDEX IF NOT EXISTS task_stats_event_user_idx ON task_stats_event (workspace_id, app_id, platform_id, platform_user_id, occurred_at);
CREATE INDEX IF NOT EXISTS task_stats_daily_date_idx ON task_stats_daily (workspace_id, stats_date, task_id);
CREATE INDEX IF NOT EXISTS task_stats_daily_overview_date_idx ON task_stats_daily_overview (stats_date, workspace_id);
CREATE INDEX IF NOT EXISTS task_partner_config_list_idx ON task_partner_config (workspace_id, is_enabled, provider, group_key);
CREATE INDEX IF NOT EXISTS task_partner_script_enabled_idx ON task_partner_script (is_enabled, provider);
CREATE INDEX IF NOT EXISTS task_partner_reward_rule_list_idx ON task_partner_reward_rule (workspace_id, provider, group_key, external_type, is_enabled, position);
CREATE INDEX IF NOT EXISTS task_partner_issue_user_idx ON task_partner_issue (workspace_id, app_id, platform_id, platform_user_id, provider, group_key, status);
CREATE INDEX IF NOT EXISTS task_partner_issue_external_idx ON task_partner_issue (workspace_id, provider, group_key, external_type, external_id);
CREATE INDEX IF NOT EXISTS task_partner_issue_expire_idx ON task_partner_issue (workspace_id, expires_at, status);
CREATE INDEX IF NOT EXISTS task_partner_reward_grant_user_idx ON task_partner_reward_grant (workspace_id, app_id, platform_id, platform_user_id, claimed_at);
CREATE INDEX IF NOT EXISTS task_partner_stats_event_daily_idx ON task_partner_stats_event (workspace_id, occurred_at, provider, group_key, external_type, event_type);
CREATE INDEX IF NOT EXISTS task_partner_stats_event_issue_idx ON task_partner_stats_event (workspace_id, issue_id, event_type);
CREATE INDEX IF NOT EXISTS task_partner_stats_daily_date_idx ON task_partner_stats_daily (workspace_id, stats_date, provider, group_key);
