// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"
)

type CalendarDefinition struct {
	ID                  string       `json:"id"`
	WorkspaceID         string       `json:"workspace_id"`
	Type                string       `json:"type"`
	Mode                string       `json:"mode"`
	IntervalType        string       `json:"interval_type"`
	IntervalUnit        string       `json:"interval_unit"`
	IntervalCount       int32        `json:"interval_count"`
	ResetAfterIntervals int32        `json:"reset_after_intervals"`
	EndBehavior         string       `json:"end_behavior"`
	Timezone            string       `json:"timezone"`
	HideFutureRewards   bool         `json:"hide_future_rewards"`
	IsActive            bool         `json:"is_active"`
	StartAt             sql.NullTime `json:"start_at"`
	EndAt               sql.NullTime `json:"end_at"`
	DeletedAt           sql.NullTime `json:"deleted_at"`
	CreatedAt           time.Time    `json:"created_at"`
	UpdatedAt           time.Time    `json:"updated_at"`
}

type CalendarLocalization struct {
	WorkspaceID string    `json:"workspace_id"`
	CalendarID  string    `json:"calendar_id"`
	Locale      string    `json:"locale"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type CalendarOperation struct {
	ID                int64           `json:"id"`
	WorkspaceID       string          `json:"workspace_id"`
	CalendarID        string          `json:"calendar_id"`
	AppID             int64           `json:"app_id"`
	PlatformID        int64           `json:"platform_id"`
	PlatformUserID    string          `json:"platform_user_id"`
	OperationID       string          `json:"operation_id"`
	Granted           bool            `json:"granted"`
	Status            string          `json:"status"`
	Position          sql.NullInt32   `json:"position"`
	RewardsSnapshot   json.RawMessage `json:"rewards_snapshot"`
	CurrentPosition   int32           `json:"current_position"`
	ClaimCount        int64           `json:"claim_count"`
	LastClaimPosition sql.NullInt32   `json:"last_claim_position"`
	LastClaimAt       sql.NullTime    `json:"last_claim_at"`
	NextClaimAt       sql.NullTime    `json:"next_claim_at"`
	IsCompleted       bool            `json:"is_completed"`
	ResetCount        int64           `json:"reset_count"`
	WasReset          bool            `json:"was_reset"`
	OccurredAt        time.Time       `json:"occurred_at"`
	CreatedAt         time.Time       `json:"created_at"`
}

type CalendarProgress struct {
	WorkspaceID       string        `json:"workspace_id"`
	CalendarID        string        `json:"calendar_id"`
	AppID             int64         `json:"app_id"`
	PlatformID        int64         `json:"platform_id"`
	PlatformUserID    string        `json:"platform_user_id"`
	CurrentPosition   int32         `json:"current_position"`
	ClaimCount        int64         `json:"claim_count"`
	LastClaimPosition sql.NullInt32 `json:"last_claim_position"`
	LastClaimAt       sql.NullTime  `json:"last_claim_at"`
	NextClaimAt       sql.NullTime  `json:"next_claim_at"`
	IsCompleted       bool          `json:"is_completed"`
	ResetCount        int64         `json:"reset_count"`
	LastWasReset      bool          `json:"last_was_reset"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type CalendarReward struct {
	ID           int64          `json:"id"`
	WorkspaceID  string         `json:"workspace_id"`
	CalendarID   string         `json:"calendar_id"`
	StepID       int64          `json:"step_id"`
	ItemKey      string         `json:"item_key"`
	RewardType   string         `json:"reward_type"`
	ItemCount    int64          `json:"item_count"`
	Scale        int16          `json:"scale"`
	DurationUnit sql.NullString `json:"duration_unit"`
	Position     int32          `json:"position"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type CalendarStatsDaily struct {
	WorkspaceID    string    `json:"workspace_id"`
	CalendarID     string    `json:"calendar_id"`
	StatsDate      time.Time `json:"stats_date"`
	OperationCount int64     `json:"operation_count"`
	GrantCount     int64     `json:"grant_count"`
	UniqueUsers    int64     `json:"unique_users"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type CalendarStep struct {
	ID          int64     `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	CalendarID  string    `json:"calendar_id"`
	Position    int32     `json:"position"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
