// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.adminAddCodeStmt, err = db.PrepareContext(ctx, adminAddCode); err != nil {
		return nil, fmt.Errorf("error preparing query AdminAddCode: %w", err)
	}
	if q.adminDeleteAvailableCodesStmt, err = db.PrepareContext(ctx, adminDeleteAvailableCodes); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteAvailableCodes: %w", err)
	}
	if q.adminDeleteCompletedCodesStmt, err = db.PrepareContext(ctx, adminDeleteCompletedCodes); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteCompletedCodes: %w", err)
	}
	if q.adminDeleteIssuedCodesStmt, err = db.PrepareContext(ctx, adminDeleteIssuedCodes); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteIssuedCodes: %w", err)
	}
	if q.adminDeleteLocalizationStmt, err = db.PrepareContext(ctx, adminDeleteLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteLocalization: %w", err)
	}
	if q.adminDeleteOfferStmt, err = db.PrepareContext(ctx, adminDeleteOffer); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteOffer: %w", err)
	}
	if q.adminDeleteRewardStmt, err = db.PrepareContext(ctx, adminDeleteReward); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteReward: %w", err)
	}
	if q.adminGetCodeStatsStmt, err = db.PrepareContext(ctx, adminGetCodeStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetCodeStats: %w", err)
	}
	if q.adminGetOfferStmt, err = db.PrepareContext(ctx, adminGetOffer); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetOffer: %w", err)
	}
	if q.adminGetOfferStatsStmt, err = db.PrepareContext(ctx, adminGetOfferStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetOfferStats: %w", err)
	}
	if q.adminListAssignmentEventsStmt, err = db.PrepareContext(ctx, adminListAssignmentEvents); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListAssignmentEvents: %w", err)
	}
	if q.adminListAssignmentsStmt, err = db.PrepareContext(ctx, adminListAssignments); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListAssignments: %w", err)
	}
	if q.adminListCodesStmt, err = db.PrepareContext(ctx, adminListCodes); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListCodes: %w", err)
	}
	if q.adminListDailyStatsStmt, err = db.PrepareContext(ctx, adminListDailyStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListDailyStats: %w", err)
	}
	if q.adminListOfferBundleRewardsStmt, err = db.PrepareContext(ctx, adminListOfferBundleRewards); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListOfferBundleRewards: %w", err)
	}
	if q.adminListOfferBundlesStmt, err = db.PrepareContext(ctx, adminListOfferBundles); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListOfferBundles: %w", err)
	}
	if q.adminListOfferIDsStmt, err = db.PrepareContext(ctx, adminListOfferIDs); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListOfferIDs: %w", err)
	}
	if q.adminUpsertLocalizationStmt, err = db.PrepareContext(ctx, adminUpsertLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertLocalization: %w", err)
	}
	if q.adminUpsertOfferStmt, err = db.PrepareContext(ctx, adminUpsertOffer); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertOffer: %w", err)
	}
	if q.adminUpsertRewardStmt, err = db.PrepareContext(ctx, adminUpsertReward); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertReward: %w", err)
	}
	if q.completeAssignmentStmt, err = db.PrepareContext(ctx, completeAssignment); err != nil {
		return nil, fmt.Errorf("error preparing query CompleteAssignment: %w", err)
	}
	if q.createAssignmentStmt, err = db.PrepareContext(ctx, createAssignment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAssignment: %w", err)
	}
	if q.createAssignmentEventStmt, err = db.PrepareContext(ctx, createAssignmentEvent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAssignmentEvent: %w", err)
	}
	if q.createGeneratedCodeStmt, err = db.PrepareContext(ctx, createGeneratedCode); err != nil {
		return nil, fmt.Errorf("error preparing query CreateGeneratedCode: %w", err)
	}
	if q.getActiveOfferStmt, err = db.PrepareContext(ctx, getActiveOffer); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveOffer: %w", err)
	}
	if q.getAssignmentStmt, err = db.PrepareContext(ctx, getAssignment); err != nil {
		return nil, fmt.Errorf("error preparing query GetAssignment: %w", err)
	}
	if q.getAssignmentByIDStmt, err = db.PrepareContext(ctx, getAssignmentByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAssignmentByID: %w", err)
	}
	if q.getAssignmentForUpdateStmt, err = db.PrepareContext(ctx, getAssignmentForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetAssignmentForUpdate: %w", err)
	}
	if q.getAvailableCodeForUpdateStmt, err = db.PrepareContext(ctx, getAvailableCodeForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetAvailableCodeForUpdate: %w", err)
	}
	if q.getCodeByValueStmt, err = db.PrepareContext(ctx, getCodeByValue); err != nil {
		return nil, fmt.Errorf("error preparing query GetCodeByValue: %w", err)
	}
	if q.getLocalizationStmt, err = db.PrepareContext(ctx, getLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query GetLocalization: %w", err)
	}
	if q.listActiveOfferCatalogStmt, err = db.PrepareContext(ctx, listActiveOfferCatalog); err != nil {
		return nil, fmt.Errorf("error preparing query ListActiveOfferCatalog: %w", err)
	}
	if q.listLocalizationsStmt, err = db.PrepareContext(ctx, listLocalizations); err != nil {
		return nil, fmt.Errorf("error preparing query ListLocalizations: %w", err)
	}
	if q.listRewardsStmt, err = db.PrepareContext(ctx, listRewards); err != nil {
		return nil, fmt.Errorf("error preparing query ListRewards: %w", err)
	}
	if q.listUserAssignmentsStmt, err = db.PrepareContext(ctx, listUserAssignments); err != nil {
		return nil, fmt.Errorf("error preparing query ListUserAssignments: %w", err)
	}
	if q.markCodeCompletedStmt, err = db.PrepareContext(ctx, markCodeCompleted); err != nil {
		return nil, fmt.Errorf("error preparing query MarkCodeCompleted: %w", err)
	}
	if q.markCodeIssuedStmt, err = db.PrepareContext(ctx, markCodeIssued); err != nil {
		return nil, fmt.Errorf("error preparing query MarkCodeIssued: %w", err)
	}
	if q.refreshDailyStatsStmt, err = db.PrepareContext(ctx, refreshDailyStats); err != nil {
		return nil, fmt.Errorf("error preparing query RefreshDailyStats: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.adminAddCodeStmt != nil {
		if cerr := q.adminAddCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminAddCodeStmt: %w", cerr)
		}
	}
	if q.adminDeleteAvailableCodesStmt != nil {
		if cerr := q.adminDeleteAvailableCodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteAvailableCodesStmt: %w", cerr)
		}
	}
	if q.adminDeleteCompletedCodesStmt != nil {
		if cerr := q.adminDeleteCompletedCodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteCompletedCodesStmt: %w", cerr)
		}
	}
	if q.adminDeleteIssuedCodesStmt != nil {
		if cerr := q.adminDeleteIssuedCodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteIssuedCodesStmt: %w", cerr)
		}
	}
	if q.adminDeleteLocalizationStmt != nil {
		if cerr := q.adminDeleteLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteLocalizationStmt: %w", cerr)
		}
	}
	if q.adminDeleteOfferStmt != nil {
		if cerr := q.adminDeleteOfferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteOfferStmt: %w", cerr)
		}
	}
	if q.adminDeleteRewardStmt != nil {
		if cerr := q.adminDeleteRewardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteRewardStmt: %w", cerr)
		}
	}
	if q.adminGetCodeStatsStmt != nil {
		if cerr := q.adminGetCodeStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetCodeStatsStmt: %w", cerr)
		}
	}
	if q.adminGetOfferStmt != nil {
		if cerr := q.adminGetOfferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetOfferStmt: %w", cerr)
		}
	}
	if q.adminGetOfferStatsStmt != nil {
		if cerr := q.adminGetOfferStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetOfferStatsStmt: %w", cerr)
		}
	}
	if q.adminListAssignmentEventsStmt != nil {
		if cerr := q.adminListAssignmentEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListAssignmentEventsStmt: %w", cerr)
		}
	}
	if q.adminListAssignmentsStmt != nil {
		if cerr := q.adminListAssignmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListAssignmentsStmt: %w", cerr)
		}
	}
	if q.adminListCodesStmt != nil {
		if cerr := q.adminListCodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListCodesStmt: %w", cerr)
		}
	}
	if q.adminListDailyStatsStmt != nil {
		if cerr := q.adminListDailyStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListDailyStatsStmt: %w", cerr)
		}
	}
	if q.adminListOfferBundleRewardsStmt != nil {
		if cerr := q.adminListOfferBundleRewardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListOfferBundleRewardsStmt: %w", cerr)
		}
	}
	if q.adminListOfferBundlesStmt != nil {
		if cerr := q.adminListOfferBundlesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListOfferBundlesStmt: %w", cerr)
		}
	}
	if q.adminListOfferIDsStmt != nil {
		if cerr := q.adminListOfferIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListOfferIDsStmt: %w", cerr)
		}
	}
	if q.adminUpsertLocalizationStmt != nil {
		if cerr := q.adminUpsertLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertLocalizationStmt: %w", cerr)
		}
	}
	if q.adminUpsertOfferStmt != nil {
		if cerr := q.adminUpsertOfferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertOfferStmt: %w", cerr)
		}
	}
	if q.adminUpsertRewardStmt != nil {
		if cerr := q.adminUpsertRewardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertRewardStmt: %w", cerr)
		}
	}
	if q.completeAssignmentStmt != nil {
		if cerr := q.completeAssignmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing completeAssignmentStmt: %w", cerr)
		}
	}
	if q.createAssignmentStmt != nil {
		if cerr := q.createAssignmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAssignmentStmt: %w", cerr)
		}
	}
	if q.createAssignmentEventStmt != nil {
		if cerr := q.createAssignmentEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAssignmentEventStmt: %w", cerr)
		}
	}
	if q.createGeneratedCodeStmt != nil {
		if cerr := q.createGeneratedCodeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createGeneratedCodeStmt: %w", cerr)
		}
	}
	if q.getActiveOfferStmt != nil {
		if cerr := q.getActiveOfferStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveOfferStmt: %w", cerr)
		}
	}
	if q.getAssignmentStmt != nil {
		if cerr := q.getAssignmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAssignmentStmt: %w", cerr)
		}
	}
	if q.getAssignmentByIDStmt != nil {
		if cerr := q.getAssignmentByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAssignmentByIDStmt: %w", cerr)
		}
	}
	if q.getAssignmentForUpdateStmt != nil {
		if cerr := q.getAssignmentForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAssignmentForUpdateStmt: %w", cerr)
		}
	}
	if q.getAvailableCodeForUpdateStmt != nil {
		if cerr := q.getAvailableCodeForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAvailableCodeForUpdateStmt: %w", cerr)
		}
	}
	if q.getCodeByValueStmt != nil {
		if cerr := q.getCodeByValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCodeByValueStmt: %w", cerr)
		}
	}
	if q.getLocalizationStmt != nil {
		if cerr := q.getLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLocalizationStmt: %w", cerr)
		}
	}
	if q.listActiveOfferCatalogStmt != nil {
		if cerr := q.listActiveOfferCatalogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listActiveOfferCatalogStmt: %w", cerr)
		}
	}
	if q.listLocalizationsStmt != nil {
		if cerr := q.listLocalizationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLocalizationsStmt: %w", cerr)
		}
	}
	if q.listRewardsStmt != nil {
		if cerr := q.listRewardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRewardsStmt: %w", cerr)
		}
	}
	if q.listUserAssignmentsStmt != nil {
		if cerr := q.listUserAssignmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUserAssignmentsStmt: %w", cerr)
		}
	}
	if q.markCodeCompletedStmt != nil {
		if cerr := q.markCodeCompletedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markCodeCompletedStmt: %w", cerr)
		}
	}
	if q.markCodeIssuedStmt != nil {
		if cerr := q.markCodeIssuedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markCodeIssuedStmt: %w", cerr)
		}
	}
	if q.refreshDailyStatsStmt != nil {
		if cerr := q.refreshDailyStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing refreshDailyStatsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                              DBTX
	tx                              *sql.Tx
	adminAddCodeStmt                *sql.Stmt
	adminDeleteAvailableCodesStmt   *sql.Stmt
	adminDeleteCompletedCodesStmt   *sql.Stmt
	adminDeleteIssuedCodesStmt      *sql.Stmt
	adminDeleteLocalizationStmt     *sql.Stmt
	adminDeleteOfferStmt            *sql.Stmt
	adminDeleteRewardStmt           *sql.Stmt
	adminGetCodeStatsStmt           *sql.Stmt
	adminGetOfferStmt               *sql.Stmt
	adminGetOfferStatsStmt          *sql.Stmt
	adminListAssignmentEventsStmt   *sql.Stmt
	adminListAssignmentsStmt        *sql.Stmt
	adminListCodesStmt              *sql.Stmt
	adminListDailyStatsStmt         *sql.Stmt
	adminListOfferBundleRewardsStmt *sql.Stmt
	adminListOfferBundlesStmt       *sql.Stmt
	adminListOfferIDsStmt           *sql.Stmt
	adminUpsertLocalizationStmt     *sql.Stmt
	adminUpsertOfferStmt            *sql.Stmt
	adminUpsertRewardStmt           *sql.Stmt
	completeAssignmentStmt          *sql.Stmt
	createAssignmentStmt            *sql.Stmt
	createAssignmentEventStmt       *sql.Stmt
	createGeneratedCodeStmt         *sql.Stmt
	getActiveOfferStmt              *sql.Stmt
	getAssignmentStmt               *sql.Stmt
	getAssignmentByIDStmt           *sql.Stmt
	getAssignmentForUpdateStmt      *sql.Stmt
	getAvailableCodeForUpdateStmt   *sql.Stmt
	getCodeByValueStmt              *sql.Stmt
	getLocalizationStmt             *sql.Stmt
	listActiveOfferCatalogStmt      *sql.Stmt
	listLocalizationsStmt           *sql.Stmt
	listRewardsStmt                 *sql.Stmt
	listUserAssignmentsStmt         *sql.Stmt
	markCodeCompletedStmt           *sql.Stmt
	markCodeIssuedStmt              *sql.Stmt
	refreshDailyStatsStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                              tx,
		tx:                              tx,
		adminAddCodeStmt:                q.adminAddCodeStmt,
		adminDeleteAvailableCodesStmt:   q.adminDeleteAvailableCodesStmt,
		adminDeleteCompletedCodesStmt:   q.adminDeleteCompletedCodesStmt,
		adminDeleteIssuedCodesStmt:      q.adminDeleteIssuedCodesStmt,
		adminDeleteLocalizationStmt:     q.adminDeleteLocalizationStmt,
		adminDeleteOfferStmt:            q.adminDeleteOfferStmt,
		adminDeleteRewardStmt:           q.adminDeleteRewardStmt,
		adminGetCodeStatsStmt:           q.adminGetCodeStatsStmt,
		adminGetOfferStmt:               q.adminGetOfferStmt,
		adminGetOfferStatsStmt:          q.adminGetOfferStatsStmt,
		adminListAssignmentEventsStmt:   q.adminListAssignmentEventsStmt,
		adminListAssignmentsStmt:        q.adminListAssignmentsStmt,
		adminListCodesStmt:              q.adminListCodesStmt,
		adminListDailyStatsStmt:         q.adminListDailyStatsStmt,
		adminListOfferBundleRewardsStmt: q.adminListOfferBundleRewardsStmt,
		adminListOfferBundlesStmt:       q.adminListOfferBundlesStmt,
		adminListOfferIDsStmt:           q.adminListOfferIDsStmt,
		adminUpsertLocalizationStmt:     q.adminUpsertLocalizationStmt,
		adminUpsertOfferStmt:            q.adminUpsertOfferStmt,
		adminUpsertRewardStmt:           q.adminUpsertRewardStmt,
		completeAssignmentStmt:          q.completeAssignmentStmt,
		createAssignmentStmt:            q.createAssignmentStmt,
		createAssignmentEventStmt:       q.createAssignmentEventStmt,
		createGeneratedCodeStmt:         q.createGeneratedCodeStmt,
		getActiveOfferStmt:              q.getActiveOfferStmt,
		getAssignmentStmt:               q.getAssignmentStmt,
		getAssignmentByIDStmt:           q.getAssignmentByIDStmt,
		getAssignmentForUpdateStmt:      q.getAssignmentForUpdateStmt,
		getAvailableCodeForUpdateStmt:   q.getAvailableCodeForUpdateStmt,
		getCodeByValueStmt:              q.getCodeByValueStmt,
		getLocalizationStmt:             q.getLocalizationStmt,
		listActiveOfferCatalogStmt:      q.listActiveOfferCatalogStmt,
		listLocalizationsStmt:           q.listLocalizationsStmt,
		listRewardsStmt:                 q.listRewardsStmt,
		listUserAssignmentsStmt:         q.listUserAssignmentsStmt,
		markCodeCompletedStmt:           q.markCodeCompletedStmt,
		markCodeIssuedStmt:              q.markCodeIssuedStmt,
		refreshDailyStatsStmt:           q.refreshDailyStatsStmt,
	}
}
