// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const adminAddCode = `-- name: AdminAddCode :execrows
INSERT INTO cpa_code (workspace_id, cpa_id, code, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, cpa_id, code) DO NOTHING
`

type AdminAddCodeParams struct {
	WorkspaceID string        `json:"workspace_id"`
	CpaID       string        `json:"cpa_id"`
	Code        string        `json:"code"`
	Source      CpaCodeSource `json:"source"`
}

func (q *Queries) AdminAddCode(ctx context.Context, arg AdminAddCodeParams) (int64, error) {
	result, err := q.exec(ctx, q.adminAddCodeStmt, adminAddCode,
		arg.WorkspaceID,
		arg.CpaID,
		arg.Code,
		arg.Source,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteAvailableCodes = `-- name: AdminDeleteAvailableCodes :execrows
UPDATE cpa_code
SET status = 'deleted', deleted_at = now(), updated_at = now()
WHERE workspace_id = $1
  AND cpa_id = $2
  AND status = 'available'
`

type AdminDeleteAvailableCodesParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) AdminDeleteAvailableCodes(ctx context.Context, arg AdminDeleteAvailableCodesParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteAvailableCodesStmt, adminDeleteAvailableCodes, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteCompletedCodes = `-- name: AdminDeleteCompletedCodes :execrows
UPDATE cpa_code c
SET status = 'deleted', deleted_at = now(), updated_at = now()
FROM cpa_assignment a
WHERE a.code_id = c.id
  AND a.workspace_id = $1
  AND a.cpa_id = $2
  AND a.status = 'completed'
  AND c.status = 'completed'
`

type AdminDeleteCompletedCodesParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) AdminDeleteCompletedCodes(ctx context.Context, arg AdminDeleteCompletedCodesParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteCompletedCodesStmt, adminDeleteCompletedCodes, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteIssuedCodes = `-- name: AdminDeleteIssuedCodes :execrows
UPDATE cpa_code c
SET status = 'deleted', deleted_at = now(), updated_at = now()
FROM cpa_assignment a
WHERE a.code_id = c.id
  AND a.workspace_id = $1
  AND a.cpa_id = $2
  AND a.status = 'issued'
  AND c.status = 'issued'
`

type AdminDeleteIssuedCodesParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) AdminDeleteIssuedCodes(ctx context.Context, arg AdminDeleteIssuedCodesParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteIssuedCodesStmt, adminDeleteIssuedCodes, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteLocalization = `-- name: AdminDeleteLocalization :execrows
DELETE FROM cpa_localization
WHERE workspace_id = $1 AND cpa_id = $2 AND locale = $3
`

type AdminDeleteLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	Locale      string `json:"locale"`
}

func (q *Queries) AdminDeleteLocalization(ctx context.Context, arg AdminDeleteLocalizationParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteLocalizationStmt, adminDeleteLocalization, arg.WorkspaceID, arg.CpaID, arg.Locale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteOffer = `-- name: AdminDeleteOffer :execrows
DELETE FROM cpa_offer
WHERE workspace_id = $1 AND id = $2
`

type AdminDeleteOfferParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) AdminDeleteOffer(ctx context.Context, arg AdminDeleteOfferParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteOfferStmt, adminDeleteOffer, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteReward = `-- name: AdminDeleteReward :execrows
DELETE FROM cpa_reward
WHERE workspace_id = $1 AND cpa_id = $2 AND reward_key = $3
`

type AdminDeleteRewardParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	RewardKey   string `json:"reward_key"`
}

func (q *Queries) AdminDeleteReward(ctx context.Context, arg AdminDeleteRewardParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteRewardStmt, adminDeleteReward, arg.WorkspaceID, arg.CpaID, arg.RewardKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminGetCodeStats = `-- name: AdminGetCodeStats :one
SELECT
    COUNT(*) AS codes_total,
    COALESCE(SUM((status = 'available')::int), 0)::bigint AS available_total,
    COALESCE(SUM((status = 'issued')::int), 0)::bigint AS issued_total,
    COALESCE(SUM((status = 'completed')::int), 0)::bigint AS completed_total,
    COALESCE(SUM((status = 'deleted')::int), 0)::bigint AS deleted_total
FROM cpa_code
WHERE workspace_id = $1 AND cpa_id = $2
`

type AdminGetCodeStatsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

type AdminGetCodeStatsRow struct {
	CodesTotal     int64 `json:"codes_total"`
	AvailableTotal int64 `json:"available_total"`
	IssuedTotal    int64 `json:"issued_total"`
	CompletedTotal int64 `json:"completed_total"`
	DeletedTotal   int64 `json:"deleted_total"`
}

func (q *Queries) AdminGetCodeStats(ctx context.Context, arg AdminGetCodeStatsParams) (AdminGetCodeStatsRow, error) {
	row := q.queryRow(ctx, q.adminGetCodeStatsStmt, adminGetCodeStats, arg.WorkspaceID, arg.CpaID)
	var i AdminGetCodeStatsRow
	err := row.Scan(
		&i.CodesTotal,
		&i.AvailableTotal,
		&i.IssuedTotal,
		&i.CompletedTotal,
		&i.DeletedTotal,
	)
	return i, err
}

const adminGetOffer = `-- name: AdminGetOffer :one
SELECT workspace_id, id, payload, target, code_mode, code_source, shared_code, generated_length, generated_alphabet, is_active, start_at, end_at, created_at, updated_at
FROM cpa_offer
WHERE workspace_id = $1 AND id = $2
LIMIT 1
`

type AdminGetOfferParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) AdminGetOffer(ctx context.Context, arg AdminGetOfferParams) (CpaOffer, error) {
	row := q.queryRow(ctx, q.adminGetOfferStmt, adminGetOffer, arg.WorkspaceID, arg.ID)
	var i CpaOffer
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.Payload,
		&i.Target,
		&i.CodeMode,
		&i.CodeSource,
		&i.SharedCode,
		&i.GeneratedLength,
		&i.GeneratedAlphabet,
		&i.IsActive,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetOfferStats = `-- name: AdminGetOfferStats :one
SELECT
    COUNT(*) AS assignments_total,
    COALESCE(SUM((status = 'issued')::int), 0)::bigint AS issued_total,
    COALESCE(SUM((status = 'completed')::int), 0)::bigint AS completed_total,
    COALESCE(SUM((deleted_at IS NOT NULL)::int), 0)::bigint AS deleted_total
FROM cpa_assignment
WHERE workspace_id = $1 AND cpa_id = $2
`

type AdminGetOfferStatsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

type AdminGetOfferStatsRow struct {
	AssignmentsTotal int64 `json:"assignments_total"`
	IssuedTotal      int64 `json:"issued_total"`
	CompletedTotal   int64 `json:"completed_total"`
	DeletedTotal     int64 `json:"deleted_total"`
}

func (q *Queries) AdminGetOfferStats(ctx context.Context, arg AdminGetOfferStatsParams) (AdminGetOfferStatsRow, error) {
	row := q.queryRow(ctx, q.adminGetOfferStatsStmt, adminGetOfferStats, arg.WorkspaceID, arg.CpaID)
	var i AdminGetOfferStatsRow
	err := row.Scan(
		&i.AssignmentsTotal,
		&i.IssuedTotal,
		&i.CompletedTotal,
		&i.DeletedTotal,
	)
	return i, err
}

const adminListAssignmentEvents = `-- name: AdminListAssignmentEvents :many
SELECT id, workspace_id, cpa_id, assignment_id, event_type, occurred_at, created_at
FROM cpa_assignment_event
WHERE workspace_id = $1
  AND cpa_id = $2
  AND (NULLIF($3, '')::cpa_assignment_event_type IS NULL OR event_type = NULLIF($3, '')::cpa_assignment_event_type)
ORDER BY occurred_at DESC, id DESC
LIMIT $4 OFFSET $5
`

type AdminListAssignmentEventsParams struct {
	WorkspaceID string      `json:"workspace_id"`
	CpaID       string      `json:"cpa_id"`
	Column3     interface{} `json:"column_3"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) AdminListAssignmentEvents(ctx context.Context, arg AdminListAssignmentEventsParams) ([]CpaAssignmentEvent, error) {
	rows, err := q.query(ctx, q.adminListAssignmentEventsStmt, adminListAssignmentEvents,
		arg.WorkspaceID,
		arg.CpaID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaAssignmentEvent
	for rows.Next() {
		var i CpaAssignmentEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CpaID,
			&i.AssignmentID,
			&i.EventType,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAssignments = `-- name: AdminListAssignments :many
SELECT id, workspace_id, cpa_id, app_id, platform_id, platform_user_id, code_id, code, code_mode, rewards_snapshot, status, issued_at, completed_at, deleted_at, updated_at
FROM cpa_assignment
WHERE workspace_id = $1
  AND cpa_id = $2
  AND (NULLIF($3, '')::cpa_assignment_status IS NULL OR status = NULLIF($3, '')::cpa_assignment_status)
ORDER BY issued_at DESC, id DESC
LIMIT $4 OFFSET $5
`

type AdminListAssignmentsParams struct {
	WorkspaceID string      `json:"workspace_id"`
	CpaID       string      `json:"cpa_id"`
	Column3     interface{} `json:"column_3"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) AdminListAssignments(ctx context.Context, arg AdminListAssignmentsParams) ([]CpaAssignment, error) {
	rows, err := q.query(ctx, q.adminListAssignmentsStmt, adminListAssignments,
		arg.WorkspaceID,
		arg.CpaID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaAssignment
	for rows.Next() {
		var i CpaAssignment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CpaID,
			&i.AppID,
			&i.PlatformID,
			&i.PlatformUserID,
			&i.CodeID,
			&i.Code,
			&i.CodeMode,
			&i.RewardsSnapshot,
			&i.Status,
			&i.IssuedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListCodes = `-- name: AdminListCodes :many
SELECT id, workspace_id, cpa_id, code, source, status, created_at, updated_at, deleted_at
FROM cpa_code
WHERE workspace_id = $1
  AND cpa_id = $2
  AND (NULLIF($3, '')::cpa_code_status IS NULL OR status = NULLIF($3, '')::cpa_code_status)
ORDER BY id DESC
LIMIT $4 OFFSET $5
`

type AdminListCodesParams struct {
	WorkspaceID string      `json:"workspace_id"`
	CpaID       string      `json:"cpa_id"`
	Column3     interface{} `json:"column_3"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) AdminListCodes(ctx context.Context, arg AdminListCodesParams) ([]CpaCode, error) {
	rows, err := q.query(ctx, q.adminListCodesStmt, adminListCodes,
		arg.WorkspaceID,
		arg.CpaID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaCode
	for rows.Next() {
		var i CpaCode
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CpaID,
			&i.Code,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListDailyStats = `-- name: AdminListDailyStats :many
SELECT workspace_id, cpa_id, stats_date, issued_count, completed_count, unique_users, updated_at
FROM cpa_stats_daily
WHERE workspace_id = $1
  AND cpa_id = $2
  AND stats_date >= $3
  AND stats_date <= $4
ORDER BY stats_date
`

type AdminListDailyStatsParams struct {
	WorkspaceID string    `json:"workspace_id"`
	CpaID       string    `json:"cpa_id"`
	StatsDate   time.Time `json:"stats_date"`
	StatsDate_2 time.Time `json:"stats_date_2"`
}

func (q *Queries) AdminListDailyStats(ctx context.Context, arg AdminListDailyStatsParams) ([]CpaStatsDaily, error) {
	rows, err := q.query(ctx, q.adminListDailyStatsStmt, adminListDailyStats,
		arg.WorkspaceID,
		arg.CpaID,
		arg.StatsDate,
		arg.StatsDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaStatsDaily
	for rows.Next() {
		var i CpaStatsDaily
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CpaID,
			&i.StatsDate,
			&i.IssuedCount,
			&i.CompletedCount,
			&i.UniqueUsers,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOfferBundleRewards = `-- name: AdminListOfferBundleRewards :many
SELECT
    o.workspace_id,
    o.id AS cpa_id,
    r.reward_key,
    r.reward_type,
    r.quantity AS reward_quantity,
    r.scale AS reward_scale,
    r.duration_unit
FROM (
    SELECT workspace_id, id, payload, target, code_mode, code_source, shared_code, generated_length, generated_alphabet, is_active, start_at, end_at, created_at, updated_at
    FROM cpa_offer
    WHERE cpa_offer.workspace_id = $1
    ORDER BY cpa_offer.created_at DESC, cpa_offer.id
    LIMIT NULLIF($3::integer, 0) OFFSET $2::integer
) o
JOIN cpa_reward r
    ON r.workspace_id = o.workspace_id
   AND r.cpa_id = o.id
ORDER BY o.created_at DESC, o.id, r.id
`

type AdminListOfferBundleRewardsParams struct {
	WorkspaceID string `json:"workspace_id"`
	PageOffset  int32  `json:"page_offset"`
	PageLimit   int32  `json:"page_limit"`
}

type AdminListOfferBundleRewardsRow struct {
	WorkspaceID    string              `json:"workspace_id"`
	CpaID          string              `json:"cpa_id"`
	RewardKey      string              `json:"reward_key"`
	RewardType     CpaRewardType       `json:"reward_type"`
	RewardQuantity int64               `json:"reward_quantity"`
	RewardScale    int32               `json:"reward_scale"`
	DurationUnit   NullCpaDurationUnit `json:"duration_unit"`
}

func (q *Queries) AdminListOfferBundleRewards(ctx context.Context, arg AdminListOfferBundleRewardsParams) ([]AdminListOfferBundleRewardsRow, error) {
	rows, err := q.query(ctx, q.adminListOfferBundleRewardsStmt, adminListOfferBundleRewards, arg.WorkspaceID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOfferBundleRewardsRow
	for rows.Next() {
		var i AdminListOfferBundleRewardsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CpaID,
			&i.RewardKey,
			&i.RewardType,
			&i.RewardQuantity,
			&i.RewardScale,
			&i.DurationUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOfferBundles = `-- name: AdminListOfferBundles :many
SELECT
    o.workspace_id, o.id, o.payload, o.target, o.code_mode, o.code_source, o.shared_code, o.generated_length, o.generated_alphabet, o.is_active, o.start_at, o.end_at, o.created_at, o.updated_at,
    l.locale,
    l.title AS localization_title,
    l.description AS localization_description
FROM (
    SELECT workspace_id, id, payload, target, code_mode, code_source, shared_code, generated_length, generated_alphabet, is_active, start_at, end_at, created_at, updated_at
    FROM cpa_offer
    WHERE cpa_offer.workspace_id = $1
    ORDER BY cpa_offer.created_at DESC, cpa_offer.id
    LIMIT NULLIF($3::integer, 0) OFFSET $2::integer
) o
LEFT JOIN cpa_localization l
    ON l.workspace_id = o.workspace_id
   AND l.cpa_id = o.id
ORDER BY o.created_at DESC, o.id, l.locale
`

type AdminListOfferBundlesParams struct {
	WorkspaceID string `json:"workspace_id"`
	PageOffset  int32  `json:"page_offset"`
	PageLimit   int32  `json:"page_limit"`
}

type AdminListOfferBundlesRow struct {
	WorkspaceID             string                `json:"workspace_id"`
	ID                      string                `json:"id"`
	Payload                 json.RawMessage       `json:"payload"`
	Target                  pqtype.NullRawMessage `json:"target"`
	CodeMode                CpaCodeMode           `json:"code_mode"`
	CodeSource              NullCpaCodeSource     `json:"code_source"`
	SharedCode              sql.NullString        `json:"shared_code"`
	GeneratedLength         sql.NullInt16         `json:"generated_length"`
	GeneratedAlphabet       sql.NullString        `json:"generated_alphabet"`
	IsActive                bool                  `json:"is_active"`
	StartAt                 sql.NullTime          `json:"start_at"`
	EndAt                   sql.NullTime          `json:"end_at"`
	CreatedAt               time.Time             `json:"created_at"`
	UpdatedAt               time.Time             `json:"updated_at"`
	Locale                  sql.NullString        `json:"locale"`
	LocalizationTitle       sql.NullString        `json:"localization_title"`
	LocalizationDescription sql.NullString        `json:"localization_description"`
}

func (q *Queries) AdminListOfferBundles(ctx context.Context, arg AdminListOfferBundlesParams) ([]AdminListOfferBundlesRow, error) {
	rows, err := q.query(ctx, q.adminListOfferBundlesStmt, adminListOfferBundles, arg.WorkspaceID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOfferBundlesRow
	for rows.Next() {
		var i AdminListOfferBundlesRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.Payload,
			&i.Target,
			&i.CodeMode,
			&i.CodeSource,
			&i.SharedCode,
			&i.GeneratedLength,
			&i.GeneratedAlphabet,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Locale,
			&i.LocalizationTitle,
			&i.LocalizationDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOfferIDs = `-- name: AdminListOfferIDs :many
SELECT id
FROM cpa_offer
WHERE workspace_id = $1
`

func (q *Queries) AdminListOfferIDs(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.query(ctx, q.adminListOfferIDsStmt, adminListOfferIDs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpsertLocalization = `-- name: AdminUpsertLocalization :exec
WITH workspace_lock AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
)
INSERT INTO cpa_localization (
    workspace_id, cpa_id, locale, title, description
)
SELECT $1, $2, $3, $4, $5
FROM workspace_lock
ON CONFLICT (workspace_id, cpa_id, locale) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = now()
`

type AdminUpsertLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	Locale      string `json:"locale"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) AdminUpsertLocalization(ctx context.Context, arg AdminUpsertLocalizationParams) error {
	_, err := q.exec(ctx, q.adminUpsertLocalizationStmt, adminUpsertLocalization,
		arg.WorkspaceID,
		arg.CpaID,
		arg.Locale,
		arg.Title,
		arg.Description,
	)
	return err
}

const adminUpsertOffer = `-- name: AdminUpsertOffer :exec
INSERT INTO cpa_offer (
    workspace_id, id, payload, target, code_mode, code_source, shared_code,
    generated_length, generated_alphabet, is_active, start_at, end_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (workspace_id, id) DO UPDATE SET
    payload = EXCLUDED.payload,
    target = EXCLUDED.target,
    code_mode = EXCLUDED.code_mode,
    code_source = EXCLUDED.code_source,
    shared_code = EXCLUDED.shared_code,
    generated_length = EXCLUDED.generated_length,
    generated_alphabet = EXCLUDED.generated_alphabet,
    is_active = EXCLUDED.is_active,
    start_at = EXCLUDED.start_at,
    end_at = EXCLUDED.end_at,
    updated_at = now()
`

type AdminUpsertOfferParams struct {
	WorkspaceID       string                `json:"workspace_id"`
	ID                string                `json:"id"`
	Payload           json.RawMessage       `json:"payload"`
	Target            pqtype.NullRawMessage `json:"target"`
	CodeMode          CpaCodeMode           `json:"code_mode"`
	CodeSource        NullCpaCodeSource     `json:"code_source"`
	SharedCode        sql.NullString        `json:"shared_code"`
	GeneratedLength   sql.NullInt16         `json:"generated_length"`
	GeneratedAlphabet sql.NullString        `json:"generated_alphabet"`
	IsActive          bool                  `json:"is_active"`
	StartAt           sql.NullTime          `json:"start_at"`
	EndAt             sql.NullTime          `json:"end_at"`
}

func (q *Queries) AdminUpsertOffer(ctx context.Context, arg AdminUpsertOfferParams) error {
	_, err := q.exec(ctx, q.adminUpsertOfferStmt, adminUpsertOffer,
		arg.WorkspaceID,
		arg.ID,
		arg.Payload,
		arg.Target,
		arg.CodeMode,
		arg.CodeSource,
		arg.SharedCode,
		arg.GeneratedLength,
		arg.GeneratedAlphabet,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
	)
	return err
}

const adminUpsertReward = `-- name: AdminUpsertReward :exec
WITH workspace_lock AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
)
INSERT INTO cpa_reward (
    workspace_id, cpa_id, reward_key, reward_type, quantity, scale, duration_unit
)
SELECT $1, $2, $3, $4, $5, $6, $7
FROM workspace_lock
ON CONFLICT (workspace_id, cpa_id, reward_key) DO UPDATE SET
    reward_type = EXCLUDED.reward_type,
    quantity = EXCLUDED.quantity,
    scale = EXCLUDED.scale,
    duration_unit = EXCLUDED.duration_unit,
    updated_at = now()
`

type AdminUpsertRewardParams struct {
	WorkspaceID  string              `json:"workspace_id"`
	CpaID        string              `json:"cpa_id"`
	RewardKey    string              `json:"reward_key"`
	RewardType   CpaRewardType       `json:"reward_type"`
	Quantity     int64               `json:"quantity"`
	Scale        int32               `json:"scale"`
	DurationUnit NullCpaDurationUnit `json:"duration_unit"`
}

func (q *Queries) AdminUpsertReward(ctx context.Context, arg AdminUpsertRewardParams) error {
	_, err := q.exec(ctx, q.adminUpsertRewardStmt, adminUpsertReward,
		arg.WorkspaceID,
		arg.CpaID,
		arg.RewardKey,
		arg.RewardType,
		arg.Quantity,
		arg.Scale,
		arg.DurationUnit,
	)
	return err
}

const completeAssignment = `-- name: CompleteAssignment :execrows
UPDATE cpa_assignment
SET status = 'completed', completed_at = now(), updated_at = now()
WHERE workspace_id = $1
  AND id = $2
  AND status = 'issued'
`

type CompleteAssignmentParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          int64  `json:"id"`
}

func (q *Queries) CompleteAssignment(ctx context.Context, arg CompleteAssignmentParams) (int64, error) {
	result, err := q.exec(ctx, q.completeAssignmentStmt, completeAssignment, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO cpa_assignment (
    workspace_id, cpa_id, app_id, platform_id, platform_user_id,
    code_id, code, code_mode, rewards_snapshot
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type CreateAssignmentParams struct {
	WorkspaceID     string          `json:"workspace_id"`
	CpaID           string          `json:"cpa_id"`
	AppID           int64           `json:"app_id"`
	PlatformID      int64           `json:"platform_id"`
	PlatformUserID  string          `json:"platform_user_id"`
	CodeID          sql.NullInt64   `json:"code_id"`
	Code            string          `json:"code"`
	CodeMode        CpaCodeMode     `json:"code_mode"`
	RewardsSnapshot json.RawMessage `json:"rewards_snapshot"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (int64, error) {
	row := q.queryRow(ctx, q.createAssignmentStmt, createAssignment,
		arg.WorkspaceID,
		arg.CpaID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.CodeID,
		arg.Code,
		arg.CodeMode,
		arg.RewardsSnapshot,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createAssignmentEvent = `-- name: CreateAssignmentEvent :one
INSERT INTO cpa_assignment_event (
    workspace_id, cpa_id, assignment_id, event_type
) VALUES ($1, $2, $3, $4)
ON CONFLICT (assignment_id, event_type) DO UPDATE SET
    event_type = EXCLUDED.event_type
RETURNING id
`

type CreateAssignmentEventParams struct {
	WorkspaceID  string                 `json:"workspace_id"`
	CpaID        string                 `json:"cpa_id"`
	AssignmentID int64                  `json:"assignment_id"`
	EventType    CpaAssignmentEventType `json:"event_type"`
}

func (q *Queries) CreateAssignmentEvent(ctx context.Context, arg CreateAssignmentEventParams) (int64, error) {
	row := q.queryRow(ctx, q.createAssignmentEventStmt, createAssignmentEvent,
		arg.WorkspaceID,
		arg.CpaID,
		arg.AssignmentID,
		arg.EventType,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createGeneratedCode = `-- name: CreateGeneratedCode :one
INSERT INTO cpa_code (workspace_id, cpa_id, code, source)
VALUES ($1, $2, $3, 'generated')
RETURNING id
`

type CreateGeneratedCodeParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	Code        string `json:"code"`
}

func (q *Queries) CreateGeneratedCode(ctx context.Context, arg CreateGeneratedCodeParams) (int64, error) {
	row := q.queryRow(ctx, q.createGeneratedCodeStmt, createGeneratedCode, arg.WorkspaceID, arg.CpaID, arg.Code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActiveOffer = `-- name: GetActiveOffer :one
SELECT workspace_id, id, payload, target, code_mode, code_source, shared_code, generated_length, generated_alphabet, is_active, start_at, end_at, created_at, updated_at
FROM cpa_offer
WHERE workspace_id = $1
  AND id = $2
  AND is_active = TRUE
  AND (start_at IS NULL OR start_at <= now())
  AND (end_at IS NULL OR end_at > now())
LIMIT 1
`

type GetActiveOfferParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetActiveOffer(ctx context.Context, arg GetActiveOfferParams) (CpaOffer, error) {
	row := q.queryRow(ctx, q.getActiveOfferStmt, getActiveOffer, arg.WorkspaceID, arg.ID)
	var i CpaOffer
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.Payload,
		&i.Target,
		&i.CodeMode,
		&i.CodeSource,
		&i.SharedCode,
		&i.GeneratedLength,
		&i.GeneratedAlphabet,
		&i.IsActive,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, workspace_id, cpa_id, app_id, platform_id, platform_user_id, code_id, code, code_mode, rewards_snapshot, status, issued_at, completed_at, deleted_at, updated_at
FROM cpa_assignment
WHERE workspace_id = $1
  AND cpa_id = $2
  AND app_id = $3
  AND platform_id = $4
  AND platform_user_id = $5
LIMIT 1
`

type GetAssignmentParams struct {
	WorkspaceID    string `json:"workspace_id"`
	CpaID          string `json:"cpa_id"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
}

func (q *Queries) GetAssignment(ctx context.Context, arg GetAssignmentParams) (CpaAssignment, error) {
	row := q.queryRow(ctx, q.getAssignmentStmt, getAssignment,
		arg.WorkspaceID,
		arg.CpaID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
	)
	var i CpaAssignment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CpaID,
		&i.AppID,
		&i.PlatformID,
		&i.PlatformUserID,
		&i.CodeID,
		&i.Code,
		&i.CodeMode,
		&i.RewardsSnapshot,
		&i.Status,
		&i.IssuedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, workspace_id, cpa_id, app_id, platform_id, platform_user_id, code_id, code, code_mode, rewards_snapshot, status, issued_at, completed_at, deleted_at, updated_at
FROM cpa_assignment
WHERE workspace_id = $1 AND id = $2
LIMIT 1
`

type GetAssignmentByIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          int64  `json:"id"`
}

func (q *Queries) GetAssignmentByID(ctx context.Context, arg GetAssignmentByIDParams) (CpaAssignment, error) {
	row := q.queryRow(ctx, q.getAssignmentByIDStmt, getAssignmentByID, arg.WorkspaceID, arg.ID)
	var i CpaAssignment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CpaID,
		&i.AppID,
		&i.PlatformID,
		&i.PlatformUserID,
		&i.CodeID,
		&i.Code,
		&i.CodeMode,
		&i.RewardsSnapshot,
		&i.Status,
		&i.IssuedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentForUpdate = `-- name: GetAssignmentForUpdate :one
SELECT id, workspace_id, cpa_id, app_id, platform_id, platform_user_id, code_id, code, code_mode, rewards_snapshot, status, issued_at, completed_at, deleted_at, updated_at
FROM cpa_assignment
WHERE workspace_id = $1
  AND cpa_id = $2
  AND app_id = $3
  AND platform_id = $4
  AND platform_user_id = $5
LIMIT 1
FOR UPDATE
`

type GetAssignmentForUpdateParams struct {
	WorkspaceID    string `json:"workspace_id"`
	CpaID          string `json:"cpa_id"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
}

func (q *Queries) GetAssignmentForUpdate(ctx context.Context, arg GetAssignmentForUpdateParams) (CpaAssignment, error) {
	row := q.queryRow(ctx, q.getAssignmentForUpdateStmt, getAssignmentForUpdate,
		arg.WorkspaceID,
		arg.CpaID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
	)
	var i CpaAssignment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CpaID,
		&i.AppID,
		&i.PlatformID,
		&i.PlatformUserID,
		&i.CodeID,
		&i.Code,
		&i.CodeMode,
		&i.RewardsSnapshot,
		&i.Status,
		&i.IssuedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvailableCodeForUpdate = `-- name: GetAvailableCodeForUpdate :one
SELECT id, workspace_id, cpa_id, code, source, status, created_at, updated_at, deleted_at
FROM cpa_code
WHERE workspace_id = $1
  AND cpa_id = $2
  AND source = 'pool'
  AND status = 'available'
ORDER BY id
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type GetAvailableCodeForUpdateParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) GetAvailableCodeForUpdate(ctx context.Context, arg GetAvailableCodeForUpdateParams) (CpaCode, error) {
	row := q.queryRow(ctx, q.getAvailableCodeForUpdateStmt, getAvailableCodeForUpdate, arg.WorkspaceID, arg.CpaID)
	var i CpaCode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CpaID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCodeByValue = `-- name: GetCodeByValue :one
SELECT id, workspace_id, cpa_id, code, source, status, created_at, updated_at, deleted_at
FROM cpa_code
WHERE workspace_id = $1 AND cpa_id = $2 AND code = $3
LIMIT 1
`

type GetCodeByValueParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	Code        string `json:"code"`
}

func (q *Queries) GetCodeByValue(ctx context.Context, arg GetCodeByValueParams) (CpaCode, error) {
	row := q.queryRow(ctx, q.getCodeByValueStmt, getCodeByValue, arg.WorkspaceID, arg.CpaID, arg.Code)
	var i CpaCode
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CpaID,
		&i.Code,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLocalization = `-- name: GetLocalization :one
SELECT workspace_id, cpa_id, locale, title, description, created_at, updated_at
FROM cpa_localization
WHERE workspace_id = $1 AND cpa_id = $2 AND locale = $3
LIMIT 1
`

type GetLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
	Locale      string `json:"locale"`
}

func (q *Queries) GetLocalization(ctx context.Context, arg GetLocalizationParams) (CpaLocalization, error) {
	row := q.queryRow(ctx, q.getLocalizationStmt, getLocalization, arg.WorkspaceID, arg.CpaID, arg.Locale)
	var i CpaLocalization
	err := row.Scan(
		&i.WorkspaceID,
		&i.CpaID,
		&i.Locale,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveOfferCatalog = `-- name: ListActiveOfferCatalog :many
WITH active AS MATERIALIZED (
    SELECT o.workspace_id, o.id, o.payload, o.target, o.code_mode, o.code_source, o.shared_code, o.generated_length, o.generated_alphabet, o.is_active, o.start_at, o.end_at, o.created_at, o.updated_at
    FROM cpa_offer o
    WHERE o.workspace_id = $2
      AND o.is_active = TRUE
)
SELECT
    o.workspace_id,
    o.id,
    o.payload,
    o.target,
    o.code_mode,
    o.code_source,
    o.shared_code,
    o.generated_length,
    o.generated_alphabet,
    o.is_active,
    o.start_at,
    o.end_at,
    o.created_at,
    o.updated_at,
    l.locale AS localized_locale,
    l.title AS localized_title,
    l.description AS localized_description,
    r.reward_key,
    r.reward_type,
    r.quantity AS reward_quantity,
    r.scale AS reward_scale,
    r.duration_unit
FROM active o
LEFT JOIN cpa_localization l
    ON l.workspace_id = o.workspace_id
   AND l.cpa_id = o.id
   AND l.locale = $1
LEFT JOIN cpa_reward r
    ON r.workspace_id = o.workspace_id
   AND r.cpa_id = o.id
ORDER BY o.created_at DESC, o.id, r.id
`

type ListActiveOfferCatalogParams struct {
	Locale      string `json:"locale"`
	WorkspaceID string `json:"workspace_id"`
}

type ListActiveOfferCatalogRow struct {
	WorkspaceID          string                `json:"workspace_id"`
	ID                   string                `json:"id"`
	Payload              json.RawMessage       `json:"payload"`
	Target               pqtype.NullRawMessage `json:"target"`
	CodeMode             CpaCodeMode           `json:"code_mode"`
	CodeSource           NullCpaCodeSource     `json:"code_source"`
	SharedCode           sql.NullString        `json:"shared_code"`
	GeneratedLength      sql.NullInt16         `json:"generated_length"`
	GeneratedAlphabet    sql.NullString        `json:"generated_alphabet"`
	IsActive             bool                  `json:"is_active"`
	StartAt              sql.NullTime          `json:"start_at"`
	EndAt                sql.NullTime          `json:"end_at"`
	CreatedAt            time.Time             `json:"created_at"`
	UpdatedAt            time.Time             `json:"updated_at"`
	LocalizedLocale      sql.NullString        `json:"localized_locale"`
	LocalizedTitle       sql.NullString        `json:"localized_title"`
	LocalizedDescription sql.NullString        `json:"localized_description"`
	RewardKey            sql.NullString        `json:"reward_key"`
	RewardType           NullCpaRewardType     `json:"reward_type"`
	RewardQuantity       sql.NullInt64         `json:"reward_quantity"`
	RewardScale          sql.NullInt32         `json:"reward_scale"`
	DurationUnit         NullCpaDurationUnit   `json:"duration_unit"`
}

func (q *Queries) ListActiveOfferCatalog(ctx context.Context, arg ListActiveOfferCatalogParams) ([]ListActiveOfferCatalogRow, error) {
	rows, err := q.query(ctx, q.listActiveOfferCatalogStmt, listActiveOfferCatalog, arg.Locale, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveOfferCatalogRow
	for rows.Next() {
		var i ListActiveOfferCatalogRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.Payload,
			&i.Target,
			&i.CodeMode,
			&i.CodeSource,
			&i.SharedCode,
			&i.GeneratedLength,
			&i.GeneratedAlphabet,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocalizedLocale,
			&i.LocalizedTitle,
			&i.LocalizedDescription,
			&i.RewardKey,
			&i.RewardType,
			&i.RewardQuantity,
			&i.RewardScale,
			&i.DurationUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalizations = `-- name: ListLocalizations :many
SELECT workspace_id, cpa_id, locale, title, description, created_at, updated_at
FROM cpa_localization
WHERE workspace_id = $1 AND cpa_id = $2
ORDER BY locale
`

type ListLocalizationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) ListLocalizations(ctx context.Context, arg ListLocalizationsParams) ([]CpaLocalization, error) {
	rows, err := q.query(ctx, q.listLocalizationsStmt, listLocalizations, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaLocalization
	for rows.Next() {
		var i CpaLocalization
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.CpaID,
			&i.Locale,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRewards = `-- name: ListRewards :many
SELECT id, workspace_id, cpa_id, reward_key, reward_type, quantity, scale, duration_unit, created_at, updated_at
FROM cpa_reward
WHERE workspace_id = $1 AND cpa_id = $2
ORDER BY id
`

type ListRewardsParams struct {
	WorkspaceID string `json:"workspace_id"`
	CpaID       string `json:"cpa_id"`
}

func (q *Queries) ListRewards(ctx context.Context, arg ListRewardsParams) ([]CpaReward, error) {
	rows, err := q.query(ctx, q.listRewardsStmt, listRewards, arg.WorkspaceID, arg.CpaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaReward
	for rows.Next() {
		var i CpaReward
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CpaID,
			&i.RewardKey,
			&i.RewardType,
			&i.Quantity,
			&i.Scale,
			&i.DurationUnit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAssignments = `-- name: ListUserAssignments :many
SELECT id, workspace_id, cpa_id, app_id, platform_id, platform_user_id, code_id, code, code_mode, rewards_snapshot, status, issued_at, completed_at, deleted_at, updated_at
FROM cpa_assignment
WHERE workspace_id = $1
  AND app_id = $2
  AND platform_id = $3
  AND platform_user_id = $4
ORDER BY issued_at DESC, id DESC
`

type ListUserAssignmentsParams struct {
	WorkspaceID    string `json:"workspace_id"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
}

func (q *Queries) ListUserAssignments(ctx context.Context, arg ListUserAssignmentsParams) ([]CpaAssignment, error) {
	rows, err := q.query(ctx, q.listUserAssignmentsStmt, listUserAssignments,
		arg.WorkspaceID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CpaAssignment
	for rows.Next() {
		var i CpaAssignment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CpaID,
			&i.AppID,
			&i.PlatformID,
			&i.PlatformUserID,
			&i.CodeID,
			&i.Code,
			&i.CodeMode,
			&i.RewardsSnapshot,
			&i.Status,
			&i.IssuedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCodeCompleted = `-- name: MarkCodeCompleted :execrows
UPDATE cpa_code
SET status = 'completed', updated_at = now()
WHERE id = $1 AND status = 'issued'
`

func (q *Queries) MarkCodeCompleted(ctx context.Context, id int64) (int64, error) {
	result, err := q.exec(ctx, q.markCodeCompletedStmt, markCodeCompleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markCodeIssued = `-- name: MarkCodeIssued :execrows
UPDATE cpa_code
SET status = 'issued', updated_at = now()
WHERE id = $1 AND status = 'available'
`

func (q *Queries) MarkCodeIssued(ctx context.Context, id int64) (int64, error) {
	result, err := q.exec(ctx, q.markCodeIssuedStmt, markCodeIssued, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refreshDailyStats = `-- name: RefreshDailyStats :exec
INSERT INTO cpa_stats_daily (
    workspace_id, cpa_id, stats_date,
    issued_count, completed_count, unique_users
)
SELECT
    e.workspace_id,
    e.cpa_id,
    (e.occurred_at AT TIME ZONE 'UTC')::date,
    SUM((e.event_type = 'issued')::int)::bigint,
    SUM((e.event_type = 'completed')::int)::bigint,
    COUNT(DISTINCT e.assignment_id)::bigint
FROM cpa_assignment_event e
WHERE e.workspace_id = $3
  AND e.occurred_at >= $1
  AND e.occurred_at < $2
GROUP BY e.workspace_id, e.cpa_id, (e.occurred_at AT TIME ZONE 'UTC')::date
ON CONFLICT (workspace_id, cpa_id, stats_date) DO UPDATE SET
    issued_count = EXCLUDED.issued_count,
    completed_count = EXCLUDED.completed_count,
    unique_users = EXCLUDED.unique_users,
    updated_at = now()
`

type RefreshDailyStatsParams struct {
	OccurredAt         time.Time `json:"occurred_at"`
	OccurredAt_2       time.Time `json:"occurred_at_2"`
	RefreshWorkspaceID string    `json:"refresh_workspace_id"`
}

func (q *Queries) RefreshDailyStats(ctx context.Context, arg RefreshDailyStatsParams) error {
	_, err := q.exec(ctx, q.refreshDailyStatsStmt, refreshDailyStats, arg.OccurredAt, arg.OccurredAt_2, arg.RefreshWorkspaceID)
	return err
}
