// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.activateTwoFactorStmt, err = db.PrepareContext(ctx, activateTwoFactor); err != nil {
		return nil, fmt.Errorf("error preparing query ActivateTwoFactor: %w", err)
	}
	if q.addInviteRoleStmt, err = db.PrepareContext(ctx, addInviteRole); err != nil {
		return nil, fmt.Errorf("error preparing query AddInviteRole: %w", err)
	}
	if q.addRoleMemberStmt, err = db.PrepareContext(ctx, addRoleMember); err != nil {
		return nil, fmt.Errorf("error preparing query AddRoleMember: %w", err)
	}
	if q.addWorkspaceMemberStmt, err = db.PrepareContext(ctx, addWorkspaceMember); err != nil {
		return nil, fmt.Errorf("error preparing query AddWorkspaceMember: %w", err)
	}
	if q.checkAccessStmt, err = db.PrepareContext(ctx, checkAccess); err != nil {
		return nil, fmt.Errorf("error preparing query CheckAccess: %w", err)
	}
	if q.clearRolePermissionsStmt, err = db.PrepareContext(ctx, clearRolePermissions); err != nil {
		return nil, fmt.Errorf("error preparing query ClearRolePermissions: %w", err)
	}
	if q.countIdentitiesStmt, err = db.PrepareContext(ctx, countIdentities); err != nil {
		return nil, fmt.Errorf("error preparing query CountIdentities: %w", err)
	}
	if q.createAccountStmt, err = db.PrepareContext(ctx, createAccount); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccount: %w", err)
	}
	if q.createAuditEventStmt, err = db.PrepareContext(ctx, createAuditEvent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAuditEvent: %w", err)
	}
	if q.createInviteStmt, err = db.PrepareContext(ctx, createInvite); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInvite: %w", err)
	}
	if q.createInviteAcceptanceStmt, err = db.PrepareContext(ctx, createInviteAcceptance); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInviteAcceptance: %w", err)
	}
	if q.createRoleStmt, err = db.PrepareContext(ctx, createRole); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRole: %w", err)
	}
	if q.createSessionStmt, err = db.PrepareContext(ctx, createSession); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSession: %w", err)
	}
	if q.createTwoFactorChallengeStmt, err = db.PrepareContext(ctx, createTwoFactorChallenge); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTwoFactorChallenge: %w", err)
	}
	if q.createWorkspaceStmt, err = db.PrepareContext(ctx, createWorkspace); err != nil {
		return nil, fmt.Errorf("error preparing query CreateWorkspace: %w", err)
	}
	if q.deleteIdentityStmt, err = db.PrepareContext(ctx, deleteIdentity); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteIdentity: %w", err)
	}
	if q.deleteRoleStmt, err = db.PrepareContext(ctx, deleteRole); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRole: %w", err)
	}
	if q.deleteRolePermissionStmt, err = db.PrepareContext(ctx, deleteRolePermission); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRolePermission: %w", err)
	}
	if q.deleteTwoFactorStmt, err = db.PrepareContext(ctx, deleteTwoFactor); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTwoFactor: %w", err)
	}
	if q.deleteTwoFactorChallengeStmt, err = db.PrepareContext(ctx, deleteTwoFactorChallenge); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTwoFactorChallenge: %w", err)
	}
	if q.findAccountByIdentityStmt, err = db.PrepareContext(ctx, findAccountByIdentity); err != nil {
		return nil, fmt.Errorf("error preparing query FindAccountByIdentity: %w", err)
	}
	if q.getAccountStmt, err = db.PrepareContext(ctx, getAccount); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccount: %w", err)
	}
	if q.getAccountPositionStmt, err = db.PrepareContext(ctx, getAccountPosition); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountPosition: %w", err)
	}
	if q.getActiveSessionByHashStmt, err = db.PrepareContext(ctx, getActiveSessionByHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetActiveSessionByHash: %w", err)
	}
	if q.getInviteByHashForUpdateStmt, err = db.PrepareContext(ctx, getInviteByHashForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetInviteByHashForUpdate: %w", err)
	}
	if q.getMethodStmt, err = db.PrepareContext(ctx, getMethod); err != nil {
		return nil, fmt.Errorf("error preparing query GetMethod: %w", err)
	}
	if q.getRoleStmt, err = db.PrepareContext(ctx, getRole); err != nil {
		return nil, fmt.Errorf("error preparing query GetRole: %w", err)
	}
	if q.getTwoFactorStmt, err = db.PrepareContext(ctx, getTwoFactor); err != nil {
		return nil, fmt.Errorf("error preparing query GetTwoFactor: %w", err)
	}
	if q.getTwoFactorChallengeForUpdateStmt, err = db.PrepareContext(ctx, getTwoFactorChallengeForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetTwoFactorChallengeForUpdate: %w", err)
	}
	if q.getTwoFactorChallengeWithFactorForUpdateStmt, err = db.PrepareContext(ctx, getTwoFactorChallengeWithFactorForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetTwoFactorChallengeWithFactorForUpdate: %w", err)
	}
	if q.getTwoFactorForUpdateStmt, err = db.PrepareContext(ctx, getTwoFactorForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetTwoFactorForUpdate: %w", err)
	}
	if q.getWorkspaceStmt, err = db.PrepareContext(ctx, getWorkspace); err != nil {
		return nil, fmt.Errorf("error preparing query GetWorkspace: %w", err)
	}
	if q.hasActiveTwoFactorStmt, err = db.PrepareContext(ctx, hasActiveTwoFactor); err != nil {
		return nil, fmt.Errorf("error preparing query HasActiveTwoFactor: %w", err)
	}
	if q.incrementInviteUseStmt, err = db.PrepareContext(ctx, incrementInviteUse); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementInviteUse: %w", err)
	}
	if q.isActiveWorkspaceMemberStmt, err = db.PrepareContext(ctx, isActiveWorkspaceMember); err != nil {
		return nil, fmt.Errorf("error preparing query IsActiveWorkspaceMember: %w", err)
	}
	if q.listAccessCatalogStmt, err = db.PrepareContext(ctx, listAccessCatalog); err != nil {
		return nil, fmt.Errorf("error preparing query ListAccessCatalog: %w", err)
	}
	if q.listAuditEventsStmt, err = db.PrepareContext(ctx, listAuditEvents); err != nil {
		return nil, fmt.Errorf("error preparing query ListAuditEvents: %w", err)
	}
	if q.listAuditEventsFilteredStmt, err = db.PrepareContext(ctx, listAuditEventsFiltered); err != nil {
		return nil, fmt.Errorf("error preparing query ListAuditEventsFiltered: %w", err)
	}
	if q.listAuthorizedMethodsStmt, err = db.PrepareContext(ctx, listAuthorizedMethods); err != nil {
		return nil, fmt.Errorf("error preparing query ListAuthorizedMethods: %w", err)
	}
	if q.listIdentitiesStmt, err = db.PrepareContext(ctx, listIdentities); err != nil {
		return nil, fmt.Errorf("error preparing query ListIdentities: %w", err)
	}
	if q.listInviteRolesStmt, err = db.PrepareContext(ctx, listInviteRoles); err != nil {
		return nil, fmt.Errorf("error preparing query ListInviteRoles: %w", err)
	}
	if q.listInvitesStmt, err = db.PrepareContext(ctx, listInvites); err != nil {
		return nil, fmt.Errorf("error preparing query ListInvites: %w", err)
	}
	if q.listMethodGroupsStmt, err = db.PrepareContext(ctx, listMethodGroups); err != nil {
		return nil, fmt.Errorf("error preparing query ListMethodGroups: %w", err)
	}
	if q.listMethodsStmt, err = db.PrepareContext(ctx, listMethods); err != nil {
		return nil, fmt.Errorf("error preparing query ListMethods: %w", err)
	}
	if q.listRolePermissionsStmt, err = db.PrepareContext(ctx, listRolePermissions); err != nil {
		return nil, fmt.Errorf("error preparing query ListRolePermissions: %w", err)
	}
	if q.listRolesStmt, err = db.PrepareContext(ctx, listRoles); err != nil {
		return nil, fmt.Errorf("error preparing query ListRoles: %w", err)
	}
	if q.listSessionsStmt, err = db.PrepareContext(ctx, listSessions); err != nil {
		return nil, fmt.Errorf("error preparing query ListSessions: %w", err)
	}
	if q.listWorkspaceMembersStmt, err = db.PrepareContext(ctx, listWorkspaceMembers); err != nil {
		return nil, fmt.Errorf("error preparing query ListWorkspaceMembers: %w", err)
	}
	if q.listWorkspacesForAccountStmt, err = db.PrepareContext(ctx, listWorkspacesForAccount); err != nil {
		return nil, fmt.Errorf("error preparing query ListWorkspacesForAccount: %w", err)
	}
	if q.lockMethodRegistryStmt, err = db.PrepareContext(ctx, lockMethodRegistry); err != nil {
		return nil, fmt.Errorf("error preparing query LockMethodRegistry: %w", err)
	}
	if q.lockWorkspaceAuthorizationStmt, err = db.PrepareContext(ctx, lockWorkspaceAuthorization); err != nil {
		return nil, fmt.Errorf("error preparing query LockWorkspaceAuthorization: %w", err)
	}
	if q.removeRoleMemberStmt, err = db.PrepareContext(ctx, removeRoleMember); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveRoleMember: %w", err)
	}
	if q.removeWorkspaceMemberStmt, err = db.PrepareContext(ctx, removeWorkspaceMember); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveWorkspaceMember: %w", err)
	}
	if q.removeWorkspaceMemberRolesStmt, err = db.PrepareContext(ctx, removeWorkspaceMemberRoles); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveWorkspaceMemberRoles: %w", err)
	}
	if q.revokeAllSessionsStmt, err = db.PrepareContext(ctx, revokeAllSessions); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeAllSessions: %w", err)
	}
	if q.revokeInviteStmt, err = db.PrepareContext(ctx, revokeInvite); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeInvite: %w", err)
	}
	if q.revokeInviteAsActiveMemberStmt, err = db.PrepareContext(ctx, revokeInviteAsActiveMember); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeInviteAsActiveMember: %w", err)
	}
	if q.revokeSessionStmt, err = db.PrepareContext(ctx, revokeSession); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeSession: %w", err)
	}
	if q.setRolePermissionStmt, err = db.PrepareContext(ctx, setRolePermission); err != nil {
		return nil, fmt.Errorf("error preparing query SetRolePermission: %w", err)
	}
	if q.touchSessionStmt, err = db.PrepareContext(ctx, touchSession); err != nil {
		return nil, fmt.Errorf("error preparing query TouchSession: %w", err)
	}
	if q.updatePendingTwoFactorBackupHashesStmt, err = db.PrepareContext(ctx, updatePendingTwoFactorBackupHashes); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePendingTwoFactorBackupHashes: %w", err)
	}
	if q.updateRoleStmt, err = db.PrepareContext(ctx, updateRole); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRole: %w", err)
	}
	if q.updateTwoFactorBackupHashesStmt, err = db.PrepareContext(ctx, updateTwoFactorBackupHashes); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTwoFactorBackupHashes: %w", err)
	}
	if q.updateWorkspaceStmt, err = db.PrepareContext(ctx, updateWorkspace); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWorkspace: %w", err)
	}
	if q.updateWorkspaceAsActiveMemberStmt, err = db.PrepareContext(ctx, updateWorkspaceAsActiveMember); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWorkspaceAsActiveMember: %w", err)
	}
	if q.upsertIdentityStmt, err = db.PrepareContext(ctx, upsertIdentity); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertIdentity: %w", err)
	}
	if q.upsertMethodStmt, err = db.PrepareContext(ctx, upsertMethod); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMethod: %w", err)
	}
	if q.upsertMethodGroupStmt, err = db.PrepareContext(ctx, upsertMethodGroup); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertMethodGroup: %w", err)
	}
	if q.upsertTwoFactorStmt, err = db.PrepareContext(ctx, upsertTwoFactor); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertTwoFactor: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.activateTwoFactorStmt != nil {
		if cerr := q.activateTwoFactorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing activateTwoFactorStmt: %w", cerr)
		}
	}
	if q.addInviteRoleStmt != nil {
		if cerr := q.addInviteRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addInviteRoleStmt: %w", cerr)
		}
	}
	if q.addRoleMemberStmt != nil {
		if cerr := q.addRoleMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addRoleMemberStmt: %w", cerr)
		}
	}
	if q.addWorkspaceMemberStmt != nil {
		if cerr := q.addWorkspaceMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addWorkspaceMemberStmt: %w", cerr)
		}
	}
	if q.checkAccessStmt != nil {
		if cerr := q.checkAccessStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkAccessStmt: %w", cerr)
		}
	}
	if q.clearRolePermissionsStmt != nil {
		if cerr := q.clearRolePermissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearRolePermissionsStmt: %w", cerr)
		}
	}
	if q.countIdentitiesStmt != nil {
		if cerr := q.countIdentitiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countIdentitiesStmt: %w", cerr)
		}
	}
	if q.createAccountStmt != nil {
		if cerr := q.createAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountStmt: %w", cerr)
		}
	}
	if q.createAuditEventStmt != nil {
		if cerr := q.createAuditEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAuditEventStmt: %w", cerr)
		}
	}
	if q.createInviteStmt != nil {
		if cerr := q.createInviteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInviteStmt: %w", cerr)
		}
	}
	if q.createInviteAcceptanceStmt != nil {
		if cerr := q.createInviteAcceptanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInviteAcceptanceStmt: %w", cerr)
		}
	}
	if q.createRoleStmt != nil {
		if cerr := q.createRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRoleStmt: %w", cerr)
		}
	}
	if q.createSessionStmt != nil {
		if cerr := q.createSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSessionStmt: %w", cerr)
		}
	}
	if q.createTwoFactorChallengeStmt != nil {
		if cerr := q.createTwoFactorChallengeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTwoFactorChallengeStmt: %w", cerr)
		}
	}
	if q.createWorkspaceStmt != nil {
		if cerr := q.createWorkspaceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createWorkspaceStmt: %w", cerr)
		}
	}
	if q.deleteIdentityStmt != nil {
		if cerr := q.deleteIdentityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteIdentityStmt: %w", cerr)
		}
	}
	if q.deleteRoleStmt != nil {
		if cerr := q.deleteRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRoleStmt: %w", cerr)
		}
	}
	if q.deleteRolePermissionStmt != nil {
		if cerr := q.deleteRolePermissionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRolePermissionStmt: %w", cerr)
		}
	}
	if q.deleteTwoFactorStmt != nil {
		if cerr := q.deleteTwoFactorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTwoFactorStmt: %w", cerr)
		}
	}
	if q.deleteTwoFactorChallengeStmt != nil {
		if cerr := q.deleteTwoFactorChallengeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTwoFactorChallengeStmt: %w", cerr)
		}
	}
	if q.findAccountByIdentityStmt != nil {
		if cerr := q.findAccountByIdentityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing findAccountByIdentityStmt: %w", cerr)
		}
	}
	if q.getAccountStmt != nil {
		if cerr := q.getAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountStmt: %w", cerr)
		}
	}
	if q.getAccountPositionStmt != nil {
		if cerr := q.getAccountPositionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountPositionStmt: %w", cerr)
		}
	}
	if q.getActiveSessionByHashStmt != nil {
		if cerr := q.getActiveSessionByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getActiveSessionByHashStmt: %w", cerr)
		}
	}
	if q.getInviteByHashForUpdateStmt != nil {
		if cerr := q.getInviteByHashForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInviteByHashForUpdateStmt: %w", cerr)
		}
	}
	if q.getMethodStmt != nil {
		if cerr := q.getMethodStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMethodStmt: %w", cerr)
		}
	}
	if q.getRoleStmt != nil {
		if cerr := q.getRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRoleStmt: %w", cerr)
		}
	}
	if q.getTwoFactorStmt != nil {
		if cerr := q.getTwoFactorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTwoFactorStmt: %w", cerr)
		}
	}
	if q.getTwoFactorChallengeForUpdateStmt != nil {
		if cerr := q.getTwoFactorChallengeForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTwoFactorChallengeForUpdateStmt: %w", cerr)
		}
	}
	if q.getTwoFactorChallengeWithFactorForUpdateStmt != nil {
		if cerr := q.getTwoFactorChallengeWithFactorForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTwoFactorChallengeWithFactorForUpdateStmt: %w", cerr)
		}
	}
	if q.getTwoFactorForUpdateStmt != nil {
		if cerr := q.getTwoFactorForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTwoFactorForUpdateStmt: %w", cerr)
		}
	}
	if q.getWorkspaceStmt != nil {
		if cerr := q.getWorkspaceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWorkspaceStmt: %w", cerr)
		}
	}
	if q.hasActiveTwoFactorStmt != nil {
		if cerr := q.hasActiveTwoFactorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing hasActiveTwoFactorStmt: %w", cerr)
		}
	}
	if q.incrementInviteUseStmt != nil {
		if cerr := q.incrementInviteUseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementInviteUseStmt: %w", cerr)
		}
	}
	if q.isActiveWorkspaceMemberStmt != nil {
		if cerr := q.isActiveWorkspaceMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isActiveWorkspaceMemberStmt: %w", cerr)
		}
	}
	if q.listAccessCatalogStmt != nil {
		if cerr := q.listAccessCatalogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAccessCatalogStmt: %w", cerr)
		}
	}
	if q.listAuditEventsStmt != nil {
		if cerr := q.listAuditEventsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAuditEventsStmt: %w", cerr)
		}
	}
	if q.listAuditEventsFilteredStmt != nil {
		if cerr := q.listAuditEventsFilteredStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAuditEventsFilteredStmt: %w", cerr)
		}
	}
	if q.listAuthorizedMethodsStmt != nil {
		if cerr := q.listAuthorizedMethodsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAuthorizedMethodsStmt: %w", cerr)
		}
	}
	if q.listIdentitiesStmt != nil {
		if cerr := q.listIdentitiesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listIdentitiesStmt: %w", cerr)
		}
	}
	if q.listInviteRolesStmt != nil {
		if cerr := q.listInviteRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listInviteRolesStmt: %w", cerr)
		}
	}
	if q.listInvitesStmt != nil {
		if cerr := q.listInvitesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listInvitesStmt: %w", cerr)
		}
	}
	if q.listMethodGroupsStmt != nil {
		if cerr := q.listMethodGroupsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMethodGroupsStmt: %w", cerr)
		}
	}
	if q.listMethodsStmt != nil {
		if cerr := q.listMethodsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listMethodsStmt: %w", cerr)
		}
	}
	if q.listRolePermissionsStmt != nil {
		if cerr := q.listRolePermissionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRolePermissionsStmt: %w", cerr)
		}
	}
	if q.listRolesStmt != nil {
		if cerr := q.listRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRolesStmt: %w", cerr)
		}
	}
	if q.listSessionsStmt != nil {
		if cerr := q.listSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listSessionsStmt: %w", cerr)
		}
	}
	if q.listWorkspaceMembersStmt != nil {
		if cerr := q.listWorkspaceMembersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listWorkspaceMembersStmt: %w", cerr)
		}
	}
	if q.listWorkspacesForAccountStmt != nil {
		if cerr := q.listWorkspacesForAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listWorkspacesForAccountStmt: %w", cerr)
		}
	}
	if q.lockMethodRegistryStmt != nil {
		if cerr := q.lockMethodRegistryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing lockMethodRegistryStmt: %w", cerr)
		}
	}
	if q.lockWorkspaceAuthorizationStmt != nil {
		if cerr := q.lockWorkspaceAuthorizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing lockWorkspaceAuthorizationStmt: %w", cerr)
		}
	}
	if q.removeRoleMemberStmt != nil {
		if cerr := q.removeRoleMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeRoleMemberStmt: %w", cerr)
		}
	}
	if q.removeWorkspaceMemberStmt != nil {
		if cerr := q.removeWorkspaceMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeWorkspaceMemberStmt: %w", cerr)
		}
	}
	if q.removeWorkspaceMemberRolesStmt != nil {
		if cerr := q.removeWorkspaceMemberRolesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeWorkspaceMemberRolesStmt: %w", cerr)
		}
	}
	if q.revokeAllSessionsStmt != nil {
		if cerr := q.revokeAllSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeAllSessionsStmt: %w", cerr)
		}
	}
	if q.revokeInviteStmt != nil {
		if cerr := q.revokeInviteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeInviteStmt: %w", cerr)
		}
	}
	if q.revokeInviteAsActiveMemberStmt != nil {
		if cerr := q.revokeInviteAsActiveMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeInviteAsActiveMemberStmt: %w", cerr)
		}
	}
	if q.revokeSessionStmt != nil {
		if cerr := q.revokeSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeSessionStmt: %w", cerr)
		}
	}
	if q.setRolePermissionStmt != nil {
		if cerr := q.setRolePermissionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setRolePermissionStmt: %w", cerr)
		}
	}
	if q.touchSessionStmt != nil {
		if cerr := q.touchSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing touchSessionStmt: %w", cerr)
		}
	}
	if q.updatePendingTwoFactorBackupHashesStmt != nil {
		if cerr := q.updatePendingTwoFactorBackupHashesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePendingTwoFactorBackupHashesStmt: %w", cerr)
		}
	}
	if q.updateRoleStmt != nil {
		if cerr := q.updateRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRoleStmt: %w", cerr)
		}
	}
	if q.updateTwoFactorBackupHashesStmt != nil {
		if cerr := q.updateTwoFactorBackupHashesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTwoFactorBackupHashesStmt: %w", cerr)
		}
	}
	if q.updateWorkspaceStmt != nil {
		if cerr := q.updateWorkspaceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWorkspaceStmt: %w", cerr)
		}
	}
	if q.updateWorkspaceAsActiveMemberStmt != nil {
		if cerr := q.updateWorkspaceAsActiveMemberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWorkspaceAsActiveMemberStmt: %w", cerr)
		}
	}
	if q.upsertIdentityStmt != nil {
		if cerr := q.upsertIdentityStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertIdentityStmt: %w", cerr)
		}
	}
	if q.upsertMethodStmt != nil {
		if cerr := q.upsertMethodStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMethodStmt: %w", cerr)
		}
	}
	if q.upsertMethodGroupStmt != nil {
		if cerr := q.upsertMethodGroupStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertMethodGroupStmt: %w", cerr)
		}
	}
	if q.upsertTwoFactorStmt != nil {
		if cerr := q.upsertTwoFactorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertTwoFactorStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                           DBTX
	tx                                           *sql.Tx
	activateTwoFactorStmt                        *sql.Stmt
	addInviteRoleStmt                            *sql.Stmt
	addRoleMemberStmt                            *sql.Stmt
	addWorkspaceMemberStmt                       *sql.Stmt
	checkAccessStmt                              *sql.Stmt
	clearRolePermissionsStmt                     *sql.Stmt
	countIdentitiesStmt                          *sql.Stmt
	createAccountStmt                            *sql.Stmt
	createAuditEventStmt                         *sql.Stmt
	createInviteStmt                             *sql.Stmt
	createInviteAcceptanceStmt                   *sql.Stmt
	createRoleStmt                               *sql.Stmt
	createSessionStmt                            *sql.Stmt
	createTwoFactorChallengeStmt                 *sql.Stmt
	createWorkspaceStmt                          *sql.Stmt
	deleteIdentityStmt                           *sql.Stmt
	deleteRoleStmt                               *sql.Stmt
	deleteRolePermissionStmt                     *sql.Stmt
	deleteTwoFactorStmt                          *sql.Stmt
	deleteTwoFactorChallengeStmt                 *sql.Stmt
	findAccountByIdentityStmt                    *sql.Stmt
	getAccountStmt                               *sql.Stmt
	getAccountPositionStmt                       *sql.Stmt
	getActiveSessionByHashStmt                   *sql.Stmt
	getInviteByHashForUpdateStmt                 *sql.Stmt
	getMethodStmt                                *sql.Stmt
	getRoleStmt                                  *sql.Stmt
	getTwoFactorStmt                             *sql.Stmt
	getTwoFactorChallengeForUpdateStmt           *sql.Stmt
	getTwoFactorChallengeWithFactorForUpdateStmt *sql.Stmt
	getTwoFactorForUpdateStmt                    *sql.Stmt
	getWorkspaceStmt                             *sql.Stmt
	hasActiveTwoFactorStmt                       *sql.Stmt
	incrementInviteUseStmt                       *sql.Stmt
	isActiveWorkspaceMemberStmt                  *sql.Stmt
	listAccessCatalogStmt                        *sql.Stmt
	listAuditEventsStmt                          *sql.Stmt
	listAuditEventsFilteredStmt                  *sql.Stmt
	listAuthorizedMethodsStmt                    *sql.Stmt
	listIdentitiesStmt                           *sql.Stmt
	listInviteRolesStmt                          *sql.Stmt
	listInvitesStmt                              *sql.Stmt
	listMethodGroupsStmt                         *sql.Stmt
	listMethodsStmt                              *sql.Stmt
	listRolePermissionsStmt                      *sql.Stmt
	listRolesStmt                                *sql.Stmt
	listSessionsStmt                             *sql.Stmt
	listWorkspaceMembersStmt                     *sql.Stmt
	listWorkspacesForAccountStmt                 *sql.Stmt
	lockMethodRegistryStmt                       *sql.Stmt
	lockWorkspaceAuthorizationStmt               *sql.Stmt
	removeRoleMemberStmt                         *sql.Stmt
	removeWorkspaceMemberStmt                    *sql.Stmt
	removeWorkspaceMemberRolesStmt               *sql.Stmt
	revokeAllSessionsStmt                        *sql.Stmt
	revokeInviteStmt                             *sql.Stmt
	revokeInviteAsActiveMemberStmt               *sql.Stmt
	revokeSessionStmt                            *sql.Stmt
	setRolePermissionStmt                        *sql.Stmt
	touchSessionStmt                             *sql.Stmt
	updatePendingTwoFactorBackupHashesStmt       *sql.Stmt
	updateRoleStmt                               *sql.Stmt
	updateTwoFactorBackupHashesStmt              *sql.Stmt
	updateWorkspaceStmt                          *sql.Stmt
	updateWorkspaceAsActiveMemberStmt            *sql.Stmt
	upsertIdentityStmt                           *sql.Stmt
	upsertMethodStmt                             *sql.Stmt
	upsertMethodGroupStmt                        *sql.Stmt
	upsertTwoFactorStmt                          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                 tx,
		tx:                                 tx,
		activateTwoFactorStmt:              q.activateTwoFactorStmt,
		addInviteRoleStmt:                  q.addInviteRoleStmt,
		addRoleMemberStmt:                  q.addRoleMemberStmt,
		addWorkspaceMemberStmt:             q.addWorkspaceMemberStmt,
		checkAccessStmt:                    q.checkAccessStmt,
		clearRolePermissionsStmt:           q.clearRolePermissionsStmt,
		countIdentitiesStmt:                q.countIdentitiesStmt,
		createAccountStmt:                  q.createAccountStmt,
		createAuditEventStmt:               q.createAuditEventStmt,
		createInviteStmt:                   q.createInviteStmt,
		createInviteAcceptanceStmt:         q.createInviteAcceptanceStmt,
		createRoleStmt:                     q.createRoleStmt,
		createSessionStmt:                  q.createSessionStmt,
		createTwoFactorChallengeStmt:       q.createTwoFactorChallengeStmt,
		createWorkspaceStmt:                q.createWorkspaceStmt,
		deleteIdentityStmt:                 q.deleteIdentityStmt,
		deleteRoleStmt:                     q.deleteRoleStmt,
		deleteRolePermissionStmt:           q.deleteRolePermissionStmt,
		deleteTwoFactorStmt:                q.deleteTwoFactorStmt,
		deleteTwoFactorChallengeStmt:       q.deleteTwoFactorChallengeStmt,
		findAccountByIdentityStmt:          q.findAccountByIdentityStmt,
		getAccountStmt:                     q.getAccountStmt,
		getAccountPositionStmt:             q.getAccountPositionStmt,
		getActiveSessionByHashStmt:         q.getActiveSessionByHashStmt,
		getInviteByHashForUpdateStmt:       q.getInviteByHashForUpdateStmt,
		getMethodStmt:                      q.getMethodStmt,
		getRoleStmt:                        q.getRoleStmt,
		getTwoFactorStmt:                   q.getTwoFactorStmt,
		getTwoFactorChallengeForUpdateStmt: q.getTwoFactorChallengeForUpdateStmt,
		getTwoFactorChallengeWithFactorForUpdateStmt: q.getTwoFactorChallengeWithFactorForUpdateStmt,
		getTwoFactorForUpdateStmt:                    q.getTwoFactorForUpdateStmt,
		getWorkspaceStmt:                             q.getWorkspaceStmt,
		hasActiveTwoFactorStmt:                       q.hasActiveTwoFactorStmt,
		incrementInviteUseStmt:                       q.incrementInviteUseStmt,
		isActiveWorkspaceMemberStmt:                  q.isActiveWorkspaceMemberStmt,
		listAccessCatalogStmt:                        q.listAccessCatalogStmt,
		listAuditEventsStmt:                          q.listAuditEventsStmt,
		listAuditEventsFilteredStmt:                  q.listAuditEventsFilteredStmt,
		listAuthorizedMethodsStmt:                    q.listAuthorizedMethodsStmt,
		listIdentitiesStmt:                           q.listIdentitiesStmt,
		listInviteRolesStmt:                          q.listInviteRolesStmt,
		listInvitesStmt:                              q.listInvitesStmt,
		listMethodGroupsStmt:                         q.listMethodGroupsStmt,
		listMethodsStmt:                              q.listMethodsStmt,
		listRolePermissionsStmt:                      q.listRolePermissionsStmt,
		listRolesStmt:                                q.listRolesStmt,
		listSessionsStmt:                             q.listSessionsStmt,
		listWorkspaceMembersStmt:                     q.listWorkspaceMembersStmt,
		listWorkspacesForAccountStmt:                 q.listWorkspacesForAccountStmt,
		lockMethodRegistryStmt:                       q.lockMethodRegistryStmt,
		lockWorkspaceAuthorizationStmt:               q.lockWorkspaceAuthorizationStmt,
		removeRoleMemberStmt:                         q.removeRoleMemberStmt,
		removeWorkspaceMemberStmt:                    q.removeWorkspaceMemberStmt,
		removeWorkspaceMemberRolesStmt:               q.removeWorkspaceMemberRolesStmt,
		revokeAllSessionsStmt:                        q.revokeAllSessionsStmt,
		revokeInviteStmt:                             q.revokeInviteStmt,
		revokeInviteAsActiveMemberStmt:               q.revokeInviteAsActiveMemberStmt,
		revokeSessionStmt:                            q.revokeSessionStmt,
		setRolePermissionStmt:                        q.setRolePermissionStmt,
		touchSessionStmt:                             q.touchSessionStmt,
		updatePendingTwoFactorBackupHashesStmt:       q.updatePendingTwoFactorBackupHashesStmt,
		updateRoleStmt:                               q.updateRoleStmt,
		updateTwoFactorBackupHashesStmt:              q.updateTwoFactorBackupHashesStmt,
		updateWorkspaceStmt:                          q.updateWorkspaceStmt,
		updateWorkspaceAsActiveMemberStmt:            q.updateWorkspaceAsActiveMemberStmt,
		upsertIdentityStmt:                           q.upsertIdentityStmt,
		upsertMethodStmt:                             q.upsertMethodStmt,
		upsertMethodGroupStmt:                        q.upsertMethodGroupStmt,
		upsertTwoFactorStmt:                          q.upsertTwoFactorStmt,
	}
}
