// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ControlAccessService struct {
	Service   string    `json:"service"`
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ControlAccount struct {
	ID          string    `json:"id"`
	DisplayName string    `json:"display_name"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ControlAuditEvent struct {
	ID          string                `json:"id"`
	Scope       string                `json:"scope"`
	WorkspaceID sql.NullString        `json:"workspace_id"`
	ActorID     sql.NullString        `json:"actor_id"`
	MethodKey   string                `json:"method_key"`
	TargetType  string                `json:"target_type"`
	TargetID    string                `json:"target_id"`
	BeforeData  pqtype.NullRawMessage `json:"before_data"`
	AfterData   pqtype.NullRawMessage `json:"after_data"`
	Result      string                `json:"result"`
	RequestID   string                `json:"request_id"`
	OccurredAt  time.Time             `json:"occurred_at"`
}

type ControlGlobalRole struct {
	ID          string    `json:"id"`
	Code        string    `json:"code"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Position    int32     `json:"position"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ControlGlobalRoleMember struct {
	RoleID    string    `json:"role_id"`
	AccountID string    `json:"account_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ControlGlobalRolePermission struct {
	RoleID    string    `json:"role_id"`
	MethodKey string    `json:"method_key"`
	CreatedAt time.Time `json:"created_at"`
}

type ControlIdentity struct {
	AccountID       string                `json:"account_id"`
	Provider        string                `json:"provider"`
	ProviderSubject string                `json:"provider_subject"`
	Payload         pqtype.NullRawMessage `json:"payload"`
	CreatedAt       time.Time             `json:"created_at"`
	UpdatedAt       time.Time             `json:"updated_at"`
}

type ControlInvite struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	WorkspaceID sql.NullString `json:"workspace_id"`
	CreatedBy   string         `json:"created_by"`
	TokenHash   string         `json:"token_hash"`
	ExpiresAt   sql.NullTime   `json:"expires_at"`
	AcceptedBy  sql.NullString `json:"accepted_by"`
	AcceptedAt  sql.NullTime   `json:"accepted_at"`
	RevokedAt   sql.NullTime   `json:"revoked_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ControlInviteGlobalRole struct {
	InviteID   string `json:"invite_id"`
	InviteKind string `json:"invite_kind"`
	RoleID     string `json:"role_id"`
}

type ControlInviteWorkspaceRole struct {
	InviteID    string `json:"invite_id"`
	InviteKind  string `json:"invite_kind"`
	WorkspaceID string `json:"workspace_id"`
	RoleID      string `json:"role_id"`
}

type ControlLimitRequest struct {
	ID             string         `json:"id"`
	Kind           string         `json:"kind"`
	AccountID      sql.NullString `json:"account_id"`
	WorkspaceID    sql.NullString `json:"workspace_id"`
	CurrentLimit   int32          `json:"current_limit"`
	RequestedLimit int32          `json:"requested_limit"`
	ApprovedLimit  sql.NullInt32  `json:"approved_limit"`
	Reason         string         `json:"reason"`
	Status         string         `json:"status"`
	RequestedBy    string         `json:"requested_by"`
	ReviewedBy     sql.NullString `json:"reviewed_by"`
	ReviewComment  string         `json:"review_comment"`
	CreatedAt      time.Time      `json:"created_at"`
	ReviewedAt     sql.NullTime   `json:"reviewed_at"`
}

type ControlLocalization struct {
	LocalizationKey string    `json:"localization_key"`
	Locale          string    `json:"locale"`
	Value           string    `json:"value"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type ControlMethod struct {
	MethodKey string         `json:"method_key"`
	Service   string         `json:"service"`
	GroupKey  string         `json:"group_key"`
	Scope     sql.NullString `json:"scope"`
	Position  int32          `json:"position"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type ControlMethodGroup struct {
	Service   string    `json:"service"`
	GroupKey  string    `json:"group_key"`
	Position  int32     `json:"position"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ControlPlatform struct {
	ID             int16     `json:"id"`
	OwnerAccountID string    `json:"owner_account_id"`
	InitializedBy  string    `json:"initialized_by"`
	InitializedAt  time.Time `json:"initialized_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ControlPlatformMember struct {
	AccountID      string         `json:"account_id"`
	Status         string         `json:"status"`
	WorkspaceLimit int32          `json:"workspace_limit"`
	InvitedBy      sql.NullString `json:"invited_by"`
	JoinedAt       time.Time      `json:"joined_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type ControlSession struct {
	ID         string       `json:"id"`
	AccountID  string       `json:"account_id"`
	TokenHash  string       `json:"token_hash"`
	Ip         string       `json:"ip"`
	UserAgent  string       `json:"user_agent"`
	BindToIp   bool         `json:"bind_to_ip"`
	ExpiresAt  time.Time    `json:"expires_at"`
	RevokedAt  sql.NullTime `json:"revoked_at"`
	LastUsedAt time.Time    `json:"last_used_at"`
	CreatedAt  time.Time    `json:"created_at"`
}

type ControlTwoFactor struct {
	AccountID       string          `json:"account_id"`
	Secret          string          `json:"secret"`
	BackupHashes    json.RawMessage `json:"backup_hashes"`
	ActivatedAt     sql.NullTime    `json:"activated_at"`
	LastTotpCounter sql.NullInt64   `json:"last_totp_counter"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type ControlTwoFactorChallenge struct {
	ID               string         `json:"id"`
	AccountID        string         `json:"account_id"`
	InviteID         sql.NullString `json:"invite_id"`
	TokenHash        string         `json:"token_hash"`
	Ip               string         `json:"ip"`
	UserAgent        string         `json:"user_agent"`
	BindToIp         bool           `json:"bind_to_ip"`
	ExpiresAt        time.Time      `json:"expires_at"`
	SessionExpiresAt time.Time      `json:"session_expires_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

type ControlWorkspace struct {
	ID             string    `json:"id"`
	Slug           string    `json:"slug"`
	Title          string    `json:"title"`
	Status         string    `json:"status"`
	CreatedBy      string    `json:"created_by"`
	OwnerAccountID string    `json:"owner_account_id"`
	EmployeeLimit  int32     `json:"employee_limit"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type ControlWorkspaceMember struct {
	WorkspaceID string    `json:"workspace_id"`
	AccountID   string    `json:"account_id"`
	Status      string    `json:"status"`
	JoinedAt    time.Time `json:"joined_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ControlWorkspaceRole struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	Code        string    `json:"code"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Position    int32     `json:"position"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type ControlWorkspaceRoleMember struct {
	RoleID      string    `json:"role_id"`
	WorkspaceID string    `json:"workspace_id"`
	AccountID   string    `json:"account_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type ControlWorkspaceRolePermission struct {
	RoleID      string    `json:"role_id"`
	WorkspaceID string    `json:"workspace_id"`
	MethodKey   string    `json:"method_key"`
	CreatedAt   time.Time `json:"created_at"`
}
