// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const activateTwoFactor = `-- name: ActivateTwoFactor :execrows
UPDATE control_two_factor SET activated_at = now()
WHERE account_id = $1 AND activated_at IS NULL
`

func (q *Queries) ActivateTwoFactor(ctx context.Context, accountID string) (int64, error) {
	result, err := q.exec(ctx, q.activateTwoFactorStmt, activateTwoFactor, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const addInviteRole = `-- name: AddInviteRole :exec
INSERT INTO control_workspace_invite_role (invite_id, role_id) VALUES ($1, $2)
`

type AddInviteRoleParams struct {
	InviteID string `json:"invite_id"`
	RoleID   string `json:"role_id"`
}

func (q *Queries) AddInviteRole(ctx context.Context, arg AddInviteRoleParams) error {
	_, err := q.exec(ctx, q.addInviteRoleStmt, addInviteRole, arg.InviteID, arg.RoleID)
	return err
}

const addRoleMember = `-- name: AddRoleMember :exec
INSERT INTO control_role_member (role_id, account_id)
VALUES ($1, $2)
ON CONFLICT (role_id, account_id) DO NOTHING
`

type AddRoleMemberParams struct {
	RoleID    string `json:"role_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) AddRoleMember(ctx context.Context, arg AddRoleMemberParams) error {
	_, err := q.exec(ctx, q.addRoleMemberStmt, addRoleMember, arg.RoleID, arg.AccountID)
	return err
}

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO control_workspace_member (workspace_id, account_id)
VALUES ($1, $2)
ON CONFLICT (workspace_id, account_id) DO UPDATE SET
    status = 'active',
    updated_at = now()
`

type AddWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.exec(ctx, q.addWorkspaceMemberStmt, addWorkspaceMember, arg.WorkspaceID, arg.AccountID)
	return err
}

const checkAccess = `-- name: CheckAccess :one
SELECT EXISTS(
    SELECT 1
    FROM control_workspace_member m
    JOIN control_method cm ON cm.method_key = $1
    JOIN control_role_member rm ON rm.account_id = m.account_id
    JOIN control_role r ON r.id = rm.role_id
    LEFT JOIN control_role_permission p ON p.role_id = r.id AND p.method_key = cm.method_key
    WHERE m.workspace_id = $2 AND m.account_id = $3 AND m.status = 'active'
      AND r.workspace_id = m.workspace_id AND r.deleted_at IS NULL
      AND (r.is_owner = TRUE OR p.method_key IS NOT NULL)
) AS allowed
`

type CheckAccessParams struct {
	MethodKey   string `json:"method_key"`
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) CheckAccess(ctx context.Context, arg CheckAccessParams) (bool, error) {
	row := q.queryRow(ctx, q.checkAccessStmt, checkAccess, arg.MethodKey, arg.WorkspaceID, arg.AccountID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const clearRolePermissions = `-- name: ClearRolePermissions :execrows
DELETE FROM control_role_permission WHERE role_id = $1
`

func (q *Queries) ClearRolePermissions(ctx context.Context, roleID string) (int64, error) {
	result, err := q.exec(ctx, q.clearRolePermissionsStmt, clearRolePermissions, roleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countIdentities = `-- name: CountIdentities :one
SELECT COUNT(*) AS count FROM control_identity WHERE account_id = $1
`

func (q *Queries) CountIdentities(ctx context.Context, accountID string) (int64, error) {
	row := q.queryRow(ctx, q.countIdentitiesStmt, countIdentities, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO control_account (id, display_name) VALUES ($1, $2)
`

type CreateAccountParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.exec(ctx, q.createAccountStmt, createAccount, arg.ID, arg.DisplayName)
	return err
}

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO control_audit_event (
    id, workspace_id, actor_id, method_key, target_type, target_id,
    before_data, after_data, result, request_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateAuditEventParams struct {
	ID          string                `json:"id"`
	WorkspaceID sql.NullString        `json:"workspace_id"`
	ActorID     sql.NullString        `json:"actor_id"`
	MethodKey   string                `json:"method_key"`
	TargetType  string                `json:"target_type"`
	TargetID    string                `json:"target_id"`
	BeforeData  pqtype.NullRawMessage `json:"before_data"`
	AfterData   pqtype.NullRawMessage `json:"after_data"`
	Result      string                `json:"result"`
	RequestID   string                `json:"request_id"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.exec(ctx, q.createAuditEventStmt, createAuditEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.ActorID,
		arg.MethodKey,
		arg.TargetType,
		arg.TargetID,
		arg.BeforeData,
		arg.AfterData,
		arg.Result,
		arg.RequestID,
	)
	return err
}

const createInvite = `-- name: CreateInvite :exec
INSERT INTO control_workspace_invite (id, workspace_id, created_by, token_hash, max_uses, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateInviteParams struct {
	ID          string        `json:"id"`
	WorkspaceID string        `json:"workspace_id"`
	CreatedBy   string        `json:"created_by"`
	TokenHash   string        `json:"token_hash"`
	MaxUses     sql.NullInt32 `json:"max_uses"`
	ExpiresAt   sql.NullTime  `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) error {
	_, err := q.exec(ctx, q.createInviteStmt, createInvite,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.TokenHash,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	return err
}

const createInviteAcceptance = `-- name: CreateInviteAcceptance :execrows
INSERT INTO control_workspace_invite_acceptance (invite_id, account_id)
VALUES ($1, $2)
ON CONFLICT (invite_id, account_id) DO NOTHING
`

type CreateInviteAcceptanceParams struct {
	InviteID  string `json:"invite_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) CreateInviteAcceptance(ctx context.Context, arg CreateInviteAcceptanceParams) (int64, error) {
	result, err := q.exec(ctx, q.createInviteAcceptanceStmt, createInviteAcceptance, arg.InviteID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createRole = `-- name: CreateRole :exec
INSERT INTO control_role (id, workspace_id, code, title, description, position, is_owner)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateRoleParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Code        string `json:"code"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Position    int32  `json:"position"`
	IsOwner     bool   `json:"is_owner"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.exec(ctx, q.createRoleStmt, createRole,
		arg.ID,
		arg.WorkspaceID,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.IsOwner,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO control_session (id, account_id, token_hash, ip, user_agent, bind_to_ip, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	AccountID string    `json:"account_id"`
	TokenHash string    `json:"token_hash"`
	Ip        string    `json:"ip"`
	UserAgent string    `json:"user_agent"`
	BindToIp  bool      `json:"bind_to_ip"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.exec(ctx, q.createSessionStmt, createSession,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.Ip,
		arg.UserAgent,
		arg.BindToIp,
		arg.ExpiresAt,
	)
	return err
}

const createTwoFactorChallenge = `-- name: CreateTwoFactorChallenge :exec
INSERT INTO control_two_factor_challenge (
    id,
    account_id,
    token_hash,
    ip,
    user_agent,
    bind_to_ip,
    expires_at,
    session_expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateTwoFactorChallengeParams struct {
	ID               string    `json:"id"`
	AccountID        string    `json:"account_id"`
	TokenHash        string    `json:"token_hash"`
	Ip               string    `json:"ip"`
	UserAgent        string    `json:"user_agent"`
	BindToIp         bool      `json:"bind_to_ip"`
	ExpiresAt        time.Time `json:"expires_at"`
	SessionExpiresAt time.Time `json:"session_expires_at"`
}

func (q *Queries) CreateTwoFactorChallenge(ctx context.Context, arg CreateTwoFactorChallengeParams) error {
	_, err := q.exec(ctx, q.createTwoFactorChallengeStmt, createTwoFactorChallenge,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.Ip,
		arg.UserAgent,
		arg.BindToIp,
		arg.ExpiresAt,
		arg.SessionExpiresAt,
	)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO control_workspace (id, slug, title, created_by) VALUES ($1, $2, $3, $4)
`

type CreateWorkspaceParams struct {
	ID        string `json:"id"`
	Slug      string `json:"slug"`
	Title     string `json:"title"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.exec(ctx, q.createWorkspaceStmt, createWorkspace,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.CreatedBy,
	)
	return err
}

const deleteIdentity = `-- name: DeleteIdentity :execrows
DELETE FROM control_identity WHERE account_id = $1 AND provider = $2
`

type DeleteIdentityParams struct {
	AccountID string `json:"account_id"`
	Provider  string `json:"provider"`
}

func (q *Queries) DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteIdentityStmt, deleteIdentity, arg.AccountID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRole = `-- name: DeleteRole :execrows
UPDATE control_role SET deleted_at = now()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL AND is_owner = FALSE
`

type DeleteRoleParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteRoleStmt, deleteRole, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRolePermission = `-- name: DeleteRolePermission :execrows
DELETE FROM control_role_permission WHERE role_id = $1 AND method_key = $2
`

type DeleteRolePermissionParams struct {
	RoleID    string `json:"role_id"`
	MethodKey string `json:"method_key"`
}

func (q *Queries) DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteRolePermissionStmt, deleteRolePermission, arg.RoleID, arg.MethodKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTwoFactor = `-- name: DeleteTwoFactor :execrows
DELETE FROM control_two_factor WHERE account_id = $1
`

func (q *Queries) DeleteTwoFactor(ctx context.Context, accountID string) (int64, error) {
	result, err := q.exec(ctx, q.deleteTwoFactorStmt, deleteTwoFactor, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTwoFactorChallenge = `-- name: DeleteTwoFactorChallenge :execrows
DELETE FROM control_two_factor_challenge WHERE id = $1
`

func (q *Queries) DeleteTwoFactorChallenge(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteTwoFactorChallengeStmt, deleteTwoFactorChallenge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findAccountByIdentity = `-- name: FindAccountByIdentity :one
SELECT a.id, a.display_name, a.status, a.created_at, a.updated_at
FROM control_identity i
JOIN control_account a ON a.id = i.account_id
WHERE i.provider = $1 AND i.provider_subject = $2
LIMIT 1
`

type FindAccountByIdentityParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) FindAccountByIdentity(ctx context.Context, arg FindAccountByIdentityParams) (ControlAccount, error) {
	row := q.queryRow(ctx, q.findAccountByIdentityStmt, findAccountByIdentity, arg.Provider, arg.ProviderSubject)
	var i ControlAccount
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, display_name, status, created_at, updated_at
FROM control_account WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (ControlAccount, error) {
	row := q.queryRow(ctx, q.getAccountStmt, getAccount, id)
	var i ControlAccount
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountPosition = `-- name: GetAccountPosition :one
SELECT COALESCE((
    SELECT r.position
    FROM control_workspace_member m
    JOIN control_role_member rm ON rm.account_id = m.account_id
    JOIN control_role r ON r.id = rm.role_id
    WHERE m.workspace_id = $1 AND m.account_id = $2 AND m.status = 'active'
      AND r.workspace_id = m.workspace_id AND r.deleted_at IS NULL
    ORDER BY r.position
    LIMIT 1
), 2147483647) AS position
`

type GetAccountPositionParams struct {
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) GetAccountPosition(ctx context.Context, arg GetAccountPositionParams) (interface{}, error) {
	row := q.queryRow(ctx, q.getAccountPositionStmt, getAccountPosition, arg.WorkspaceID, arg.AccountID)
	var position interface{}
	err := row.Scan(&position)
	return position, err
}

const getActiveSessionByHash = `-- name: GetActiveSessionByHash :one
SELECT id, account_id, token_hash, ip, user_agent, bind_to_ip, expires_at, revoked_at, last_used_at, created_at
FROM control_session
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetActiveSessionByHash(ctx context.Context, tokenHash string) (ControlSession, error) {
	row := q.queryRow(ctx, q.getActiveSessionByHashStmt, getActiveSessionByHash, tokenHash)
	var i ControlSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Ip,
		&i.UserAgent,
		&i.BindToIp,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByHashForUpdate = `-- name: GetInviteByHashForUpdate :one
SELECT id, workspace_id, created_by, token_hash, max_uses, used_count, expires_at, revoked_at, created_at
FROM control_workspace_invite
WHERE token_hash = $1
LIMIT 1 FOR UPDATE
`

func (q *Queries) GetInviteByHashForUpdate(ctx context.Context, tokenHash string) (ControlWorkspaceInvite, error) {
	row := q.queryRow(ctx, q.getInviteByHashForUpdateStmt, getInviteByHashForUpdate, tokenHash)
	var i ControlWorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.TokenHash,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMethod = `-- name: GetMethod :one
SELECT method_key, service, group_key, position, created_at, updated_at
FROM control_method WHERE method_key = $1 LIMIT 1
`

func (q *Queries) GetMethod(ctx context.Context, methodKey string) (ControlMethod, error) {
	row := q.queryRow(ctx, q.getMethodStmt, getMethod, methodKey)
	var i ControlMethod
	err := row.Scan(
		&i.MethodKey,
		&i.Service,
		&i.GroupKey,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, workspace_id, code, title, description, position, is_owner, deleted_at, created_at, updated_at
FROM control_role WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL LIMIT 1
`

type GetRoleParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (ControlRole, error) {
	row := q.queryRow(ctx, q.getRoleStmt, getRole, arg.ID, arg.WorkspaceID)
	var i ControlRole
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.IsOwner,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTwoFactor = `-- name: GetTwoFactor :one
SELECT account_id, secret, backup_hashes, activated_at, created_at, updated_at
FROM control_two_factor WHERE account_id = $1 LIMIT 1
`

func (q *Queries) GetTwoFactor(ctx context.Context, accountID string) (ControlTwoFactor, error) {
	row := q.queryRow(ctx, q.getTwoFactorStmt, getTwoFactor, accountID)
	var i ControlTwoFactor
	err := row.Scan(
		&i.AccountID,
		&i.Secret,
		&i.BackupHashes,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTwoFactorChallengeForUpdate = `-- name: GetTwoFactorChallengeForUpdate :one
SELECT id, account_id, token_hash, ip, user_agent, bind_to_ip, expires_at,
       session_expires_at, created_at
FROM control_two_factor_challenge
WHERE token_hash = $1 AND expires_at > now()
LIMIT 1 FOR UPDATE
`

func (q *Queries) GetTwoFactorChallengeForUpdate(ctx context.Context, tokenHash string) (ControlTwoFactorChallenge, error) {
	row := q.queryRow(ctx, q.getTwoFactorChallengeForUpdateStmt, getTwoFactorChallengeForUpdate, tokenHash)
	var i ControlTwoFactorChallenge
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.Ip,
		&i.UserAgent,
		&i.BindToIp,
		&i.ExpiresAt,
		&i.SessionExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTwoFactorChallengeWithFactorForUpdate = `-- name: GetTwoFactorChallengeWithFactorForUpdate :one
SELECT c.id AS challenge_id, c.account_id, c.ip, c.user_agent, c.bind_to_ip,
       c.expires_at, c.session_expires_at,
       f.secret, f.backup_hashes, f.activated_at
FROM control_two_factor_challenge c
JOIN control_two_factor f ON f.account_id = c.account_id
WHERE c.token_hash = $1 AND c.expires_at > now()
LIMIT 1 FOR UPDATE
`

type GetTwoFactorChallengeWithFactorForUpdateRow struct {
	ChallengeID      string          `json:"challenge_id"`
	AccountID        string          `json:"account_id"`
	Ip               string          `json:"ip"`
	UserAgent        string          `json:"user_agent"`
	BindToIp         bool            `json:"bind_to_ip"`
	ExpiresAt        time.Time       `json:"expires_at"`
	SessionExpiresAt time.Time       `json:"session_expires_at"`
	Secret           string          `json:"secret"`
	BackupHashes     json.RawMessage `json:"backup_hashes"`
	ActivatedAt      sql.NullTime    `json:"activated_at"`
}

func (q *Queries) GetTwoFactorChallengeWithFactorForUpdate(ctx context.Context, tokenHash string) (GetTwoFactorChallengeWithFactorForUpdateRow, error) {
	row := q.queryRow(ctx, q.getTwoFactorChallengeWithFactorForUpdateStmt, getTwoFactorChallengeWithFactorForUpdate, tokenHash)
	var i GetTwoFactorChallengeWithFactorForUpdateRow
	err := row.Scan(
		&i.ChallengeID,
		&i.AccountID,
		&i.Ip,
		&i.UserAgent,
		&i.BindToIp,
		&i.ExpiresAt,
		&i.SessionExpiresAt,
		&i.Secret,
		&i.BackupHashes,
		&i.ActivatedAt,
	)
	return i, err
}

const getTwoFactorForUpdate = `-- name: GetTwoFactorForUpdate :one
SELECT account_id, secret, backup_hashes, activated_at, created_at, updated_at
FROM control_two_factor WHERE account_id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetTwoFactorForUpdate(ctx context.Context, accountID string) (ControlTwoFactor, error) {
	row := q.queryRow(ctx, q.getTwoFactorForUpdateStmt, getTwoFactorForUpdate, accountID)
	var i ControlTwoFactor
	err := row.Scan(
		&i.AccountID,
		&i.Secret,
		&i.BackupHashes,
		&i.ActivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, slug, title, status, created_by, created_at, updated_at
FROM control_workspace WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (ControlWorkspace, error) {
	row := q.queryRow(ctx, q.getWorkspaceStmt, getWorkspace, id)
	var i ControlWorkspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveTwoFactor = `-- name: HasActiveTwoFactor :one
SELECT EXISTS(
    SELECT 1 FROM control_two_factor WHERE account_id = $1 AND activated_at IS NOT NULL
) AS active
`

func (q *Queries) HasActiveTwoFactor(ctx context.Context, accountID string) (bool, error) {
	row := q.queryRow(ctx, q.hasActiveTwoFactorStmt, hasActiveTwoFactor, accountID)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const incrementInviteUse = `-- name: IncrementInviteUse :execrows
UPDATE control_workspace_invite SET used_count = used_count + 1
WHERE id = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
  AND (max_uses IS NULL OR used_count < max_uses)
`

func (q *Queries) IncrementInviteUse(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.incrementInviteUseStmt, incrementInviteUse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const isActiveWorkspaceMember = `-- name: IsActiveWorkspaceMember :one
SELECT EXISTS(
    SELECT 1 FROM control_workspace_member
    WHERE workspace_id = $1 AND account_id = $2 AND status = 'active'
) AS active
`

type IsActiveWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) IsActiveWorkspaceMember(ctx context.Context, arg IsActiveWorkspaceMemberParams) (bool, error) {
	row := q.queryRow(ctx, q.isActiveWorkspaceMemberStmt, isActiveWorkspaceMember, arg.WorkspaceID, arg.AccountID)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const listAccessCatalog = `-- name: ListAccessCatalog :many
SELECT g.service, service_catalog.position AS service_position, g.group_key, g.position AS group_position,
       COALESCE(service_title.value, g.service) AS service_title,
       COALESCE(service_description.value, '') AS service_description,
       COALESCE(group_loc.value, g.group_key) AS group_title,
       COALESCE(group_description.value, '') AS group_description,
       m.method_key, m.position,
       COALESCE(access_loc.value, m.method_key) AS access_title,
       COALESCE(access_description.value, '') AS access_description
FROM control_method_group g
JOIN control_method m ON m.service = g.service AND m.group_key = g.group_key
JOIN control_access_service service_catalog ON service_catalog.service = g.service
LEFT JOIN control_localization service_title
    ON service_title.localization_key = 'control.access_service.' || g.service || '.title'
   AND service_title.locale = $1
LEFT JOIN control_localization service_description
    ON service_description.localization_key = 'control.access_service.' || g.service || '.description'
   AND service_description.locale = $2
LEFT JOIN control_localization group_loc
    ON group_loc.localization_key = 'control.method_group.' || g.service || '.' || g.group_key
   AND group_loc.locale = $3
LEFT JOIN control_localization group_description
    ON group_description.localization_key = 'control.method_group.' || g.service || '.' || g.group_key || '.description'
   AND group_description.locale = $4
LEFT JOIN control_localization access_loc
    ON access_loc.localization_key = 'control.method.' || m.method_key
   AND access_loc.locale = $5
LEFT JOIN control_localization access_description
    ON access_description.localization_key = 'control.method.' || m.method_key || '.description'
   AND access_description.locale = $6
ORDER BY service_catalog.position, g.position, m.position, m.method_key
`

type ListAccessCatalogParams struct {
	Locale   string `json:"locale"`
	Locale_2 string `json:"locale_2"`
	Locale_3 string `json:"locale_3"`
	Locale_4 string `json:"locale_4"`
	Locale_5 string `json:"locale_5"`
	Locale_6 string `json:"locale_6"`
}

type ListAccessCatalogRow struct {
	Service            string `json:"service"`
	ServicePosition    int32  `json:"service_position"`
	GroupKey           string `json:"group_key"`
	GroupPosition      int32  `json:"group_position"`
	ServiceTitle       string `json:"service_title"`
	ServiceDescription string `json:"service_description"`
	GroupTitle         string `json:"group_title"`
	GroupDescription   string `json:"group_description"`
	MethodKey          string `json:"method_key"`
	Position           int32  `json:"position"`
	AccessTitle        string `json:"access_title"`
	AccessDescription  string `json:"access_description"`
}

func (q *Queries) ListAccessCatalog(ctx context.Context, arg ListAccessCatalogParams) ([]ListAccessCatalogRow, error) {
	rows, err := q.query(ctx, q.listAccessCatalogStmt, listAccessCatalog,
		arg.Locale,
		arg.Locale_2,
		arg.Locale_3,
		arg.Locale_4,
		arg.Locale_5,
		arg.Locale_6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccessCatalogRow
	for rows.Next() {
		var i ListAccessCatalogRow
		if err := rows.Scan(
			&i.Service,
			&i.ServicePosition,
			&i.GroupKey,
			&i.GroupPosition,
			&i.ServiceTitle,
			&i.ServiceDescription,
			&i.GroupTitle,
			&i.GroupDescription,
			&i.MethodKey,
			&i.Position,
			&i.AccessTitle,
			&i.AccessDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, workspace_id, actor_id, method_key, target_type, target_id,
       COALESCE(before_data, '{}'::jsonb) AS before_data, COALESCE(after_data, '{}'::jsonb) AS after_data, result, request_id, occurred_at
FROM control_audit_event
WHERE workspace_id = $1
ORDER BY occurred_at DESC, id DESC LIMIT $2 OFFSET $3
`

type ListAuditEventsParams struct {
	WorkspaceID sql.NullString `json:"workspace_id"`
	Limit       int32          `json:"limit"`
	Offset      int32          `json:"offset"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ControlAuditEvent, error) {
	rows, err := q.query(ctx, q.listAuditEventsStmt, listAuditEvents, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlAuditEvent
	for rows.Next() {
		var i ControlAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.MethodKey,
			&i.TargetType,
			&i.TargetID,
			&i.BeforeData,
			&i.AfterData,
			&i.Result,
			&i.RequestID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsFiltered = `-- name: ListAuditEventsFiltered :many
SELECT id, workspace_id, actor_id, method_key, target_type, target_id,
       COALESCE(before_data, '{}'::jsonb) AS before_data, COALESCE(after_data, '{}'::jsonb) AS after_data, result, request_id, occurred_at
FROM control_audit_event
WHERE workspace_id = $1
  AND ($2 = '' OR method_key = $3)
  AND ($4 = '' OR actor_id = $5)
  AND ($6 IS NULL OR occurred_at >= $7)
  AND ($8 IS NULL OR occurred_at < $9)
ORDER BY occurred_at DESC, id DESC LIMIT $10 OFFSET $11
`

type ListAuditEventsFilteredParams struct {
	WorkspaceID  sql.NullString `json:"workspace_id"`
	Column2      interface{}    `json:"column_2"`
	MethodKey    string         `json:"method_key"`
	Column4      interface{}    `json:"column_4"`
	ActorID      sql.NullString `json:"actor_id"`
	Column6      interface{}    `json:"column_6"`
	OccurredAt   time.Time      `json:"occurred_at"`
	Column8      interface{}    `json:"column_8"`
	OccurredAt_2 time.Time      `json:"occurred_at_2"`
	Limit        int32          `json:"limit"`
	Offset       int32          `json:"offset"`
}

func (q *Queries) ListAuditEventsFiltered(ctx context.Context, arg ListAuditEventsFilteredParams) ([]ControlAuditEvent, error) {
	rows, err := q.query(ctx, q.listAuditEventsFilteredStmt, listAuditEventsFiltered,
		arg.WorkspaceID,
		arg.Column2,
		arg.MethodKey,
		arg.Column4,
		arg.ActorID,
		arg.Column6,
		arg.OccurredAt,
		arg.Column8,
		arg.OccurredAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlAuditEvent
	for rows.Next() {
		var i ControlAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.MethodKey,
			&i.TargetType,
			&i.TargetID,
			&i.BeforeData,
			&i.AfterData,
			&i.Result,
			&i.RequestID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorizedMethods = `-- name: ListAuthorizedMethods :many
SELECT DISTINCT cm.method_key, cm.service, cm.group_key, cm.position
FROM control_method cm
JOIN control_workspace_member m ON m.workspace_id = $1 AND m.account_id = $2 AND m.status = 'active'
JOIN control_role_member rm ON rm.account_id = m.account_id
JOIN control_role r ON r.id = rm.role_id AND r.workspace_id = m.workspace_id AND r.deleted_at IS NULL
LEFT JOIN control_role_permission p ON p.role_id = r.id AND p.method_key = cm.method_key
WHERE r.is_owner = TRUE OR p.method_key IS NOT NULL
ORDER BY cm.service, cm.group_key, cm.method_key
`

type ListAuthorizedMethodsParams struct {
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

type ListAuthorizedMethodsRow struct {
	MethodKey string `json:"method_key"`
	Service   string `json:"service"`
	GroupKey  string `json:"group_key"`
	Position  int32  `json:"position"`
}

func (q *Queries) ListAuthorizedMethods(ctx context.Context, arg ListAuthorizedMethodsParams) ([]ListAuthorizedMethodsRow, error) {
	rows, err := q.query(ctx, q.listAuthorizedMethodsStmt, listAuthorizedMethods, arg.WorkspaceID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorizedMethodsRow
	for rows.Next() {
		var i ListAuthorizedMethodsRow
		if err := rows.Scan(
			&i.MethodKey,
			&i.Service,
			&i.GroupKey,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentities = `-- name: ListIdentities :many
SELECT account_id, provider, provider_subject, created_at, updated_at
FROM control_identity WHERE account_id = $1 ORDER BY provider
`

type ListIdentitiesRow struct {
	AccountID       string    `json:"account_id"`
	Provider        string    `json:"provider"`
	ProviderSubject string    `json:"provider_subject"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) ListIdentities(ctx context.Context, accountID string) ([]ListIdentitiesRow, error) {
	rows, err := q.query(ctx, q.listIdentitiesStmt, listIdentities, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentitiesRow
	for rows.Next() {
		var i ListIdentitiesRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Provider,
			&i.ProviderSubject,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInviteRoles = `-- name: ListInviteRoles :many
SELECT role_id FROM control_workspace_invite_role WHERE invite_id = $1 ORDER BY role_id
`

func (q *Queries) ListInviteRoles(ctx context.Context, inviteID string) ([]string, error) {
	rows, err := q.query(ctx, q.listInviteRolesStmt, listInviteRoles, inviteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role_id string
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, workspace_id, created_by, token_hash, max_uses, used_count, expires_at, revoked_at, created_at
FROM control_workspace_invite WHERE workspace_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListInvitesParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListInvites(ctx context.Context, arg ListInvitesParams) ([]ControlWorkspaceInvite, error) {
	rows, err := q.query(ctx, q.listInvitesStmt, listInvites, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlWorkspaceInvite
	for rows.Next() {
		var i ControlWorkspaceInvite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.TokenHash,
			&i.MaxUses,
			&i.UsedCount,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMethodGroups = `-- name: ListMethodGroups :many
SELECT service, group_key, position, created_at, updated_at
FROM control_method_group
ORDER BY service, group_key
`

func (q *Queries) ListMethodGroups(ctx context.Context) ([]ControlMethodGroup, error) {
	rows, err := q.query(ctx, q.listMethodGroupsStmt, listMethodGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlMethodGroup
	for rows.Next() {
		var i ControlMethodGroup
		if err := rows.Scan(
			&i.Service,
			&i.GroupKey,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMethods = `-- name: ListMethods :many
SELECT method_key, service, group_key, position, created_at, updated_at
FROM control_method ORDER BY service, group_key, method_key
`

func (q *Queries) ListMethods(ctx context.Context) ([]ControlMethod, error) {
	rows, err := q.query(ctx, q.listMethodsStmt, listMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlMethod
	for rows.Next() {
		var i ControlMethod
		if err := rows.Scan(
			&i.MethodKey,
			&i.Service,
			&i.GroupKey,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT p.role_id, p.method_key, p.created_at
FROM control_role_permission p
JOIN control_role r ON r.id = p.role_id
WHERE r.workspace_id = $1 AND p.role_id = $2 AND r.deleted_at IS NULL
ORDER BY p.method_key
`

type ListRolePermissionsParams struct {
	WorkspaceID string `json:"workspace_id"`
	RoleID      string `json:"role_id"`
}

func (q *Queries) ListRolePermissions(ctx context.Context, arg ListRolePermissionsParams) ([]ControlRolePermission, error) {
	rows, err := q.query(ctx, q.listRolePermissionsStmt, listRolePermissions, arg.WorkspaceID, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRolePermission
	for rows.Next() {
		var i ControlRolePermission
		if err := rows.Scan(&i.RoleID, &i.MethodKey, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT r.id, r.workspace_id, r.code, r.title, r.description, r.position, r.is_owner, r.deleted_at, r.created_at, r.updated_at,
       COUNT(rm.account_id) AS member_count
FROM control_role r
LEFT JOIN control_role_member rm ON rm.role_id = r.id
WHERE r.workspace_id = $1 AND r.deleted_at IS NULL
GROUP BY r.id
ORDER BY r.position, r.id
`

type ListRolesRow struct {
	ID          string       `json:"id"`
	WorkspaceID string       `json:"workspace_id"`
	Code        string       `json:"code"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Position    int32        `json:"position"`
	IsOwner     bool         `json:"is_owner"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	MemberCount int64        `json:"member_count"`
}

func (q *Queries) ListRoles(ctx context.Context, workspaceID string) ([]ListRolesRow, error) {
	rows, err := q.query(ctx, q.listRolesStmt, listRoles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesRow
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.IsOwner,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, account_id, token_hash, ip, user_agent, bind_to_ip, expires_at, revoked_at, last_used_at, created_at
FROM control_session WHERE account_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context, accountID string) ([]ControlSession, error) {
	rows, err := q.query(ctx, q.listSessionsStmt, listSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlSession
	for rows.Next() {
		var i ControlSession
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenHash,
			&i.Ip,
			&i.UserAgent,
			&i.BindToIp,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT m.workspace_id, m.account_id, m.status, m.joined_at, m.updated_at,
       a.display_name, COALESCE(MIN(r.position), 2147483647) AS position
FROM control_workspace_member m
JOIN control_account a ON a.id = m.account_id
LEFT JOIN control_role_member rm ON rm.account_id = m.account_id
LEFT JOIN control_role r ON r.id = rm.role_id AND r.workspace_id = m.workspace_id AND r.deleted_at IS NULL
WHERE m.workspace_id = $1 AND m.status = 'active'
GROUP BY m.workspace_id, m.account_id, m.status, m.joined_at, m.updated_at, a.display_name
ORDER BY position, m.joined_at
LIMIT $2 OFFSET $3
`

type ListWorkspaceMembersParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type ListWorkspaceMembersRow struct {
	WorkspaceID string      `json:"workspace_id"`
	AccountID   string      `json:"account_id"`
	Status      string      `json:"status"`
	JoinedAt    time.Time   `json:"joined_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	DisplayName string      `json:"display_name"`
	Position    interface{} `json:"position"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, arg ListWorkspaceMembersParams) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.query(ctx, q.listWorkspaceMembersStmt, listWorkspaceMembers, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceMembersRow
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.AccountID,
			&i.Status,
			&i.JoinedAt,
			&i.UpdatedAt,
			&i.DisplayName,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForAccount = `-- name: ListWorkspacesForAccount :many
SELECT w.id, w.slug, w.title, w.status, w.created_by, w.created_at, w.updated_at
FROM control_workspace w
JOIN control_workspace_member m ON m.workspace_id = w.id
WHERE m.account_id = $1 AND m.status = 'active'
ORDER BY w.created_at DESC LIMIT $2 OFFSET $3
`

type ListWorkspacesForAccountParams struct {
	AccountID string `json:"account_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListWorkspacesForAccount(ctx context.Context, arg ListWorkspacesForAccountParams) ([]ControlWorkspace, error) {
	rows, err := q.query(ctx, q.listWorkspacesForAccountStmt, listWorkspacesForAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlWorkspace
	for rows.Next() {
		var i ControlWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMethodRegistry = `-- name: LockMethodRegistry :exec
SELECT pg_advisory_xact_lock(hashtextextended('control:method-registry', 0))
`

func (q *Queries) LockMethodRegistry(ctx context.Context) error {
	_, err := q.exec(ctx, q.lockMethodRegistryStmt, lockMethodRegistry)
	return err
}

const lockWorkspaceAuthorization = `-- name: LockWorkspaceAuthorization :exec
SELECT pg_advisory_xact_lock(hashtextextended('control:authorization:' || $1::text, 0))
`

func (q *Queries) LockWorkspaceAuthorization(ctx context.Context, dollar_1 string) error {
	_, err := q.exec(ctx, q.lockWorkspaceAuthorizationStmt, lockWorkspaceAuthorization, dollar_1)
	return err
}

const removeRoleMember = `-- name: RemoveRoleMember :execrows
DELETE FROM control_role_member WHERE role_id = $1 AND account_id = $2
`

type RemoveRoleMemberParams struct {
	RoleID    string `json:"role_id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) RemoveRoleMember(ctx context.Context, arg RemoveRoleMemberParams) (int64, error) {
	result, err := q.exec(ctx, q.removeRoleMemberStmt, removeRoleMember, arg.RoleID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :execrows
UPDATE control_workspace_member SET status = 'removed'
WHERE workspace_id = $1 AND account_id = $2 AND status = 'active'
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (int64, error) {
	result, err := q.exec(ctx, q.removeWorkspaceMemberStmt, removeWorkspaceMember, arg.WorkspaceID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeWorkspaceMemberRoles = `-- name: RemoveWorkspaceMemberRoles :execrows
DELETE FROM control_role_member rm
USING control_role r
WHERE r.id = rm.role_id
  AND r.workspace_id = $1
  AND rm.account_id = $2
`

type RemoveWorkspaceMemberRolesParams struct {
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) RemoveWorkspaceMemberRoles(ctx context.Context, arg RemoveWorkspaceMemberRolesParams) (int64, error) {
	result, err := q.exec(ctx, q.removeWorkspaceMemberRolesStmt, removeWorkspaceMemberRoles, arg.WorkspaceID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAllSessions = `-- name: RevokeAllSessions :execrows
UPDATE control_session SET revoked_at = now()
WHERE account_id = $1 AND revoked_at IS NULL AND ($2 = '' OR id <> $3)
`

type RevokeAllSessionsParams struct {
	AccountID string      `json:"account_id"`
	Column2   interface{} `json:"column_2"`
	ID        string      `json:"id"`
}

func (q *Queries) RevokeAllSessions(ctx context.Context, arg RevokeAllSessionsParams) (int64, error) {
	result, err := q.exec(ctx, q.revokeAllSessionsStmt, revokeAllSessions, arg.AccountID, arg.Column2, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE control_workspace_invite SET revoked_at = now()
WHERE id = $1 AND workspace_id = $2 AND revoked_at IS NULL
`

type RevokeInviteParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.exec(ctx, q.revokeInviteStmt, revokeInvite, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeInviteAsActiveMember = `-- name: RevokeInviteAsActiveMember :execrows
UPDATE control_workspace_invite i
SET revoked_at = now()
WHERE i.id = $1 AND i.workspace_id = $2 AND i.revoked_at IS NULL
  AND EXISTS (
      SELECT 1 FROM control_workspace_member m
      WHERE m.workspace_id = i.workspace_id AND m.account_id = $3 AND m.status = 'active'
  )
`

type RevokeInviteAsActiveMemberParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	AccountID   string `json:"account_id"`
}

func (q *Queries) RevokeInviteAsActiveMember(ctx context.Context, arg RevokeInviteAsActiveMemberParams) (int64, error) {
	result, err := q.exec(ctx, q.revokeInviteAsActiveMemberStmt, revokeInviteAsActiveMember, arg.ID, arg.WorkspaceID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE control_session SET revoked_at = now()
WHERE id = $1 AND account_id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.exec(ctx, q.revokeSessionStmt, revokeSession, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRolePermission = `-- name: SetRolePermission :exec
INSERT INTO control_role_permission (role_id, method_key)
VALUES ($1, $2)
ON CONFLICT (role_id, method_key) DO NOTHING
`

type SetRolePermissionParams struct {
	RoleID    string `json:"role_id"`
	MethodKey string `json:"method_key"`
}

func (q *Queries) SetRolePermission(ctx context.Context, arg SetRolePermissionParams) error {
	_, err := q.exec(ctx, q.setRolePermissionStmt, setRolePermission, arg.RoleID, arg.MethodKey)
	return err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE control_session SET last_used_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.touchSessionStmt, touchSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePendingTwoFactorBackupHashes = `-- name: UpdatePendingTwoFactorBackupHashes :execrows
UPDATE control_two_factor SET backup_hashes = $1 WHERE account_id = $2 AND activated_at IS NULL
`

type UpdatePendingTwoFactorBackupHashesParams struct {
	BackupHashes json.RawMessage `json:"backup_hashes"`
	AccountID    string          `json:"account_id"`
}

func (q *Queries) UpdatePendingTwoFactorBackupHashes(ctx context.Context, arg UpdatePendingTwoFactorBackupHashesParams) (int64, error) {
	result, err := q.exec(ctx, q.updatePendingTwoFactorBackupHashesStmt, updatePendingTwoFactorBackupHashes, arg.BackupHashes, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE control_role SET title = $1, description = $2, position = $3
WHERE id = $4 AND workspace_id = $5 AND deleted_at IS NULL AND is_owner = FALSE
`

type UpdateRoleParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Position    int32  `json:"position"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.exec(ctx, q.updateRoleStmt, updateRole,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.ID,
		arg.WorkspaceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTwoFactorBackupHashes = `-- name: UpdateTwoFactorBackupHashes :execrows
UPDATE control_two_factor SET backup_hashes = $1 WHERE account_id = $2 AND activated_at IS NOT NULL
`

type UpdateTwoFactorBackupHashesParams struct {
	BackupHashes json.RawMessage `json:"backup_hashes"`
	AccountID    string          `json:"account_id"`
}

func (q *Queries) UpdateTwoFactorBackupHashes(ctx context.Context, arg UpdateTwoFactorBackupHashesParams) (int64, error) {
	result, err := q.exec(ctx, q.updateTwoFactorBackupHashesStmt, updateTwoFactorBackupHashes, arg.BackupHashes, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspace = `-- name: UpdateWorkspace :execrows
UPDATE control_workspace SET slug = $1, title = $2, status = $3 WHERE id = $4
`

type UpdateWorkspaceParams struct {
	Slug   string `json:"slug"`
	Title  string `json:"title"`
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (int64, error) {
	result, err := q.exec(ctx, q.updateWorkspaceStmt, updateWorkspace,
		arg.Slug,
		arg.Title,
		arg.Status,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspaceAsActiveMember = `-- name: UpdateWorkspaceAsActiveMember :execrows
UPDATE control_workspace w
SET slug = $1, title = $2, status = $3
WHERE w.id = $4
  AND EXISTS (
      SELECT 1 FROM control_workspace_member m
      WHERE m.workspace_id = w.id AND m.account_id = $5 AND m.status = 'active'
  )
`

type UpdateWorkspaceAsActiveMemberParams struct {
	Slug      string `json:"slug"`
	Title     string `json:"title"`
	Status    string `json:"status"`
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
}

func (q *Queries) UpdateWorkspaceAsActiveMember(ctx context.Context, arg UpdateWorkspaceAsActiveMemberParams) (int64, error) {
	result, err := q.exec(ctx, q.updateWorkspaceAsActiveMemberStmt, updateWorkspaceAsActiveMember,
		arg.Slug,
		arg.Title,
		arg.Status,
		arg.ID,
		arg.AccountID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertIdentity = `-- name: UpsertIdentity :exec
INSERT INTO control_identity (account_id, provider, provider_subject, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, provider) DO UPDATE SET
    provider_subject = EXCLUDED.provider_subject,
    payload = EXCLUDED.payload,
    updated_at = now()
`

type UpsertIdentityParams struct {
	AccountID       string                `json:"account_id"`
	Provider        string                `json:"provider"`
	ProviderSubject string                `json:"provider_subject"`
	Payload         pqtype.NullRawMessage `json:"payload"`
}

func (q *Queries) UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) error {
	_, err := q.exec(ctx, q.upsertIdentityStmt, upsertIdentity,
		arg.AccountID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Payload,
	)
	return err
}

const upsertMethod = `-- name: UpsertMethod :exec
INSERT INTO control_method (method_key, service, group_key, position)
VALUES ($1, $2, $3, $4)
ON CONFLICT (method_key) DO UPDATE SET
    service = EXCLUDED.service,
    group_key = EXCLUDED.group_key,
    position = EXCLUDED.position,
    updated_at = now()
`

type UpsertMethodParams struct {
	MethodKey string `json:"method_key"`
	Service   string `json:"service"`
	GroupKey  string `json:"group_key"`
	Position  int32  `json:"position"`
}

func (q *Queries) UpsertMethod(ctx context.Context, arg UpsertMethodParams) error {
	_, err := q.exec(ctx, q.upsertMethodStmt, upsertMethod,
		arg.MethodKey,
		arg.Service,
		arg.GroupKey,
		arg.Position,
	)
	return err
}

const upsertMethodGroup = `-- name: UpsertMethodGroup :exec
INSERT INTO control_method_group (service, group_key, position)
VALUES ($1, $2, $3)
ON CONFLICT (service, group_key) DO UPDATE SET
    position = EXCLUDED.position,
    updated_at = now()
`

type UpsertMethodGroupParams struct {
	Service  string `json:"service"`
	GroupKey string `json:"group_key"`
	Position int32  `json:"position"`
}

func (q *Queries) UpsertMethodGroup(ctx context.Context, arg UpsertMethodGroupParams) error {
	_, err := q.exec(ctx, q.upsertMethodGroupStmt, upsertMethodGroup, arg.Service, arg.GroupKey, arg.Position)
	return err
}

const upsertTwoFactor = `-- name: UpsertTwoFactor :exec
INSERT INTO control_two_factor (account_id, secret, backup_hashes, activated_at)
VALUES ($1, $2, $3, NULL)
ON CONFLICT (account_id) DO UPDATE SET
    secret = EXCLUDED.secret,
    backup_hashes = EXCLUDED.backup_hashes,
    activated_at = NULL,
    updated_at = now()
`

type UpsertTwoFactorParams struct {
	AccountID    string          `json:"account_id"`
	Secret       string          `json:"secret"`
	BackupHashes json.RawMessage `json:"backup_hashes"`
}

func (q *Queries) UpsertTwoFactor(ctx context.Context, arg UpsertTwoFactorParams) error {
	_, err := q.exec(ctx, q.upsertTwoFactorStmt, upsertTwoFactor, arg.AccountID, arg.Secret, arg.BackupHashes)
	return err
}
