// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type PaymentAssetAssetKind string

const (
	PaymentAssetAssetKindFiat             PaymentAssetAssetKind = "fiat"
	PaymentAssetAssetKindPlatformCurrency PaymentAssetAssetKind = "platform_currency"
	PaymentAssetAssetKindCryptoNative     PaymentAssetAssetKind = "crypto_native"
	PaymentAssetAssetKindCryptoJetton     PaymentAssetAssetKind = "crypto_jetton"
)

func (e *PaymentAssetAssetKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentAssetAssetKind(s)
	case string:
		*e = PaymentAssetAssetKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentAssetAssetKind: %T", src)
	}
	return nil
}

type NullPaymentAssetAssetKind struct {
	PaymentAssetAssetKind PaymentAssetAssetKind `json:"payment_asset_asset_kind"`
	Valid                 bool                  `json:"valid"` // Valid is true if PaymentAssetAssetKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentAssetAssetKind) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentAssetAssetKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentAssetAssetKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentAssetAssetKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentAssetAssetKind), nil
}

type PaymentAttemptStatus string

const (
	PaymentAttemptStatusCreated        PaymentAttemptStatus = "created"
	PaymentAttemptStatusPending        PaymentAttemptStatus = "pending"
	PaymentAttemptStatusRequiresAction PaymentAttemptStatus = "requires_action"
	PaymentAttemptStatusWaitingCapture PaymentAttemptStatus = "waiting_capture"
	PaymentAttemptStatusSucceeded      PaymentAttemptStatus = "succeeded"
	PaymentAttemptStatusCanceled       PaymentAttemptStatus = "canceled"
	PaymentAttemptStatusExpired        PaymentAttemptStatus = "expired"
	PaymentAttemptStatusRefunded       PaymentAttemptStatus = "refunded"
	PaymentAttemptStatusChargebacked   PaymentAttemptStatus = "chargebacked"
	PaymentAttemptStatusFailed         PaymentAttemptStatus = "failed"
)

func (e *PaymentAttemptStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentAttemptStatus(s)
	case string:
		*e = PaymentAttemptStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentAttemptStatus: %T", src)
	}
	return nil
}

type NullPaymentAttemptStatus struct {
	PaymentAttemptStatus PaymentAttemptStatus `json:"payment_attempt_status"`
	Valid                bool                 `json:"valid"` // Valid is true if PaymentAttemptStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentAttemptStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentAttemptStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentAttemptStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentAttemptStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentAttemptStatus), nil
}

type PaymentEventProcessingStatus string

const (
	PaymentEventProcessingStatusNew       PaymentEventProcessingStatus = "new"
	PaymentEventProcessingStatusProcessed PaymentEventProcessingStatus = "processed"
	PaymentEventProcessingStatusIgnored   PaymentEventProcessingStatus = "ignored"
	PaymentEventProcessingStatusFailed    PaymentEventProcessingStatus = "failed"
)

func (e *PaymentEventProcessingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentEventProcessingStatus(s)
	case string:
		*e = PaymentEventProcessingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentEventProcessingStatus: %T", src)
	}
	return nil
}

type NullPaymentEventProcessingStatus struct {
	PaymentEventProcessingStatus PaymentEventProcessingStatus `json:"payment_event_processing_status"`
	Valid                        bool                         `json:"valid"` // Valid is true if PaymentEventProcessingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentEventProcessingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentEventProcessingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentEventProcessingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentEventProcessingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentEventProcessingStatus), nil
}

type PaymentFulfillmentItemDurationUnit string

const (
	PaymentFulfillmentItemDurationUnitSecond PaymentFulfillmentItemDurationUnit = "second"
	PaymentFulfillmentItemDurationUnitMinute PaymentFulfillmentItemDurationUnit = "minute"
	PaymentFulfillmentItemDurationUnitHour   PaymentFulfillmentItemDurationUnit = "hour"
	PaymentFulfillmentItemDurationUnitDay    PaymentFulfillmentItemDurationUnit = "day"
	PaymentFulfillmentItemDurationUnitWeek   PaymentFulfillmentItemDurationUnit = "week"
	PaymentFulfillmentItemDurationUnitMonth  PaymentFulfillmentItemDurationUnit = "month"
	PaymentFulfillmentItemDurationUnitYear   PaymentFulfillmentItemDurationUnit = "year"
)

func (e *PaymentFulfillmentItemDurationUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentFulfillmentItemDurationUnit(s)
	case string:
		*e = PaymentFulfillmentItemDurationUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentFulfillmentItemDurationUnit: %T", src)
	}
	return nil
}

type NullPaymentFulfillmentItemDurationUnit struct {
	PaymentFulfillmentItemDurationUnit PaymentFulfillmentItemDurationUnit `json:"payment_fulfillment_item_duration_unit"`
	Valid                              bool                               `json:"valid"` // Valid is true if PaymentFulfillmentItemDurationUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentFulfillmentItemDurationUnit) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentFulfillmentItemDurationUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentFulfillmentItemDurationUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentFulfillmentItemDurationUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentFulfillmentItemDurationUnit), nil
}

type PaymentFulfillmentItemRewardType string

const (
	PaymentFulfillmentItemRewardTypeQuantity PaymentFulfillmentItemRewardType = "quantity"
	PaymentFulfillmentItemRewardTypeDuration PaymentFulfillmentItemRewardType = "duration"
)

func (e *PaymentFulfillmentItemRewardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentFulfillmentItemRewardType(s)
	case string:
		*e = PaymentFulfillmentItemRewardType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentFulfillmentItemRewardType: %T", src)
	}
	return nil
}

type NullPaymentFulfillmentItemRewardType struct {
	PaymentFulfillmentItemRewardType PaymentFulfillmentItemRewardType `json:"payment_fulfillment_item_reward_type"`
	Valid                            bool                             `json:"valid"` // Valid is true if PaymentFulfillmentItemRewardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentFulfillmentItemRewardType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentFulfillmentItemRewardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentFulfillmentItemRewardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentFulfillmentItemRewardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentFulfillmentItemRewardType), nil
}

type PaymentFulfillmentStatus string

const (
	PaymentFulfillmentStatusPending   PaymentFulfillmentStatus = "pending"
	PaymentFulfillmentStatusSucceeded PaymentFulfillmentStatus = "succeeded"
	PaymentFulfillmentStatusRevoked   PaymentFulfillmentStatus = "revoked"
	PaymentFulfillmentStatusFailed    PaymentFulfillmentStatus = "failed"
)

func (e *PaymentFulfillmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentFulfillmentStatus(s)
	case string:
		*e = PaymentFulfillmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentFulfillmentStatus: %T", src)
	}
	return nil
}

type NullPaymentFulfillmentStatus struct {
	PaymentFulfillmentStatus PaymentFulfillmentStatus `json:"payment_fulfillment_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if PaymentFulfillmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentFulfillmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentFulfillmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentFulfillmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentFulfillmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentFulfillmentStatus), nil
}

type PaymentOrderItemDurationUnit string

const (
	PaymentOrderItemDurationUnitSecond PaymentOrderItemDurationUnit = "second"
	PaymentOrderItemDurationUnitMinute PaymentOrderItemDurationUnit = "minute"
	PaymentOrderItemDurationUnitHour   PaymentOrderItemDurationUnit = "hour"
	PaymentOrderItemDurationUnitDay    PaymentOrderItemDurationUnit = "day"
	PaymentOrderItemDurationUnitWeek   PaymentOrderItemDurationUnit = "week"
	PaymentOrderItemDurationUnitMonth  PaymentOrderItemDurationUnit = "month"
	PaymentOrderItemDurationUnitYear   PaymentOrderItemDurationUnit = "year"
)

func (e *PaymentOrderItemDurationUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentOrderItemDurationUnit(s)
	case string:
		*e = PaymentOrderItemDurationUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentOrderItemDurationUnit: %T", src)
	}
	return nil
}

type NullPaymentOrderItemDurationUnit struct {
	PaymentOrderItemDurationUnit PaymentOrderItemDurationUnit `json:"payment_order_item_duration_unit"`
	Valid                        bool                         `json:"valid"` // Valid is true if PaymentOrderItemDurationUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentOrderItemDurationUnit) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentOrderItemDurationUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentOrderItemDurationUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentOrderItemDurationUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentOrderItemDurationUnit), nil
}

type PaymentOrderItemRewardType string

const (
	PaymentOrderItemRewardTypeQuantity PaymentOrderItemRewardType = "quantity"
	PaymentOrderItemRewardTypeDuration PaymentOrderItemRewardType = "duration"
)

func (e *PaymentOrderItemRewardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentOrderItemRewardType(s)
	case string:
		*e = PaymentOrderItemRewardType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentOrderItemRewardType: %T", src)
	}
	return nil
}

type NullPaymentOrderItemRewardType struct {
	PaymentOrderItemRewardType PaymentOrderItemRewardType `json:"payment_order_item_reward_type"`
	Valid                      bool                       `json:"valid"` // Valid is true if PaymentOrderItemRewardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentOrderItemRewardType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentOrderItemRewardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentOrderItemRewardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentOrderItemRewardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentOrderItemRewardType), nil
}

type PaymentOrderStatus string

const (
	PaymentOrderStatusDraft          PaymentOrderStatus = "draft"
	PaymentOrderStatusPendingPayment PaymentOrderStatus = "pending_payment"
	PaymentOrderStatusPaid           PaymentOrderStatus = "paid"
	PaymentOrderStatusFulfilled      PaymentOrderStatus = "fulfilled"
	PaymentOrderStatusCanceled       PaymentOrderStatus = "canceled"
	PaymentOrderStatusExpired        PaymentOrderStatus = "expired"
	PaymentOrderStatusRefunded       PaymentOrderStatus = "refunded"
	PaymentOrderStatusChargebacked   PaymentOrderStatus = "chargebacked"
	PaymentOrderStatusFailed         PaymentOrderStatus = "failed"
)

func (e *PaymentOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentOrderStatus(s)
	case string:
		*e = PaymentOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentOrderStatus: %T", src)
	}
	return nil
}

type NullPaymentOrderStatus struct {
	PaymentOrderStatus PaymentOrderStatus `json:"payment_order_status"`
	Valid              bool               `json:"valid"` // Valid is true if PaymentOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentOrderStatus), nil
}

type PaymentPaidOrderIndexStatus string

const (
	PaymentPaidOrderIndexStatusPaid      PaymentPaidOrderIndexStatus = "paid"
	PaymentPaidOrderIndexStatusFulfilled PaymentPaidOrderIndexStatus = "fulfilled"
)

func (e *PaymentPaidOrderIndexStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentPaidOrderIndexStatus(s)
	case string:
		*e = PaymentPaidOrderIndexStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentPaidOrderIndexStatus: %T", src)
	}
	return nil
}

type NullPaymentPaidOrderIndexStatus struct {
	PaymentPaidOrderIndexStatus PaymentPaidOrderIndexStatus `json:"payment_paid_order_index_status"`
	Valid                       bool                        `json:"valid"` // Valid is true if PaymentPaidOrderIndexStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentPaidOrderIndexStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentPaidOrderIndexStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentPaidOrderIndexStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentPaidOrderIndexStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentPaidOrderIndexStatus), nil
}

type PaymentPricePricingMode string

const (
	PaymentPricePricingModeFixed   PaymentPricePricingMode = "fixed"
	PaymentPricePricingModeDynamic PaymentPricePricingMode = "dynamic"
)

func (e *PaymentPricePricingMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentPricePricingMode(s)
	case string:
		*e = PaymentPricePricingMode(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentPricePricingMode: %T", src)
	}
	return nil
}

type NullPaymentPricePricingMode struct {
	PaymentPricePricingMode PaymentPricePricingMode `json:"payment_price_pricing_mode"`
	Valid                   bool                    `json:"valid"` // Valid is true if PaymentPricePricingMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentPricePricingMode) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentPricePricingMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentPricePricingMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentPricePricingMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentPricePricingMode), nil
}

type PaymentProductCacheDurationUnit string

const (
	PaymentProductCacheDurationUnitSecond PaymentProductCacheDurationUnit = "second"
	PaymentProductCacheDurationUnitMinute PaymentProductCacheDurationUnit = "minute"
	PaymentProductCacheDurationUnitHour   PaymentProductCacheDurationUnit = "hour"
	PaymentProductCacheDurationUnitDay    PaymentProductCacheDurationUnit = "day"
	PaymentProductCacheDurationUnitWeek   PaymentProductCacheDurationUnit = "week"
	PaymentProductCacheDurationUnitMonth  PaymentProductCacheDurationUnit = "month"
	PaymentProductCacheDurationUnitYear   PaymentProductCacheDurationUnit = "year"
)

func (e *PaymentProductCacheDurationUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProductCacheDurationUnit(s)
	case string:
		*e = PaymentProductCacheDurationUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProductCacheDurationUnit: %T", src)
	}
	return nil
}

type NullPaymentProductCacheDurationUnit struct {
	PaymentProductCacheDurationUnit PaymentProductCacheDurationUnit `json:"payment_product_cache_duration_unit"`
	Valid                           bool                            `json:"valid"` // Valid is true if PaymentProductCacheDurationUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProductCacheDurationUnit) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProductCacheDurationUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProductCacheDurationUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProductCacheDurationUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProductCacheDurationUnit), nil
}

type PaymentProductCacheGlobalInterval string

const (
	PaymentProductCacheGlobalIntervalSECOND    PaymentProductCacheGlobalInterval = "SECOND"
	PaymentProductCacheGlobalIntervalMINUTE    PaymentProductCacheGlobalInterval = "MINUTE"
	PaymentProductCacheGlobalIntervalHOUR      PaymentProductCacheGlobalInterval = "HOUR"
	PaymentProductCacheGlobalIntervalDAY       PaymentProductCacheGlobalInterval = "DAY"
	PaymentProductCacheGlobalIntervalWEEK      PaymentProductCacheGlobalInterval = "WEEK"
	PaymentProductCacheGlobalIntervalMONTH     PaymentProductCacheGlobalInterval = "MONTH"
	PaymentProductCacheGlobalIntervalONCE      PaymentProductCacheGlobalInterval = "ONCE"
	PaymentProductCacheGlobalIntervalUNLIMITED PaymentProductCacheGlobalInterval = "UNLIMITED"
)

func (e *PaymentProductCacheGlobalInterval) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProductCacheGlobalInterval(s)
	case string:
		*e = PaymentProductCacheGlobalInterval(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProductCacheGlobalInterval: %T", src)
	}
	return nil
}

type NullPaymentProductCacheGlobalInterval struct {
	PaymentProductCacheGlobalInterval PaymentProductCacheGlobalInterval `json:"payment_product_cache_global_interval"`
	Valid                             bool                              `json:"valid"` // Valid is true if PaymentProductCacheGlobalInterval is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProductCacheGlobalInterval) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProductCacheGlobalInterval, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProductCacheGlobalInterval.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProductCacheGlobalInterval) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProductCacheGlobalInterval), nil
}

type PaymentProductCacheQuantityMode string

const (
	PaymentProductCacheQuantityModeFixed    PaymentProductCacheQuantityMode = "fixed"
	PaymentProductCacheQuantityModeFlexible PaymentProductCacheQuantityMode = "flexible"
)

func (e *PaymentProductCacheQuantityMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProductCacheQuantityMode(s)
	case string:
		*e = PaymentProductCacheQuantityMode(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProductCacheQuantityMode: %T", src)
	}
	return nil
}

type NullPaymentProductCacheQuantityMode struct {
	PaymentProductCacheQuantityMode PaymentProductCacheQuantityMode `json:"payment_product_cache_quantity_mode"`
	Valid                           bool                            `json:"valid"` // Valid is true if PaymentProductCacheQuantityMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProductCacheQuantityMode) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProductCacheQuantityMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProductCacheQuantityMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProductCacheQuantityMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProductCacheQuantityMode), nil
}

type PaymentProductCacheRewardType string

const (
	PaymentProductCacheRewardTypeQuantity PaymentProductCacheRewardType = "quantity"
	PaymentProductCacheRewardTypeDuration PaymentProductCacheRewardType = "duration"
)

func (e *PaymentProductCacheRewardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProductCacheRewardType(s)
	case string:
		*e = PaymentProductCacheRewardType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProductCacheRewardType: %T", src)
	}
	return nil
}

type NullPaymentProductCacheRewardType struct {
	PaymentProductCacheRewardType PaymentProductCacheRewardType `json:"payment_product_cache_reward_type"`
	Valid                         bool                          `json:"valid"` // Valid is true if PaymentProductCacheRewardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProductCacheRewardType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProductCacheRewardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProductCacheRewardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProductCacheRewardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProductCacheRewardType), nil
}

type PaymentProductCacheUserInterval string

const (
	PaymentProductCacheUserIntervalSECOND    PaymentProductCacheUserInterval = "SECOND"
	PaymentProductCacheUserIntervalMINUTE    PaymentProductCacheUserInterval = "MINUTE"
	PaymentProductCacheUserIntervalHOUR      PaymentProductCacheUserInterval = "HOUR"
	PaymentProductCacheUserIntervalDAY       PaymentProductCacheUserInterval = "DAY"
	PaymentProductCacheUserIntervalWEEK      PaymentProductCacheUserInterval = "WEEK"
	PaymentProductCacheUserIntervalMONTH     PaymentProductCacheUserInterval = "MONTH"
	PaymentProductCacheUserIntervalONCE      PaymentProductCacheUserInterval = "ONCE"
	PaymentProductCacheUserIntervalUNLIMITED PaymentProductCacheUserInterval = "UNLIMITED"
)

func (e *PaymentProductCacheUserInterval) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProductCacheUserInterval(s)
	case string:
		*e = PaymentProductCacheUserInterval(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProductCacheUserInterval: %T", src)
	}
	return nil
}

type NullPaymentProductCacheUserInterval struct {
	PaymentProductCacheUserInterval PaymentProductCacheUserInterval `json:"payment_product_cache_user_interval"`
	Valid                           bool                            `json:"valid"` // Valid is true if PaymentProductCacheUserInterval is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProductCacheUserInterval) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProductCacheUserInterval, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProductCacheUserInterval.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProductCacheUserInterval) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProductCacheUserInterval), nil
}

type PaymentProductGlobalInterval string

const (
	PaymentProductGlobalIntervalSECOND    PaymentProductGlobalInterval = "SECOND"
	PaymentProductGlobalIntervalMINUTE    PaymentProductGlobalInterval = "MINUTE"
	PaymentProductGlobalIntervalHOUR      PaymentProductGlobalInterval = "HOUR"
	PaymentProductGlobalIntervalDAY       PaymentProductGlobalInterval = "DAY"
	PaymentProductGlobalIntervalWEEK      PaymentProductGlobalInterval = "WEEK"
	PaymentProductGlobalIntervalMONTH     PaymentProductGlobalInterval = "MONTH"
	PaymentProductGlobalIntervalONCE      PaymentProductGlobalInterval = "ONCE"
	PaymentProductGlobalIntervalUNLIMITED PaymentProductGlobalInterval = "UNLIMITED"
)

func (e *PaymentProductGlobalInterval) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProductGlobalInterval(s)
	case string:
		*e = PaymentProductGlobalInterval(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProductGlobalInterval: %T", src)
	}
	return nil
}

type NullPaymentProductGlobalInterval struct {
	PaymentProductGlobalInterval PaymentProductGlobalInterval `json:"payment_product_global_interval"`
	Valid                        bool                         `json:"valid"` // Valid is true if PaymentProductGlobalInterval is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProductGlobalInterval) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProductGlobalInterval, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProductGlobalInterval.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProductGlobalInterval) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProductGlobalInterval), nil
}

type PaymentProductItemDurationUnit string

const (
	PaymentProductItemDurationUnitSecond PaymentProductItemDurationUnit = "second"
	PaymentProductItemDurationUnitMinute PaymentProductItemDurationUnit = "minute"
	PaymentProductItemDurationUnitHour   PaymentProductItemDurationUnit = "hour"
	PaymentProductItemDurationUnitDay    PaymentProductItemDurationUnit = "day"
	PaymentProductItemDurationUnitWeek   PaymentProductItemDurationUnit = "week"
	PaymentProductItemDurationUnitMonth  PaymentProductItemDurationUnit = "month"
	PaymentProductItemDurationUnitYear   PaymentProductItemDurationUnit = "year"
)

func (e *PaymentProductItemDurationUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProductItemDurationUnit(s)
	case string:
		*e = PaymentProductItemDurationUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProductItemDurationUnit: %T", src)
	}
	return nil
}

type NullPaymentProductItemDurationUnit struct {
	PaymentProductItemDurationUnit PaymentProductItemDurationUnit `json:"payment_product_item_duration_unit"`
	Valid                          bool                           `json:"valid"` // Valid is true if PaymentProductItemDurationUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProductItemDurationUnit) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProductItemDurationUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProductItemDurationUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProductItemDurationUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProductItemDurationUnit), nil
}

type PaymentProductItemRewardType string

const (
	PaymentProductItemRewardTypeQuantity PaymentProductItemRewardType = "quantity"
	PaymentProductItemRewardTypeDuration PaymentProductItemRewardType = "duration"
)

func (e *PaymentProductItemRewardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProductItemRewardType(s)
	case string:
		*e = PaymentProductItemRewardType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProductItemRewardType: %T", src)
	}
	return nil
}

type NullPaymentProductItemRewardType struct {
	PaymentProductItemRewardType PaymentProductItemRewardType `json:"payment_product_item_reward_type"`
	Valid                        bool                         `json:"valid"` // Valid is true if PaymentProductItemRewardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProductItemRewardType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProductItemRewardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProductItemRewardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProductItemRewardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProductItemRewardType), nil
}

type PaymentProductLimitCounterCounterScope string

const (
	PaymentProductLimitCounterCounterScopeGlobal PaymentProductLimitCounterCounterScope = "global"
	PaymentProductLimitCounterCounterScopeUser   PaymentProductLimitCounterCounterScope = "user"
)

func (e *PaymentProductLimitCounterCounterScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProductLimitCounterCounterScope(s)
	case string:
		*e = PaymentProductLimitCounterCounterScope(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProductLimitCounterCounterScope: %T", src)
	}
	return nil
}

type NullPaymentProductLimitCounterCounterScope struct {
	PaymentProductLimitCounterCounterScope PaymentProductLimitCounterCounterScope `json:"payment_product_limit_counter_counter_scope"`
	Valid                                  bool                                   `json:"valid"` // Valid is true if PaymentProductLimitCounterCounterScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProductLimitCounterCounterScope) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProductLimitCounterCounterScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProductLimitCounterCounterScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProductLimitCounterCounterScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProductLimitCounterCounterScope), nil
}

type PaymentProductQuantityMode string

const (
	PaymentProductQuantityModeFixed    PaymentProductQuantityMode = "fixed"
	PaymentProductQuantityModeFlexible PaymentProductQuantityMode = "flexible"
)

func (e *PaymentProductQuantityMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProductQuantityMode(s)
	case string:
		*e = PaymentProductQuantityMode(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProductQuantityMode: %T", src)
	}
	return nil
}

type NullPaymentProductQuantityMode struct {
	PaymentProductQuantityMode PaymentProductQuantityMode `json:"payment_product_quantity_mode"`
	Valid                      bool                       `json:"valid"` // Valid is true if PaymentProductQuantityMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProductQuantityMode) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProductQuantityMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProductQuantityMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProductQuantityMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProductQuantityMode), nil
}

type PaymentProductUserInterval string

const (
	PaymentProductUserIntervalSECOND    PaymentProductUserInterval = "SECOND"
	PaymentProductUserIntervalMINUTE    PaymentProductUserInterval = "MINUTE"
	PaymentProductUserIntervalHOUR      PaymentProductUserInterval = "HOUR"
	PaymentProductUserIntervalDAY       PaymentProductUserInterval = "DAY"
	PaymentProductUserIntervalWEEK      PaymentProductUserInterval = "WEEK"
	PaymentProductUserIntervalMONTH     PaymentProductUserInterval = "MONTH"
	PaymentProductUserIntervalONCE      PaymentProductUserInterval = "ONCE"
	PaymentProductUserIntervalUNLIMITED PaymentProductUserInterval = "UNLIMITED"
)

func (e *PaymentProductUserInterval) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProductUserInterval(s)
	case string:
		*e = PaymentProductUserInterval(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProductUserInterval: %T", src)
	}
	return nil
}

type NullPaymentProductUserInterval struct {
	PaymentProductUserInterval PaymentProductUserInterval `json:"payment_product_user_interval"`
	Valid                      bool                       `json:"valid"` // Valid is true if PaymentProductUserInterval is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProductUserInterval) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProductUserInterval, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProductUserInterval.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProductUserInterval) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProductUserInterval), nil
}

type PaymentProviderProviderKind string

const (
	PaymentProviderProviderKindPlatformInternal PaymentProviderProviderKind = "platform_internal"
	PaymentProviderProviderKindFiatGateway      PaymentProviderProviderKind = "fiat_gateway"
	PaymentProviderProviderKindCryptoChain      PaymentProviderProviderKind = "crypto_chain"
)

func (e *PaymentProviderProviderKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProviderProviderKind(s)
	case string:
		*e = PaymentProviderProviderKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProviderProviderKind: %T", src)
	}
	return nil
}

type NullPaymentProviderProviderKind struct {
	PaymentProviderProviderKind PaymentProviderProviderKind `json:"payment_provider_provider_kind"`
	Valid                       bool                        `json:"valid"` // Valid is true if PaymentProviderProviderKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProviderProviderKind) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProviderProviderKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProviderProviderKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProviderProviderKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProviderProviderKind), nil
}

type PaymentProviderTransactionStatus string

const (
	PaymentProviderTransactionStatusNew     PaymentProviderTransactionStatus = "new"
	PaymentProviderTransactionStatusMatched PaymentProviderTransactionStatus = "matched"
	PaymentProviderTransactionStatusIgnored PaymentProviderTransactionStatus = "ignored"
	PaymentProviderTransactionStatusFailed  PaymentProviderTransactionStatus = "failed"
)

func (e *PaymentProviderTransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProviderTransactionStatus(s)
	case string:
		*e = PaymentProviderTransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProviderTransactionStatus: %T", src)
	}
	return nil
}

type NullPaymentProviderTransactionStatus struct {
	PaymentProviderTransactionStatus PaymentProviderTransactionStatus `json:"payment_provider_transaction_status"`
	Valid                            bool                             `json:"valid"` // Valid is true if PaymentProviderTransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProviderTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProviderTransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProviderTransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProviderTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProviderTransactionStatus), nil
}

type PaymentPurchaseKeyStatus string

const (
	PaymentPurchaseKeyStatusActive   PaymentPurchaseKeyStatus = "active"
	PaymentPurchaseKeyStatusUsed     PaymentPurchaseKeyStatus = "used"
	PaymentPurchaseKeyStatusCanceled PaymentPurchaseKeyStatus = "canceled"
	PaymentPurchaseKeyStatusExpired  PaymentPurchaseKeyStatus = "expired"
)

func (e *PaymentPurchaseKeyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentPurchaseKeyStatus(s)
	case string:
		*e = PaymentPurchaseKeyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentPurchaseKeyStatus: %T", src)
	}
	return nil
}

type NullPaymentPurchaseKeyStatus struct {
	PaymentPurchaseKeyStatus PaymentPurchaseKeyStatus `json:"payment_purchase_key_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if PaymentPurchaseKeyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentPurchaseKeyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentPurchaseKeyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentPurchaseKeyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentPurchaseKeyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentPurchaseKeyStatus), nil
}

type PaymentRefundStatus string

const (
	PaymentRefundStatusCreated   PaymentRefundStatus = "created"
	PaymentRefundStatusPending   PaymentRefundStatus = "pending"
	PaymentRefundStatusSucceeded PaymentRefundStatus = "succeeded"
	PaymentRefundStatusCanceled  PaymentRefundStatus = "canceled"
	PaymentRefundStatusFailed    PaymentRefundStatus = "failed"
)

func (e *PaymentRefundStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentRefundStatus(s)
	case string:
		*e = PaymentRefundStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentRefundStatus: %T", src)
	}
	return nil
}

type NullPaymentRefundStatus struct {
	PaymentRefundStatus PaymentRefundStatus `json:"payment_refund_status"`
	Valid               bool                `json:"valid"` // Valid is true if PaymentRefundStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentRefundStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentRefundStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentRefundStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentRefundStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentRefundStatus), nil
}

type PaymentStatsEventEventType string

const (
	PaymentStatsEventEventTypePurchase PaymentStatsEventEventType = "purchase"
	PaymentStatsEventEventTypeRefund   PaymentStatsEventEventType = "refund"
)

func (e *PaymentStatsEventEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatsEventEventType(s)
	case string:
		*e = PaymentStatsEventEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatsEventEventType: %T", src)
	}
	return nil
}

type NullPaymentStatsEventEventType struct {
	PaymentStatsEventEventType PaymentStatsEventEventType `json:"payment_stats_event_event_type"`
	Valid                      bool                       `json:"valid"` // Valid is true if PaymentStatsEventEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatsEventEventType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatsEventEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatsEventEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatsEventEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatsEventEventType), nil
}

type PaymentStatsOrderEventEventType string

const (
	PaymentStatsOrderEventEventTypeCreated PaymentStatsOrderEventEventType = "created"
	PaymentStatsOrderEventEventTypeStatus  PaymentStatsOrderEventEventType = "status"
)

func (e *PaymentStatsOrderEventEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatsOrderEventEventType(s)
	case string:
		*e = PaymentStatsOrderEventEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatsOrderEventEventType: %T", src)
	}
	return nil
}

type NullPaymentStatsOrderEventEventType struct {
	PaymentStatsOrderEventEventType PaymentStatsOrderEventEventType `json:"payment_stats_order_event_event_type"`
	Valid                           bool                            `json:"valid"` // Valid is true if PaymentStatsOrderEventEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatsOrderEventEventType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatsOrderEventEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatsOrderEventEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatsOrderEventEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatsOrderEventEventType), nil
}

type PaymentStatsOrderEventOrderStatus string

const (
	PaymentStatsOrderEventOrderStatusDraft          PaymentStatsOrderEventOrderStatus = "draft"
	PaymentStatsOrderEventOrderStatusPendingPayment PaymentStatsOrderEventOrderStatus = "pending_payment"
	PaymentStatsOrderEventOrderStatusPaid           PaymentStatsOrderEventOrderStatus = "paid"
	PaymentStatsOrderEventOrderStatusFulfilled      PaymentStatsOrderEventOrderStatus = "fulfilled"
	PaymentStatsOrderEventOrderStatusCanceled       PaymentStatsOrderEventOrderStatus = "canceled"
	PaymentStatsOrderEventOrderStatusExpired        PaymentStatsOrderEventOrderStatus = "expired"
	PaymentStatsOrderEventOrderStatusRefunded       PaymentStatsOrderEventOrderStatus = "refunded"
	PaymentStatsOrderEventOrderStatusChargebacked   PaymentStatsOrderEventOrderStatus = "chargebacked"
	PaymentStatsOrderEventOrderStatusFailed         PaymentStatsOrderEventOrderStatus = "failed"
)

func (e *PaymentStatsOrderEventOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatsOrderEventOrderStatus(s)
	case string:
		*e = PaymentStatsOrderEventOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatsOrderEventOrderStatus: %T", src)
	}
	return nil
}

type NullPaymentStatsOrderEventOrderStatus struct {
	PaymentStatsOrderEventOrderStatus PaymentStatsOrderEventOrderStatus `json:"payment_stats_order_event_order_status"`
	Valid                             bool                              `json:"valid"` // Valid is true if PaymentStatsOrderEventOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatsOrderEventOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatsOrderEventOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatsOrderEventOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatsOrderEventOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatsOrderEventOrderStatus), nil
}

type PaymentSubscriptionStatus string

const (
	PaymentSubscriptionStatusActive   PaymentSubscriptionStatus = "active"
	PaymentSubscriptionStatusCanceled PaymentSubscriptionStatus = "canceled"
	PaymentSubscriptionStatusRefunded PaymentSubscriptionStatus = "refunded"
	PaymentSubscriptionStatusExpired  PaymentSubscriptionStatus = "expired"
)

func (e *PaymentSubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentSubscriptionStatus(s)
	case string:
		*e = PaymentSubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentSubscriptionStatus: %T", src)
	}
	return nil
}

type NullPaymentSubscriptionStatus struct {
	PaymentSubscriptionStatus PaymentSubscriptionStatus `json:"payment_subscription_status"`
	Valid                     bool                      `json:"valid"` // Valid is true if PaymentSubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentSubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentSubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentSubscriptionStatus), nil
}

type PaymentAsset struct {
	Code            string                `json:"code"`
	Title           string                `json:"title"`
	AssetKind       PaymentAssetAssetKind `json:"asset_kind"`
	Scale           int16                 `json:"scale"`
	Chain           sql.NullString        `json:"chain"`
	Network         sql.NullString        `json:"network"`
	ContractAddress sql.NullString        `json:"contract_address"`
	IsActive        bool                  `json:"is_active"`
	CreatedAt       time.Time             `json:"created_at"`
	UpdatedAt       time.Time             `json:"updated_at"`
}

type PaymentAssetRate struct {
	AssetCode              string         `json:"asset_code"`
	ReferenceAssetCode     string         `json:"reference_asset_code"`
	ReferencePerAssetMinor int64          `json:"reference_per_asset_minor"`
	Source                 string         `json:"source"`
	ObservedAt             time.Time      `json:"observed_at"`
	AutoUpdateEnabled      bool           `json:"auto_update_enabled"`
	AutoUpdateSource       sql.NullString `json:"auto_update_source"`
	SourceChainID          sql.NullString `json:"source_chain_id"`
	SourceTokenAddress     sql.NullString `json:"source_token_address"`
	LastAttemptAt          sql.NullTime   `json:"last_attempt_at"`
	LastError              sql.NullString `json:"last_error"`
	LeaseOwner             sql.NullString `json:"lease_owner"`
	LeaseUntil             sql.NullTime   `json:"lease_until"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

type PaymentAttempt struct {
	ID                     int64                `json:"id"`
	WorkspaceID            string               `json:"workspace_id"`
	OrderID                int64                `json:"order_id"`
	ProviderCode           string               `json:"provider_code"`
	AssetCode              string               `json:"asset_code"`
	AmountMinor            int64                `json:"amount_minor"`
	Status                 PaymentAttemptStatus `json:"status"`
	ProviderPaymentID      sql.NullString       `json:"provider_payment_id"`
	ProviderInvoiceID      sql.NullString       `json:"provider_invoice_id"`
	ProviderChargeID       sql.NullString       `json:"provider_charge_id"`
	ProviderSubscriptionID sql.NullString       `json:"provider_subscription_id"`
	IdempotencyKey         sql.NullString       `json:"idempotency_key"`
	RequestFingerprint     string               `json:"request_fingerprint"`
	ConfirmationUrl        sql.NullString       `json:"confirmation_url"`
	ReturnUrl              sql.NullString       `json:"return_url"`
	ExpiresAt              sql.NullTime         `json:"expires_at"`
	CreatedAt              time.Time            `json:"created_at"`
	UpdatedAt              time.Time            `json:"updated_at"`
}

type PaymentEvent struct {
	ID                int64                        `json:"id"`
	WorkspaceID       string                       `json:"workspace_id"`
	ProviderCode      string                       `json:"provider_code"`
	AttemptID         sql.NullInt64                `json:"attempt_id"`
	OrderID           sql.NullInt64                `json:"order_id"`
	ProviderEventID   sql.NullString               `json:"provider_event_id"`
	ProviderPaymentID sql.NullString               `json:"provider_payment_id"`
	EventType         string                       `json:"event_type"`
	EventStatus       sql.NullString               `json:"event_status"`
	PayloadHash       string                       `json:"payload_hash"`
	SignatureValid    sql.NullBool                 `json:"signature_valid"`
	ProcessingStatus  PaymentEventProcessingStatus `json:"processing_status"`
	ProcessingError   sql.NullString               `json:"processing_error"`
	ReceivedAt        time.Time                    `json:"received_at"`
	ProcessedAt       sql.NullTime                 `json:"processed_at"`
}

type PaymentFulfillment struct {
	ID             int64                    `json:"id"`
	OrderID        int64                    `json:"order_id"`
	AttemptID      int64                    `json:"attempt_id"`
	InternalUserID sql.NullInt64            `json:"internal_user_id"`
	Status         PaymentFulfillmentStatus `json:"status"`
	Error          sql.NullString           `json:"error"`
	CreatedAt      time.Time                `json:"created_at"`
	UpdatedAt      time.Time                `json:"updated_at"`
	FulfilledAt    sql.NullTime             `json:"fulfilled_at"`
	RevokedAt      sql.NullTime             `json:"revoked_at"`
}

type PaymentFulfillmentItem struct {
	ID            int64                                  `json:"id"`
	FulfillmentID int64                                  `json:"fulfillment_id"`
	WorkspaceID   string                                 `json:"workspace_id"`
	ItemID        string                                 `json:"item_id"`
	RewardType    PaymentFulfillmentItemRewardType       `json:"reward_type"`
	Quantity      int64                                  `json:"quantity"`
	Scale         int16                                  `json:"scale"`
	DurationUnit  NullPaymentFulfillmentItemDurationUnit `json:"duration_unit"`
	CreatedAt     time.Time                              `json:"created_at"`
}

type PaymentLocalization struct {
	ID              int64     `json:"id"`
	WorkspaceID     string    `json:"workspace_id"`
	Locale          string    `json:"locale"`
	LocalizationKey string    `json:"localization_key"`
	Value           string    `json:"value"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type PaymentOrder struct {
	ID                          int64              `json:"id"`
	PublicID                    string             `json:"public_id"`
	WorkspaceID                 string             `json:"workspace_id"`
	AppID                       int64              `json:"app_id"`
	PlatformID                  int64              `json:"platform_id"`
	PlatformUserID              string             `json:"platform_user_id"`
	InternalUserID              sql.NullInt64      `json:"internal_user_id"`
	PayerPlatformID             sql.NullInt64      `json:"payer_platform_id"`
	PayerPlatformUserID         sql.NullString     `json:"payer_platform_user_id"`
	PayerInternalUserID         sql.NullInt64      `json:"payer_internal_user_id"`
	PurchaseKeyID               sql.NullInt64      `json:"purchase_key_id"`
	ProductID                   string             `json:"product_id"`
	Quantity                    int64              `json:"quantity"`
	PriceID                     int64              `json:"price_id"`
	AssetCode                   string             `json:"asset_code"`
	Locale                      string             `json:"locale"`
	ListAmountMinor             int64              `json:"list_amount_minor"`
	DiscountAmountMinor         int64              `json:"discount_amount_minor"`
	PayableAmountMinor          int64              `json:"payable_amount_minor"`
	Status                      PaymentOrderStatus `json:"status"`
	ReservedUntil               sql.NullTime       `json:"reserved_until"`
	GlobalLimitSnapshot         int32              `json:"global_limit_snapshot"`
	GlobalIntervalSnapshot      string             `json:"global_interval_snapshot"`
	GlobalIntervalCountSnapshot int32              `json:"global_interval_count_snapshot"`
	GlobalWindowStartSnapshot   sql.NullTime       `json:"global_window_start_snapshot"`
	GlobalWindowEndSnapshot     sql.NullTime       `json:"global_window_end_snapshot"`
	UserLimitSnapshot           int32              `json:"user_limit_snapshot"`
	UserIntervalSnapshot        string             `json:"user_interval_snapshot"`
	UserIntervalCountSnapshot   int32              `json:"user_interval_count_snapshot"`
	UserWindowStartSnapshot     sql.NullTime       `json:"user_window_start_snapshot"`
	UserWindowEndSnapshot       sql.NullTime       `json:"user_window_end_snapshot"`
	PaidAt                      sql.NullTime       `json:"paid_at"`
	FulfilledAt                 sql.NullTime       `json:"fulfilled_at"`
	CanceledAt                  sql.NullTime       `json:"canceled_at"`
	ExpiresAt                   sql.NullTime       `json:"expires_at"`
	CreatedAt                   time.Time          `json:"created_at"`
	UpdatedAt                   time.Time          `json:"updated_at"`
}

type PaymentOrderItem struct {
	OrderID      int64                            `json:"order_id"`
	WorkspaceID  string                           `json:"workspace_id"`
	ItemID       string                           `json:"item_id"`
	RewardType   PaymentOrderItemRewardType       `json:"reward_type"`
	Quantity     int64                            `json:"quantity"`
	Scale        int16                            `json:"scale"`
	DurationUnit NullPaymentOrderItemDurationUnit `json:"duration_unit"`
	CreatedAt    time.Time                        `json:"created_at"`
}

type PaymentPaidOrderIndex struct {
	OrderID             int64                       `json:"order_id"`
	WorkspaceID         string                      `json:"workspace_id"`
	AppID               int64                       `json:"app_id"`
	PlatformID          int64                       `json:"platform_id"`
	PlatformUserID      string                      `json:"platform_user_id"`
	InternalUserID      sql.NullInt64               `json:"internal_user_id"`
	PayerPlatformID     sql.NullInt64               `json:"payer_platform_id"`
	PayerPlatformUserID sql.NullString              `json:"payer_platform_user_id"`
	PayerInternalUserID sql.NullInt64               `json:"payer_internal_user_id"`
	PurchaseKeyID       sql.NullInt64               `json:"purchase_key_id"`
	ProductID           string                      `json:"product_id"`
	Quantity            int64                       `json:"quantity"`
	PriceID             int64                       `json:"price_id"`
	AssetCode           string                      `json:"asset_code"`
	Locale              string                      `json:"locale"`
	ListAmountMinor     int64                       `json:"list_amount_minor"`
	DiscountAmountMinor int64                       `json:"discount_amount_minor"`
	PayableAmountMinor  int64                       `json:"payable_amount_minor"`
	Status              PaymentPaidOrderIndexStatus `json:"status"`
	PaidAt              time.Time                   `json:"paid_at"`
	FulfilledAt         sql.NullTime                `json:"fulfilled_at"`
	CreatedAt           time.Time                   `json:"created_at"`
	UpdatedAt           time.Time                   `json:"updated_at"`
}

type PaymentPrice struct {
	ID                           int64                   `json:"id"`
	WorkspaceID                  string                  `json:"workspace_id"`
	ProductID                    string                  `json:"product_id"`
	AssetCode                    string                  `json:"asset_code"`
	ListAmountMinor              int64                   `json:"list_amount_minor"`
	DiscountAmountMinor          int64                   `json:"discount_amount_minor"`
	PricingMode                  PaymentPricePricingMode `json:"pricing_mode"`
	ReferenceAssetCode           sql.NullString          `json:"reference_asset_code"`
	ReferenceListAmountMinor     sql.NullInt64           `json:"reference_list_amount_minor"`
	ReferenceDiscountAmountMinor sql.NullInt64           `json:"reference_discount_amount_minor"`
	Coefficient                  sql.NullString          `json:"coefficient"`
	IsPromotion                  bool                    `json:"is_promotion"`
	StartsAt                     time.Time               `json:"starts_at"`
	EndsAt                       time.Time               `json:"ends_at"`
	CreatedAt                    time.Time               `json:"created_at"`
	UpdatedAt                    time.Time               `json:"updated_at"`
}

type PaymentProduct struct {
	WorkspaceID          string                       `json:"workspace_id"`
	ID                   string                       `json:"id"`
	GroupCode            sql.NullString               `json:"group_code"`
	TitleKey             string                       `json:"title_key"`
	DescriptionKey       sql.NullString               `json:"description_key"`
	Target               pqtype.NullRawMessage        `json:"target"`
	ImageUrl             sql.NullString               `json:"image_url"`
	LinkUrl              sql.NullString               `json:"link_url"`
	SizeLabel            sql.NullString               `json:"size_label"`
	PeriodSeconds        sql.NullInt64                `json:"period_seconds"`
	TrialDurationSeconds sql.NullInt64                `json:"trial_duration_seconds"`
	QuantityMode         PaymentProductQuantityMode   `json:"quantity_mode"`
	Position             int32                        `json:"position"`
	GlobalLimit          int32                        `json:"global_limit"`
	GlobalInterval       PaymentProductGlobalInterval `json:"global_interval"`
	GlobalIntervalCount  int32                        `json:"global_interval_count"`
	UserLimit            int32                        `json:"user_limit"`
	UserInterval         PaymentProductUserInterval   `json:"user_interval"`
	UserIntervalCount    int32                        `json:"user_interval_count"`
	AvailableFrom        time.Time                    `json:"available_from"`
	AvailableUntil       time.Time                    `json:"available_until"`
	IsVisible            bool                         `json:"is_visible"`
	IsClosed             bool                         `json:"is_closed"`
	CreatedAt            time.Time                    `json:"created_at"`
	UpdatedAt            time.Time                    `json:"updated_at"`
}

type PaymentProductCache struct {
	WorkspaceID          string                              `json:"workspace_id"`
	ProductID            string                              `json:"product_id"`
	AssetCode            string                              `json:"asset_code"`
	Locale               string                              `json:"locale"`
	PriceID              int64                               `json:"price_id"`
	ItemID               string                              `json:"item_id"`
	LinkUrl              sql.NullString                      `json:"link_url"`
	SizeLabel            sql.NullString                      `json:"size_label"`
	GroupCode            sql.NullString                      `json:"group_code"`
	Target               pqtype.NullRawMessage               `json:"target"`
	ProductTitle         string                              `json:"product_title"`
	ProductDescription   string                              `json:"product_description"`
	ImageUrl             sql.NullString                      `json:"image_url"`
	PeriodSeconds        sql.NullInt64                       `json:"period_seconds"`
	TrialDurationSeconds sql.NullInt64                       `json:"trial_duration_seconds"`
	QuantityMode         PaymentProductCacheQuantityMode     `json:"quantity_mode"`
	ProductPosition      int32                               `json:"product_position"`
	GlobalLimit          int32                               `json:"global_limit"`
	GlobalInterval       PaymentProductCacheGlobalInterval   `json:"global_interval"`
	GlobalIntervalCount  int32                               `json:"global_interval_count"`
	UserLimit            int32                               `json:"user_limit"`
	UserInterval         PaymentProductCacheUserInterval     `json:"user_interval"`
	UserIntervalCount    int32                               `json:"user_interval_count"`
	IsVisible            bool                                `json:"is_visible"`
	IsClosed             bool                                `json:"is_closed"`
	AvailableFrom        time.Time                           `json:"available_from"`
	AvailableUntil       time.Time                           `json:"available_until"`
	ListAmountMinor      int64                               `json:"list_amount_minor"`
	DiscountAmountMinor  int64                               `json:"discount_amount_minor"`
	IsPromotion          bool                                `json:"is_promotion"`
	PriceStartsAt        time.Time                           `json:"price_starts_at"`
	PriceEndsAt          time.Time                           `json:"price_ends_at"`
	ItemQuantity         int64                               `json:"item_quantity"`
	ItemScale            int16                               `json:"item_scale"`
	RewardType           PaymentProductCacheRewardType       `json:"reward_type"`
	DurationUnit         NullPaymentProductCacheDurationUnit `json:"duration_unit"`
	UpdatedAt            time.Time                           `json:"updated_at"`
}

type PaymentProductGroup struct {
	WorkspaceID    string         `json:"workspace_id"`
	Code           string         `json:"code"`
	TitleKey       sql.NullString `json:"title_key"`
	DescriptionKey sql.NullString `json:"description_key"`
	Position       int32          `json:"position"`
	IsActive       bool           `json:"is_active"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type PaymentProductItem struct {
	ID           int64                              `json:"id"`
	WorkspaceID  string                             `json:"workspace_id"`
	ProductID    string                             `json:"product_id"`
	ItemID       string                             `json:"item_id"`
	RewardType   PaymentProductItemRewardType       `json:"reward_type"`
	Quantity     int64                              `json:"quantity"`
	Scale        int16                              `json:"scale"`
	DurationUnit NullPaymentProductItemDurationUnit `json:"duration_unit"`
	CreatedAt    time.Time                          `json:"created_at"`
	UpdatedAt    time.Time                          `json:"updated_at"`
}

type PaymentProductLimitCounter struct {
	WorkspaceID    string                                 `json:"workspace_id"`
	PlatformID     int64                                  `json:"platform_id"`
	ProductID      string                                 `json:"product_id"`
	CounterScope   PaymentProductLimitCounterCounterScope `json:"counter_scope"`
	PlatformUserID string                                 `json:"platform_user_id"`
	WindowStart    time.Time                              `json:"window_start"`
	WindowEnd      time.Time                              `json:"window_end"`
	PaidCount      int64                                  `json:"paid_count"`
	ReservedCount  int64                                  `json:"reserved_count"`
	UpdatedAt      time.Time                              `json:"updated_at"`
}

type PaymentProvider struct {
	Code             string                      `json:"code"`
	Title            string                      `json:"title"`
	ProviderKind     PaymentProviderProviderKind `json:"provider_kind"`
	SupportsCreate   bool                        `json:"supports_create"`
	SupportsRedirect bool                        `json:"supports_redirect"`
	SupportsWebhook  bool                        `json:"supports_webhook"`
	SupportsRefund   bool                        `json:"supports_refund"`
	IsActive         bool                        `json:"is_active"`
	CreatedAt        time.Time                   `json:"created_at"`
	UpdatedAt        time.Time                   `json:"updated_at"`
}

type PaymentProviderAsset struct {
	ProviderCode    string         `json:"provider_code"`
	AssetCode       string         `json:"asset_code"`
	MinAmountMinor  sql.NullInt64  `json:"min_amount_minor"`
	MaxAmountMinor  sql.NullInt64  `json:"max_amount_minor"`
	MerchantAccount sql.NullString `json:"merchant_account"`
	IsActive        bool           `json:"is_active"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type PaymentProviderCursor struct {
	WorkspaceID    string    `json:"workspace_id"`
	ProviderCode   string    `json:"provider_code"`
	Network        string    `json:"network"`
	SourceKey      string    `json:"source_key"`
	CursorValue    string    `json:"cursor_value"`
	CursorSequence int64     `json:"cursor_sequence"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type PaymentProviderTransaction struct {
	ID                    int64                            `json:"id"`
	WorkspaceID           string                           `json:"workspace_id"`
	ProviderCode          string                           `json:"provider_code"`
	Network               string                           `json:"network"`
	SourceKey             string                           `json:"source_key"`
	AssetCode             string                           `json:"asset_code"`
	ExternalTransactionID string                           `json:"external_transaction_id"`
	SequenceNumber        int64                            `json:"sequence_number"`
	SourceAddress         string                           `json:"source_address"`
	DestinationAddress    string                           `json:"destination_address"`
	AmountMinor           int64                            `json:"amount_minor"`
	PaymentReference      string                           `json:"payment_reference"`
	SenderReference       sql.NullString                   `json:"sender_reference"`
	OrderID               sql.NullInt64                    `json:"order_id"`
	AttemptID             sql.NullInt64                    `json:"attempt_id"`
	Status                PaymentProviderTransactionStatus `json:"status"`
	Error                 sql.NullString                   `json:"error"`
	OccurredAt            time.Time                        `json:"occurred_at"`
	CreatedAt             time.Time                        `json:"created_at"`
}

type PaymentPurchaseKey struct {
	ID             int64                    `json:"id"`
	WorkspaceID    string                   `json:"workspace_id"`
	KeyHash        string                   `json:"key_hash"`
	AppID          int64                    `json:"app_id"`
	PlatformID     int64                    `json:"platform_id"`
	PlatformUserID string                   `json:"platform_user_id"`
	InternalUserID sql.NullInt64            `json:"internal_user_id"`
	ProductID      string                   `json:"product_id"`
	Status         PaymentPurchaseKeyStatus `json:"status"`
	MaxUses        int32                    `json:"max_uses"`
	UsedCount      int32                    `json:"used_count"`
	ReservedCount  int32                    `json:"reserved_count"`
	ExpiresAt      sql.NullTime             `json:"expires_at"`
	CreatedAt      time.Time                `json:"created_at"`
	UpdatedAt      time.Time                `json:"updated_at"`
}

type PaymentRefund struct {
	ID               int64               `json:"id"`
	WorkspaceID      string              `json:"workspace_id"`
	OrderID          int64               `json:"order_id"`
	AttemptID        int64               `json:"attempt_id"`
	ProviderCode     string              `json:"provider_code"`
	IdempotencyKey   sql.NullString      `json:"idempotency_key"`
	ProviderRefundID sql.NullString      `json:"provider_refund_id"`
	AmountMinor      int64               `json:"amount_minor"`
	AssetCode        string              `json:"asset_code"`
	Status           PaymentRefundStatus `json:"status"`
	Reason           sql.NullString      `json:"reason"`
	CreatedAt        time.Time           `json:"created_at"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

type PaymentStatsDaily struct {
	WorkspaceID       string    `json:"workspace_id"`
	ProductID         string    `json:"product_id"`
	AssetCode         string    `json:"asset_code"`
	StatsDate         time.Time `json:"stats_date"`
	PurchaseCount     int64     `json:"purchase_count"`
	PurchaseQuantity  int64     `json:"purchase_quantity"`
	UniqueBuyers      int64     `json:"unique_buyers"`
	GrossAmountMinor  int64     `json:"gross_amount_minor"`
	RefundCount       int64     `json:"refund_count"`
	RefundAmountMinor int64     `json:"refund_amount_minor"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type PaymentStatsDailyBuyer struct {
	WorkspaceID    string    `json:"workspace_id"`
	StatsDate      time.Time `json:"stats_date"`
	AppID          int64     `json:"app_id"`
	PlatformID     int64     `json:"platform_id"`
	PlatformUserID string    `json:"platform_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type PaymentStatsDailyOverview struct {
	WorkspaceID          string    `json:"workspace_id"`
	StatsDate            time.Time `json:"stats_date"`
	ProductsTotal        int64     `json:"products_total"`
	ActiveProducts       int64     `json:"active_products"`
	VisibleProducts      int64     `json:"visible_products"`
	OrdersCreated        int64     `json:"orders_created"`
	DraftOrders          int64     `json:"draft_orders"`
	PendingPaymentOrders int64     `json:"pending_payment_orders"`
	PaidOrders           int64     `json:"paid_orders"`
	FulfilledOrders      int64     `json:"fulfilled_orders"`
	CanceledOrders       int64     `json:"canceled_orders"`
	ExpiredOrders        int64     `json:"expired_orders"`
	RefundedOrders       int64     `json:"refunded_orders"`
	ChargebackedOrders   int64     `json:"chargebacked_orders"`
	FailedOrders         int64     `json:"failed_orders"`
	PurchaseCount        int64     `json:"purchase_count"`
	PurchaseQuantity     int64     `json:"purchase_quantity"`
	UniqueBuyers         int64     `json:"unique_buyers"`
	RefundCount          int64     `json:"refund_count"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type PaymentStatsEvent struct {
	ID             int64                      `json:"id"`
	EventType      PaymentStatsEventEventType `json:"event_type"`
	SourceID       int64                      `json:"source_id"`
	WorkspaceID    string                     `json:"workspace_id"`
	ProductID      string                     `json:"product_id"`
	AppID          int64                      `json:"app_id"`
	PlatformID     int64                      `json:"platform_id"`
	PlatformUserID string                     `json:"platform_user_id"`
	Quantity       int64                      `json:"quantity"`
	AssetCode      string                     `json:"asset_code"`
	AmountMinor    int64                      `json:"amount_minor"`
	OccurredAt     time.Time                  `json:"occurred_at"`
	CreatedAt      time.Time                  `json:"created_at"`
}

type PaymentStatsOrderEvent struct {
	ID          int64                             `json:"id"`
	OrderID     int64                             `json:"order_id"`
	WorkspaceID string                            `json:"workspace_id"`
	ProductID   string                            `json:"product_id"`
	EventType   PaymentStatsOrderEventEventType   `json:"event_type"`
	OrderStatus PaymentStatsOrderEventOrderStatus `json:"order_status"`
	OccurredAt  time.Time                         `json:"occurred_at"`
	CreatedAt   time.Time                         `json:"created_at"`
}

type PaymentSubscription struct {
	ID                     int64                     `json:"id"`
	WorkspaceID            string                    `json:"workspace_id"`
	ProviderCode           string                    `json:"provider_code"`
	ProviderSubscriptionID string                    `json:"provider_subscription_id"`
	AppID                  int64                     `json:"app_id"`
	PlatformID             int64                     `json:"platform_id"`
	PlatformUserID         string                    `json:"platform_user_id"`
	InternalUserID         sql.NullInt64             `json:"internal_user_id"`
	ProductID              string                    `json:"product_id"`
	OrderID                sql.NullInt64             `json:"order_id"`
	AttemptID              sql.NullInt64             `json:"attempt_id"`
	Status                 PaymentSubscriptionStatus `json:"status"`
	CancelReason           sql.NullString            `json:"cancel_reason"`
	StartedAt              time.Time                 `json:"started_at"`
	EndedAt                sql.NullTime              `json:"ended_at"`
	CreatedAt              time.Time                 `json:"created_at"`
	UpdatedAt              time.Time                 `json:"updated_at"`
}

type PaymentSubscriptionRenewal struct {
	ID                     int64     `json:"id"`
	WorkspaceID            string    `json:"workspace_id"`
	SubscriptionID         int64     `json:"subscription_id"`
	OrderID                int64     `json:"order_id"`
	AttemptID              int64     `json:"attempt_id"`
	ProviderCode           string    `json:"provider_code"`
	ProviderSubscriptionID string    `json:"provider_subscription_id"`
	ProviderChargeID       string    `json:"provider_charge_id"`
	AmountMinor            int64     `json:"amount_minor"`
	AssetCode              string    `json:"asset_code"`
	PeriodEnd              time.Time `json:"period_end"`
	CreatedAt              time.Time `json:"created_at"`
}

type PaymentTonWallet struct {
	WorkspaceID      string         `json:"workspace_id"`
	Network          string         `json:"network"`
	WalletAddress    string         `json:"wallet_address"`
	NetworkConfigUrl sql.NullString `json:"network_config_url"`
	IsEnabled        bool           `json:"is_enabled"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}
