// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.adminCreatePromoStmt, err = db.PrepareContext(ctx, adminCreatePromo); err != nil {
		return nil, fmt.Errorf("error preparing query AdminCreatePromo: %w", err)
	}
	if q.adminDeleteLocalizationStmt, err = db.PrepareContext(ctx, adminDeleteLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteLocalization: %w", err)
	}
	if q.adminDeleteRewardStmt, err = db.PrepareContext(ctx, adminDeleteReward); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteReward: %w", err)
	}
	if q.adminGetLocalizationStmt, err = db.PrepareContext(ctx, adminGetLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetLocalization: %w", err)
	}
	if q.adminGetPromoStmt, err = db.PrepareContext(ctx, adminGetPromo); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetPromo: %w", err)
	}
	if q.adminGetRewardStmt, err = db.PrepareContext(ctx, adminGetReward); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetReward: %w", err)
	}
	if q.adminGetStatsStmt, err = db.PrepareContext(ctx, adminGetStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetStats: %w", err)
	}
	if q.adminListDailyStatsStmt, err = db.PrepareContext(ctx, adminListDailyStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListDailyStats: %w", err)
	}
	if q.adminListLocalizationsStmt, err = db.PrepareContext(ctx, adminListLocalizations); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListLocalizations: %w", err)
	}
	if q.adminListPromosStmt, err = db.PrepareContext(ctx, adminListPromos); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListPromos: %w", err)
	}
	if q.adminListRedemptionsStmt, err = db.PrepareContext(ctx, adminListRedemptions); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListRedemptions: %w", err)
	}
	if q.adminSoftDeletePromoStmt, err = db.PrepareContext(ctx, adminSoftDeletePromo); err != nil {
		return nil, fmt.Errorf("error preparing query AdminSoftDeletePromo: %w", err)
	}
	if q.adminUpdatePromoStmt, err = db.PrepareContext(ctx, adminUpdatePromo); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpdatePromo: %w", err)
	}
	if q.adminUpsertLocalizationStmt, err = db.PrepareContext(ctx, adminUpsertLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertLocalization: %w", err)
	}
	if q.adminUpsertRewardStmt, err = db.PrepareContext(ctx, adminUpsertReward); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertReward: %w", err)
	}
	if q.createRedemptionStmt, err = db.PrepareContext(ctx, createRedemption); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRedemption: %w", err)
	}
	if q.getApplyBundleForUpdateStmt, err = db.PrepareContext(ctx, getApplyBundleForUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query GetApplyBundleForUpdate: %w", err)
	}
	if q.getRedemptionStmt, err = db.PrepareContext(ctx, getRedemption); err != nil {
		return nil, fmt.Errorf("error preparing query GetRedemption: %w", err)
	}
	if q.listExportLocalizationsStmt, err = db.PrepareContext(ctx, listExportLocalizations); err != nil {
		return nil, fmt.Errorf("error preparing query ListExportLocalizations: %w", err)
	}
	if q.listExportPromosStmt, err = db.PrepareContext(ctx, listExportPromos); err != nil {
		return nil, fmt.Errorf("error preparing query ListExportPromos: %w", err)
	}
	if q.listExportRewardsStmt, err = db.PrepareContext(ctx, listExportRewards); err != nil {
		return nil, fmt.Errorf("error preparing query ListExportRewards: %w", err)
	}
	if q.listImportPromoCodesStmt, err = db.PrepareContext(ctx, listImportPromoCodes); err != nil {
		return nil, fmt.Errorf("error preparing query ListImportPromoCodes: %w", err)
	}
	if q.listImportPromoIDsStmt, err = db.PrepareContext(ctx, listImportPromoIDs); err != nil {
		return nil, fmt.Errorf("error preparing query ListImportPromoIDs: %w", err)
	}
	if q.listRewardsStmt, err = db.PrepareContext(ctx, listRewards); err != nil {
		return nil, fmt.Errorf("error preparing query ListRewards: %w", err)
	}
	if q.refreshDailyStatsStmt, err = db.PrepareContext(ctx, refreshDailyStats); err != nil {
		return nil, fmt.Errorf("error preparing query RefreshDailyStats: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.adminCreatePromoStmt != nil {
		if cerr := q.adminCreatePromoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminCreatePromoStmt: %w", cerr)
		}
	}
	if q.adminDeleteLocalizationStmt != nil {
		if cerr := q.adminDeleteLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteLocalizationStmt: %w", cerr)
		}
	}
	if q.adminDeleteRewardStmt != nil {
		if cerr := q.adminDeleteRewardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteRewardStmt: %w", cerr)
		}
	}
	if q.adminGetLocalizationStmt != nil {
		if cerr := q.adminGetLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetLocalizationStmt: %w", cerr)
		}
	}
	if q.adminGetPromoStmt != nil {
		if cerr := q.adminGetPromoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetPromoStmt: %w", cerr)
		}
	}
	if q.adminGetRewardStmt != nil {
		if cerr := q.adminGetRewardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetRewardStmt: %w", cerr)
		}
	}
	if q.adminGetStatsStmt != nil {
		if cerr := q.adminGetStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetStatsStmt: %w", cerr)
		}
	}
	if q.adminListDailyStatsStmt != nil {
		if cerr := q.adminListDailyStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListDailyStatsStmt: %w", cerr)
		}
	}
	if q.adminListLocalizationsStmt != nil {
		if cerr := q.adminListLocalizationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListLocalizationsStmt: %w", cerr)
		}
	}
	if q.adminListPromosStmt != nil {
		if cerr := q.adminListPromosStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListPromosStmt: %w", cerr)
		}
	}
	if q.adminListRedemptionsStmt != nil {
		if cerr := q.adminListRedemptionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListRedemptionsStmt: %w", cerr)
		}
	}
	if q.adminSoftDeletePromoStmt != nil {
		if cerr := q.adminSoftDeletePromoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminSoftDeletePromoStmt: %w", cerr)
		}
	}
	if q.adminUpdatePromoStmt != nil {
		if cerr := q.adminUpdatePromoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpdatePromoStmt: %w", cerr)
		}
	}
	if q.adminUpsertLocalizationStmt != nil {
		if cerr := q.adminUpsertLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertLocalizationStmt: %w", cerr)
		}
	}
	if q.adminUpsertRewardStmt != nil {
		if cerr := q.adminUpsertRewardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertRewardStmt: %w", cerr)
		}
	}
	if q.createRedemptionStmt != nil {
		if cerr := q.createRedemptionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRedemptionStmt: %w", cerr)
		}
	}
	if q.getApplyBundleForUpdateStmt != nil {
		if cerr := q.getApplyBundleForUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getApplyBundleForUpdateStmt: %w", cerr)
		}
	}
	if q.getRedemptionStmt != nil {
		if cerr := q.getRedemptionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRedemptionStmt: %w", cerr)
		}
	}
	if q.listExportLocalizationsStmt != nil {
		if cerr := q.listExportLocalizationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listExportLocalizationsStmt: %w", cerr)
		}
	}
	if q.listExportPromosStmt != nil {
		if cerr := q.listExportPromosStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listExportPromosStmt: %w", cerr)
		}
	}
	if q.listExportRewardsStmt != nil {
		if cerr := q.listExportRewardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listExportRewardsStmt: %w", cerr)
		}
	}
	if q.listImportPromoCodesStmt != nil {
		if cerr := q.listImportPromoCodesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listImportPromoCodesStmt: %w", cerr)
		}
	}
	if q.listImportPromoIDsStmt != nil {
		if cerr := q.listImportPromoIDsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listImportPromoIDsStmt: %w", cerr)
		}
	}
	if q.listRewardsStmt != nil {
		if cerr := q.listRewardsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listRewardsStmt: %w", cerr)
		}
	}
	if q.refreshDailyStatsStmt != nil {
		if cerr := q.refreshDailyStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing refreshDailyStatsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	tx                          *sql.Tx
	adminCreatePromoStmt        *sql.Stmt
	adminDeleteLocalizationStmt *sql.Stmt
	adminDeleteRewardStmt       *sql.Stmt
	adminGetLocalizationStmt    *sql.Stmt
	adminGetPromoStmt           *sql.Stmt
	adminGetRewardStmt          *sql.Stmt
	adminGetStatsStmt           *sql.Stmt
	adminListDailyStatsStmt     *sql.Stmt
	adminListLocalizationsStmt  *sql.Stmt
	adminListPromosStmt         *sql.Stmt
	adminListRedemptionsStmt    *sql.Stmt
	adminSoftDeletePromoStmt    *sql.Stmt
	adminUpdatePromoStmt        *sql.Stmt
	adminUpsertLocalizationStmt *sql.Stmt
	adminUpsertRewardStmt       *sql.Stmt
	createRedemptionStmt        *sql.Stmt
	getApplyBundleForUpdateStmt *sql.Stmt
	getRedemptionStmt           *sql.Stmt
	listExportLocalizationsStmt *sql.Stmt
	listExportPromosStmt        *sql.Stmt
	listExportRewardsStmt       *sql.Stmt
	listImportPromoCodesStmt    *sql.Stmt
	listImportPromoIDsStmt      *sql.Stmt
	listRewardsStmt             *sql.Stmt
	refreshDailyStatsStmt       *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		adminCreatePromoStmt:        q.adminCreatePromoStmt,
		adminDeleteLocalizationStmt: q.adminDeleteLocalizationStmt,
		adminDeleteRewardStmt:       q.adminDeleteRewardStmt,
		adminGetLocalizationStmt:    q.adminGetLocalizationStmt,
		adminGetPromoStmt:           q.adminGetPromoStmt,
		adminGetRewardStmt:          q.adminGetRewardStmt,
		adminGetStatsStmt:           q.adminGetStatsStmt,
		adminListDailyStatsStmt:     q.adminListDailyStatsStmt,
		adminListLocalizationsStmt:  q.adminListLocalizationsStmt,
		adminListPromosStmt:         q.adminListPromosStmt,
		adminListRedemptionsStmt:    q.adminListRedemptionsStmt,
		adminSoftDeletePromoStmt:    q.adminSoftDeletePromoStmt,
		adminUpdatePromoStmt:        q.adminUpdatePromoStmt,
		adminUpsertLocalizationStmt: q.adminUpsertLocalizationStmt,
		adminUpsertRewardStmt:       q.adminUpsertRewardStmt,
		createRedemptionStmt:        q.createRedemptionStmt,
		getApplyBundleForUpdateStmt: q.getApplyBundleForUpdateStmt,
		getRedemptionStmt:           q.getRedemptionStmt,
		listExportLocalizationsStmt: q.listExportLocalizationsStmt,
		listExportPromosStmt:        q.listExportPromosStmt,
		listExportRewardsStmt:       q.listExportRewardsStmt,
		listImportPromoCodesStmt:    q.listImportPromoCodesStmt,
		listImportPromoIDsStmt:      q.listImportPromoIDsStmt,
		listRewardsStmt:             q.listRewardsStmt,
		refreshDailyStatsStmt:       q.refreshDailyStatsStmt,
	}
}
