// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type PromoDurationUnit string

const (
	PromoDurationUnitSecond PromoDurationUnit = "second"
	PromoDurationUnitMinute PromoDurationUnit = "minute"
	PromoDurationUnitHour   PromoDurationUnit = "hour"
	PromoDurationUnitDay    PromoDurationUnit = "day"
	PromoDurationUnitWeek   PromoDurationUnit = "week"
	PromoDurationUnitMonth  PromoDurationUnit = "month"
	PromoDurationUnitYear   PromoDurationUnit = "year"
)

func (e *PromoDurationUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromoDurationUnit(s)
	case string:
		*e = PromoDurationUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for PromoDurationUnit: %T", src)
	}
	return nil
}

type NullPromoDurationUnit struct {
	PromoDurationUnit PromoDurationUnit `json:"promo_duration_unit"`
	Valid             bool              `json:"valid"` // Valid is true if PromoDurationUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromoDurationUnit) Scan(value interface{}) error {
	if value == nil {
		ns.PromoDurationUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromoDurationUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromoDurationUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromoDurationUnit), nil
}

type PromoRewardType string

const (
	PromoRewardTypeQuantity PromoRewardType = "quantity"
	PromoRewardTypeDuration PromoRewardType = "duration"
)

func (e *PromoRewardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromoRewardType(s)
	case string:
		*e = PromoRewardType(s)
	default:
		return fmt.Errorf("unsupported scan type for PromoRewardType: %T", src)
	}
	return nil
}

type NullPromoRewardType struct {
	PromoRewardType PromoRewardType `json:"promo_reward_type"`
	Valid           bool            `json:"valid"` // Valid is true if PromoRewardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromoRewardType) Scan(value interface{}) error {
	if value == nil {
		ns.PromoRewardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromoRewardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromoRewardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromoRewardType), nil
}

type PromoClbEvent struct {
	ID                 int64          `json:"id"`
	WorkspaceID        string         `json:"workspace_id"`
	SourceService      string         `json:"source_service"`
	EventType          string         `json:"event_type"`
	EventKey           string         `json:"event_key"`
	IdempotencyKey     string         `json:"idempotency_key"`
	Payload            []byte         `json:"payload"`
	PayloadContentType string         `json:"payload_content_type"`
	Status             string         `json:"status"`
	AttemptCount       int32          `json:"attempt_count"`
	NextAttemptAt      time.Time      `json:"next_attempt_at"`
	LockedBy           sql.NullString `json:"locked_by"`
	LockedUntil        sql.NullTime   `json:"locked_until"`
	DeliveredAt        sql.NullTime   `json:"delivered_at"`
	RejectedAt         sql.NullTime   `json:"rejected_at"`
	LastError          sql.NullString `json:"last_error"`
	RejectReason       sql.NullString `json:"reject_reason"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type PromoLocalization struct {
	WorkspaceID string    `json:"workspace_id"`
	PromoID     int64     `json:"promo_id"`
	Locale      string    `json:"locale"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PromoOffer struct {
	ID              int64                 `json:"id"`
	WorkspaceID     string                `json:"workspace_id"`
	Code            string                `json:"code"`
	CodeNormalized  string                `json:"code_normalized"`
	Payload         json.RawMessage       `json:"payload"`
	Target          pqtype.NullRawMessage `json:"target"`
	MaxActivations  int64                 `json:"max_activations"`
	ActivationCount int64                 `json:"activation_count"`
	IsActive        bool                  `json:"is_active"`
	StartAt         sql.NullTime          `json:"start_at"`
	EndAt           sql.NullTime          `json:"end_at"`
	DeletedAt       sql.NullTime          `json:"deleted_at"`
	CreatedAt       time.Time             `json:"created_at"`
	UpdatedAt       time.Time             `json:"updated_at"`
}

type PromoRedemption struct {
	ID             int64           `json:"id"`
	WorkspaceID    string          `json:"workspace_id"`
	PromoID        int64           `json:"promo_id"`
	AppID          int64           `json:"app_id"`
	PlatformID     int64           `json:"platform_id"`
	PlatformUserID string          `json:"platform_user_id"`
	RewardSnapshot json.RawMessage `json:"reward_snapshot"`
	RedeemedAt     time.Time       `json:"redeemed_at"`
	CreatedAt      time.Time       `json:"created_at"`
}

type PromoRedemptionEvent struct {
	ID           int64     `json:"id"`
	WorkspaceID  string    `json:"workspace_id"`
	PromoID      int64     `json:"promo_id"`
	RedemptionID int64     `json:"redemption_id"`
	OccurredAt   time.Time `json:"occurred_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type PromoReward struct {
	ID           int64                 `json:"id"`
	WorkspaceID  string                `json:"workspace_id"`
	PromoID      int64                 `json:"promo_id"`
	RewardKey    string                `json:"reward_key"`
	RewardType   PromoRewardType       `json:"reward_type"`
	Quantity     int64                 `json:"quantity"`
	Scale        int16                 `json:"scale"`
	DurationUnit NullPromoDurationUnit `json:"duration_unit"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

type PromoStatsDaily struct {
	WorkspaceID     string    `json:"workspace_id"`
	PromoID         int64     `json:"promo_id"`
	StatsDate       time.Time `json:"stats_date"`
	RedemptionCount int64     `json:"redemption_count"`
	UniqueUsers     int64     `json:"unique_users"`
	UpdatedAt       time.Time `json:"updated_at"`
}
