// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const adminCreatePromo = `-- name: AdminCreatePromo :one
INSERT INTO promo_offer (
    workspace_id, code, code_normalized, payload, target, max_activations,
    is_active, start_at, end_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type AdminCreatePromoParams struct {
	WorkspaceID    string                `json:"workspace_id"`
	Code           string                `json:"code"`
	CodeNormalized string                `json:"code_normalized"`
	Payload        json.RawMessage       `json:"payload"`
	Target         pqtype.NullRawMessage `json:"target"`
	MaxActivations int64                 `json:"max_activations"`
	IsActive       bool                  `json:"is_active"`
	StartAt        sql.NullTime          `json:"start_at"`
	EndAt          sql.NullTime          `json:"end_at"`
}

func (q *Queries) AdminCreatePromo(ctx context.Context, arg AdminCreatePromoParams) (int64, error) {
	row := q.queryRow(ctx, q.adminCreatePromoStmt, adminCreatePromo,
		arg.WorkspaceID,
		arg.Code,
		arg.CodeNormalized,
		arg.Payload,
		arg.Target,
		arg.MaxActivations,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const adminDeleteLocalization = `-- name: AdminDeleteLocalization :execrows
DELETE FROM promo_localization
WHERE workspace_id = $1 AND promo_id = $2 AND locale = $3
`

type AdminDeleteLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     int64  `json:"promo_id"`
	Locale      string `json:"locale"`
}

func (q *Queries) AdminDeleteLocalization(ctx context.Context, arg AdminDeleteLocalizationParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteLocalizationStmt, adminDeleteLocalization, arg.WorkspaceID, arg.PromoID, arg.Locale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteReward = `-- name: AdminDeleteReward :execrows
DELETE FROM promo_reward
WHERE workspace_id = $1 AND promo_id = $2 AND reward_key = $3
`

type AdminDeleteRewardParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     int64  `json:"promo_id"`
	RewardKey   string `json:"reward_key"`
}

func (q *Queries) AdminDeleteReward(ctx context.Context, arg AdminDeleteRewardParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteRewardStmt, adminDeleteReward, arg.WorkspaceID, arg.PromoID, arg.RewardKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminGetLocalization = `-- name: AdminGetLocalization :one
SELECT workspace_id, promo_id, locale, title, description, created_at, updated_at
FROM promo_localization
WHERE workspace_id = $1 AND promo_id = $2 AND locale = $3
LIMIT 1
`

type AdminGetLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     int64  `json:"promo_id"`
	Locale      string `json:"locale"`
}

func (q *Queries) AdminGetLocalization(ctx context.Context, arg AdminGetLocalizationParams) (PromoLocalization, error) {
	row := q.queryRow(ctx, q.adminGetLocalizationStmt, adminGetLocalization, arg.WorkspaceID, arg.PromoID, arg.Locale)
	var i PromoLocalization
	err := row.Scan(
		&i.WorkspaceID,
		&i.PromoID,
		&i.Locale,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetPromo = `-- name: AdminGetPromo :one
SELECT id, workspace_id, code, code_normalized, payload, target, max_activations, activation_count, is_active, start_at, end_at, deleted_at, created_at, updated_at
FROM promo_offer
WHERE workspace_id = $1 AND id = $2
LIMIT 1
`

type AdminGetPromoParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          int64  `json:"id"`
}

func (q *Queries) AdminGetPromo(ctx context.Context, arg AdminGetPromoParams) (PromoOffer, error) {
	row := q.queryRow(ctx, q.adminGetPromoStmt, adminGetPromo, arg.WorkspaceID, arg.ID)
	var i PromoOffer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.CodeNormalized,
		&i.Payload,
		&i.Target,
		&i.MaxActivations,
		&i.ActivationCount,
		&i.IsActive,
		&i.StartAt,
		&i.EndAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetReward = `-- name: AdminGetReward :one
SELECT id, workspace_id, promo_id, reward_key, reward_type, quantity, scale, duration_unit, created_at, updated_at
FROM promo_reward
WHERE workspace_id = $1 AND promo_id = $2 AND reward_key = $3
LIMIT 1
`

type AdminGetRewardParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     int64  `json:"promo_id"`
	RewardKey   string `json:"reward_key"`
}

func (q *Queries) AdminGetReward(ctx context.Context, arg AdminGetRewardParams) (PromoReward, error) {
	row := q.queryRow(ctx, q.adminGetRewardStmt, adminGetReward, arg.WorkspaceID, arg.PromoID, arg.RewardKey)
	var i PromoReward
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PromoID,
		&i.RewardKey,
		&i.RewardType,
		&i.Quantity,
		&i.Scale,
		&i.DurationUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetStats = `-- name: AdminGetStats :one
SELECT
    activation_count,
    max_activations,
    CASE
        WHEN max_activations = 0 THEN -1
        ELSE max_activations - activation_count
    END::bigint AS remaining_activations
FROM promo_offer
WHERE workspace_id = $1 AND id = $2
LIMIT 1
`

type AdminGetStatsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          int64  `json:"id"`
}

type AdminGetStatsRow struct {
	ActivationCount      int64 `json:"activation_count"`
	MaxActivations       int64 `json:"max_activations"`
	RemainingActivations int64 `json:"remaining_activations"`
}

func (q *Queries) AdminGetStats(ctx context.Context, arg AdminGetStatsParams) (AdminGetStatsRow, error) {
	row := q.queryRow(ctx, q.adminGetStatsStmt, adminGetStats, arg.WorkspaceID, arg.ID)
	var i AdminGetStatsRow
	err := row.Scan(&i.ActivationCount, &i.MaxActivations, &i.RemainingActivations)
	return i, err
}

const adminListDailyStats = `-- name: AdminListDailyStats :many
SELECT workspace_id, promo_id, stats_date, redemption_count, unique_users, updated_at
FROM promo_stats_daily
WHERE workspace_id = $1
  AND promo_id = $2
  AND stats_date >= $3
  AND stats_date <= $4
ORDER BY stats_date
`

type AdminListDailyStatsParams struct {
	WorkspaceID string    `json:"workspace_id"`
	PromoID     int64     `json:"promo_id"`
	StatsDate   time.Time `json:"stats_date"`
	StatsDate_2 time.Time `json:"stats_date_2"`
}

func (q *Queries) AdminListDailyStats(ctx context.Context, arg AdminListDailyStatsParams) ([]PromoStatsDaily, error) {
	rows, err := q.query(ctx, q.adminListDailyStatsStmt, adminListDailyStats,
		arg.WorkspaceID,
		arg.PromoID,
		arg.StatsDate,
		arg.StatsDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoStatsDaily
	for rows.Next() {
		var i PromoStatsDaily
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.PromoID,
			&i.StatsDate,
			&i.RedemptionCount,
			&i.UniqueUsers,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListLocalizations = `-- name: AdminListLocalizations :many
SELECT workspace_id, promo_id, locale, title, description, created_at, updated_at
FROM promo_localization
WHERE workspace_id = $1 AND promo_id = $2
ORDER BY locale
`

type AdminListLocalizationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     int64  `json:"promo_id"`
}

func (q *Queries) AdminListLocalizations(ctx context.Context, arg AdminListLocalizationsParams) ([]PromoLocalization, error) {
	rows, err := q.query(ctx, q.adminListLocalizationsStmt, adminListLocalizations, arg.WorkspaceID, arg.PromoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoLocalization
	for rows.Next() {
		var i PromoLocalization
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.PromoID,
			&i.Locale,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListPromos = `-- name: AdminListPromos :many
SELECT id, workspace_id, code, code_normalized, payload, target, max_activations, activation_count, is_active, start_at, end_at, deleted_at, created_at, updated_at
FROM promo_offer
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type AdminListPromosParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) AdminListPromos(ctx context.Context, arg AdminListPromosParams) ([]PromoOffer, error) {
	rows, err := q.query(ctx, q.adminListPromosStmt, adminListPromos, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoOffer
	for rows.Next() {
		var i PromoOffer
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Code,
			&i.CodeNormalized,
			&i.Payload,
			&i.Target,
			&i.MaxActivations,
			&i.ActivationCount,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRedemptions = `-- name: AdminListRedemptions :many
SELECT id, workspace_id, promo_id, app_id, platform_id, platform_user_id, reward_snapshot, redeemed_at, created_at
FROM promo_redemption
WHERE workspace_id = $1
  AND promo_id = $2
ORDER BY redeemed_at DESC, id DESC
LIMIT $3 OFFSET $4
`

type AdminListRedemptionsParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     int64  `json:"promo_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) AdminListRedemptions(ctx context.Context, arg AdminListRedemptionsParams) ([]PromoRedemption, error) {
	rows, err := q.query(ctx, q.adminListRedemptionsStmt, adminListRedemptions,
		arg.WorkspaceID,
		arg.PromoID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoRedemption
	for rows.Next() {
		var i PromoRedemption
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PromoID,
			&i.AppID,
			&i.PlatformID,
			&i.PlatformUserID,
			&i.RewardSnapshot,
			&i.RedeemedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSoftDeletePromo = `-- name: AdminSoftDeletePromo :execrows
UPDATE promo_offer
SET deleted_at = now(), is_active = FALSE, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL
`

type AdminSoftDeletePromoParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          int64  `json:"id"`
}

func (q *Queries) AdminSoftDeletePromo(ctx context.Context, arg AdminSoftDeletePromoParams) (int64, error) {
	result, err := q.exec(ctx, q.adminSoftDeletePromoStmt, adminSoftDeletePromo, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpdatePromo = `-- name: AdminUpdatePromo :execrows
UPDATE promo_offer
SET code = $1,
    code_normalized = $2,
    payload = $3,
    target = $4,
    max_activations = $5,
    is_active = $6,
    start_at = $7,
    end_at = $8,
    updated_at = now()
WHERE workspace_id = $9 AND id = $10 AND deleted_at IS NULL
`

type AdminUpdatePromoParams struct {
	Code           string                `json:"code"`
	CodeNormalized string                `json:"code_normalized"`
	Payload        json.RawMessage       `json:"payload"`
	Target         pqtype.NullRawMessage `json:"target"`
	MaxActivations int64                 `json:"max_activations"`
	IsActive       bool                  `json:"is_active"`
	StartAt        sql.NullTime          `json:"start_at"`
	EndAt          sql.NullTime          `json:"end_at"`
	WorkspaceID    string                `json:"workspace_id"`
	ID             int64                 `json:"id"`
}

func (q *Queries) AdminUpdatePromo(ctx context.Context, arg AdminUpdatePromoParams) (int64, error) {
	result, err := q.exec(ctx, q.adminUpdatePromoStmt, adminUpdatePromo,
		arg.Code,
		arg.CodeNormalized,
		arg.Payload,
		arg.Target,
		arg.MaxActivations,
		arg.IsActive,
		arg.StartAt,
		arg.EndAt,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpsertLocalization = `-- name: AdminUpsertLocalization :exec
INSERT INTO promo_localization (
    workspace_id, promo_id, locale, title, description
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, promo_id, locale) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = now()
`

type AdminUpsertLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     int64  `json:"promo_id"`
	Locale      string `json:"locale"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) AdminUpsertLocalization(ctx context.Context, arg AdminUpsertLocalizationParams) error {
	_, err := q.exec(ctx, q.adminUpsertLocalizationStmt, adminUpsertLocalization,
		arg.WorkspaceID,
		arg.PromoID,
		arg.Locale,
		arg.Title,
		arg.Description,
	)
	return err
}

const adminUpsertReward = `-- name: AdminUpsertReward :exec
INSERT INTO promo_reward (
    workspace_id, promo_id, reward_key, reward_type, quantity, scale, duration_unit
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (workspace_id, promo_id, reward_key) DO UPDATE SET
    reward_type = EXCLUDED.reward_type,
    quantity = EXCLUDED.quantity,
    scale = EXCLUDED.scale,
    duration_unit = EXCLUDED.duration_unit,
    updated_at = now()
`

type AdminUpsertRewardParams struct {
	WorkspaceID  string                `json:"workspace_id"`
	PromoID      int64                 `json:"promo_id"`
	RewardKey    string                `json:"reward_key"`
	RewardType   PromoRewardType       `json:"reward_type"`
	Quantity     int64                 `json:"quantity"`
	Scale        int16                 `json:"scale"`
	DurationUnit NullPromoDurationUnit `json:"duration_unit"`
}

func (q *Queries) AdminUpsertReward(ctx context.Context, arg AdminUpsertRewardParams) error {
	_, err := q.exec(ctx, q.adminUpsertRewardStmt, adminUpsertReward,
		arg.WorkspaceID,
		arg.PromoID,
		arg.RewardKey,
		arg.RewardType,
		arg.Quantity,
		arg.Scale,
		arg.DurationUnit,
	)
	return err
}

const createRedemption = `-- name: CreateRedemption :one
WITH inserted AS (
    INSERT INTO promo_redemption (
        workspace_id, promo_id, app_id, platform_id, platform_user_id,
        reward_snapshot
    ) VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING
        id,
        workspace_id,
        promo_id,
        app_id,
        platform_id,
        platform_user_id,
        reward_snapshot,
        redeemed_at
),
updated_offer AS (
    UPDATE promo_offer o
    SET activation_count = activation_count + 1,
        updated_at = now()
    FROM inserted i
    WHERE o.workspace_id = i.workspace_id
      AND o.id = i.promo_id
    RETURNING o.code
),
created_event AS (
    INSERT INTO promo_redemption_event (
        workspace_id, promo_id, redemption_id
    )
    SELECT workspace_id, promo_id, id
    FROM inserted
    RETURNING redemption_id
),
created_callback AS (
    INSERT INTO promo_clb_event (
        workspace_id,
        source_service,
        event_type,
        event_key,
        idempotency_key,
        payload,
        payload_content_type,
        next_attempt_at
    )
    SELECT
        i.workspace_id,
        'promo',
        'promo.applied',
        'promo.applied:' || i.id::text,
        'promo.applied:' || i.id::text,
        jsonb_build_object(
            'redemption_id', i.id,
            'workspace_id', i.workspace_id,
            'promo_id', i.promo_id,
            'code', u.code,
            'app_id', i.app_id,
            'platform_id', i.platform_id,
            'platform_user_id', i.platform_user_id,
            'rewards', i.reward_snapshot
        )::text::bytea,
        'application/json',
        now()
    FROM inserted i
    CROSS JOIN updated_offer u
    RETURNING id
)
SELECT id, redeemed_at
FROM inserted
`

type CreateRedemptionParams struct {
	WorkspaceID    string          `json:"workspace_id"`
	PromoID        int64           `json:"promo_id"`
	AppID          int64           `json:"app_id"`
	PlatformID     int64           `json:"platform_id"`
	PlatformUserID string          `json:"platform_user_id"`
	RewardSnapshot json.RawMessage `json:"reward_snapshot"`
}

type CreateRedemptionRow struct {
	ID         int64     `json:"id"`
	RedeemedAt time.Time `json:"redeemed_at"`
}

func (q *Queries) CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (CreateRedemptionRow, error) {
	row := q.queryRow(ctx, q.createRedemptionStmt, createRedemption,
		arg.WorkspaceID,
		arg.PromoID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.RewardSnapshot,
	)
	var i CreateRedemptionRow
	err := row.Scan(&i.ID, &i.RedeemedAt)
	return i, err
}

const getApplyBundleForUpdate = `-- name: GetApplyBundleForUpdate :many
SELECT
    o.id,
    o.workspace_id,
    o.code,
    o.payload,
    o.target,
    o.max_activations,
    o.activation_count,
    o.is_active,
    o.start_at,
    o.end_at,
    o.deleted_at,
    o.created_at,
    o.updated_at,
    l.locale AS localization_locale,
    l.title AS localization_title,
    l.description AS localization_description,
    a.id AS redemption_id,
    a.app_id AS redemption_app_id,
    a.platform_id AS redemption_platform_id,
    a.platform_user_id AS redemption_platform_user_id,
    a.redeemed_at AS redemption_redeemed_at,
    a.reward_snapshot AS redemption_reward_snapshot,
    r.id AS reward_id,
    r.reward_key,
    r.reward_type,
    r.quantity AS reward_quantity,
    r.scale AS reward_scale,
    r.duration_unit
FROM promo_offer o
LEFT JOIN promo_localization l
  ON l.workspace_id = o.workspace_id
 AND l.promo_id = o.id
 AND l.locale = $1
LEFT JOIN promo_redemption a
  ON a.workspace_id = o.workspace_id
 AND a.promo_id = o.id
 AND a.app_id = $2
 AND a.platform_id = $3
 AND a.platform_user_id = $4
LEFT JOIN promo_reward r
  ON r.workspace_id = o.workspace_id
 AND r.promo_id = o.id
WHERE o.workspace_id = $5
  AND o.code_normalized = $6
ORDER BY r.id
FOR UPDATE OF o
`

type GetApplyBundleForUpdateParams struct {
	Locale         string `json:"locale"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
	WorkspaceID    string `json:"workspace_id"`
	CodeNormalized string `json:"code_normalized"`
}

type GetApplyBundleForUpdateRow struct {
	ID                       int64                 `json:"id"`
	WorkspaceID              string                `json:"workspace_id"`
	Code                     string                `json:"code"`
	Payload                  json.RawMessage       `json:"payload"`
	Target                   pqtype.NullRawMessage `json:"target"`
	MaxActivations           int64                 `json:"max_activations"`
	ActivationCount          int64                 `json:"activation_count"`
	IsActive                 bool                  `json:"is_active"`
	StartAt                  sql.NullTime          `json:"start_at"`
	EndAt                    sql.NullTime          `json:"end_at"`
	DeletedAt                sql.NullTime          `json:"deleted_at"`
	CreatedAt                time.Time             `json:"created_at"`
	UpdatedAt                time.Time             `json:"updated_at"`
	LocalizationLocale       sql.NullString        `json:"localization_locale"`
	LocalizationTitle        sql.NullString        `json:"localization_title"`
	LocalizationDescription  sql.NullString        `json:"localization_description"`
	RedemptionID             sql.NullInt64         `json:"redemption_id"`
	RedemptionAppID          sql.NullInt64         `json:"redemption_app_id"`
	RedemptionPlatformID     sql.NullInt64         `json:"redemption_platform_id"`
	RedemptionPlatformUserID sql.NullString        `json:"redemption_platform_user_id"`
	RedemptionRedeemedAt     sql.NullTime          `json:"redemption_redeemed_at"`
	RedemptionRewardSnapshot pqtype.NullRawMessage `json:"redemption_reward_snapshot"`
	RewardID                 sql.NullInt64         `json:"reward_id"`
	RewardKey                sql.NullString        `json:"reward_key"`
	RewardType               NullPromoRewardType   `json:"reward_type"`
	RewardQuantity           sql.NullInt64         `json:"reward_quantity"`
	RewardScale              sql.NullInt16         `json:"reward_scale"`
	DurationUnit             NullPromoDurationUnit `json:"duration_unit"`
}

func (q *Queries) GetApplyBundleForUpdate(ctx context.Context, arg GetApplyBundleForUpdateParams) ([]GetApplyBundleForUpdateRow, error) {
	rows, err := q.query(ctx, q.getApplyBundleForUpdateStmt, getApplyBundleForUpdate,
		arg.Locale,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
		arg.WorkspaceID,
		arg.CodeNormalized,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplyBundleForUpdateRow
	for rows.Next() {
		var i GetApplyBundleForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Code,
			&i.Payload,
			&i.Target,
			&i.MaxActivations,
			&i.ActivationCount,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocalizationLocale,
			&i.LocalizationTitle,
			&i.LocalizationDescription,
			&i.RedemptionID,
			&i.RedemptionAppID,
			&i.RedemptionPlatformID,
			&i.RedemptionPlatformUserID,
			&i.RedemptionRedeemedAt,
			&i.RedemptionRewardSnapshot,
			&i.RewardID,
			&i.RewardKey,
			&i.RewardType,
			&i.RewardQuantity,
			&i.RewardScale,
			&i.DurationUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRedemption = `-- name: GetRedemption :one
SELECT id, workspace_id, promo_id, app_id, platform_id, platform_user_id, reward_snapshot, redeemed_at, created_at
FROM promo_redemption
WHERE workspace_id = $1
  AND promo_id = $2
  AND app_id = $3
  AND platform_id = $4
  AND platform_user_id = $5
LIMIT 1
`

type GetRedemptionParams struct {
	WorkspaceID    string `json:"workspace_id"`
	PromoID        int64  `json:"promo_id"`
	AppID          int64  `json:"app_id"`
	PlatformID     int64  `json:"platform_id"`
	PlatformUserID string `json:"platform_user_id"`
}

func (q *Queries) GetRedemption(ctx context.Context, arg GetRedemptionParams) (PromoRedemption, error) {
	row := q.queryRow(ctx, q.getRedemptionStmt, getRedemption,
		arg.WorkspaceID,
		arg.PromoID,
		arg.AppID,
		arg.PlatformID,
		arg.PlatformUserID,
	)
	var i PromoRedemption
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PromoID,
		&i.AppID,
		&i.PlatformID,
		&i.PlatformUserID,
		&i.RewardSnapshot,
		&i.RedeemedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExportLocalizations = `-- name: ListExportLocalizations :many
SELECT workspace_id, promo_id, locale, title, description, created_at, updated_at
FROM promo_localization
WHERE workspace_id = $1
ORDER BY promo_id, locale
`

func (q *Queries) ListExportLocalizations(ctx context.Context, workspaceID string) ([]PromoLocalization, error) {
	rows, err := q.query(ctx, q.listExportLocalizationsStmt, listExportLocalizations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoLocalization
	for rows.Next() {
		var i PromoLocalization
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.PromoID,
			&i.Locale,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportPromos = `-- name: ListExportPromos :many
SELECT id, workspace_id, code, code_normalized, payload, target, max_activations, activation_count, is_active, start_at, end_at, deleted_at, created_at, updated_at
FROM promo_offer
WHERE workspace_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListExportPromos(ctx context.Context, workspaceID string) ([]PromoOffer, error) {
	rows, err := q.query(ctx, q.listExportPromosStmt, listExportPromos, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoOffer
	for rows.Next() {
		var i PromoOffer
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Code,
			&i.CodeNormalized,
			&i.Payload,
			&i.Target,
			&i.MaxActivations,
			&i.ActivationCount,
			&i.IsActive,
			&i.StartAt,
			&i.EndAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportRewards = `-- name: ListExportRewards :many
SELECT id, workspace_id, promo_id, reward_key, reward_type, quantity, scale, duration_unit, created_at, updated_at
FROM promo_reward
WHERE workspace_id = $1
ORDER BY promo_id, id
`

func (q *Queries) ListExportRewards(ctx context.Context, workspaceID string) ([]PromoReward, error) {
	rows, err := q.query(ctx, q.listExportRewardsStmt, listExportRewards, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoReward
	for rows.Next() {
		var i PromoReward
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PromoID,
			&i.RewardKey,
			&i.RewardType,
			&i.Quantity,
			&i.Scale,
			&i.DurationUnit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportPromoCodes = `-- name: ListImportPromoCodes :many
SELECT code_normalized
FROM promo_offer
WHERE workspace_id = $1
  AND deleted_at IS NULL
ORDER BY code_normalized
`

func (q *Queries) ListImportPromoCodes(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.query(ctx, q.listImportPromoCodesStmt, listImportPromoCodes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code_normalized string
		if err := rows.Scan(&code_normalized); err != nil {
			return nil, err
		}
		items = append(items, code_normalized)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportPromoIDs = `-- name: ListImportPromoIDs :many
SELECT id, code_normalized
FROM promo_offer
WHERE workspace_id = $1
  AND deleted_at IS NULL
ORDER BY code_normalized
`

type ListImportPromoIDsRow struct {
	ID             int64  `json:"id"`
	CodeNormalized string `json:"code_normalized"`
}

func (q *Queries) ListImportPromoIDs(ctx context.Context, workspaceID string) ([]ListImportPromoIDsRow, error) {
	rows, err := q.query(ctx, q.listImportPromoIDsStmt, listImportPromoIDs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportPromoIDsRow
	for rows.Next() {
		var i ListImportPromoIDsRow
		if err := rows.Scan(&i.ID, &i.CodeNormalized); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRewards = `-- name: ListRewards :many
SELECT id, workspace_id, promo_id, reward_key, reward_type, quantity, scale, duration_unit, created_at, updated_at
FROM promo_reward
WHERE workspace_id = $1 AND promo_id = $2
ORDER BY id
`

type ListRewardsParams struct {
	WorkspaceID string `json:"workspace_id"`
	PromoID     int64  `json:"promo_id"`
}

func (q *Queries) ListRewards(ctx context.Context, arg ListRewardsParams) ([]PromoReward, error) {
	rows, err := q.query(ctx, q.listRewardsStmt, listRewards, arg.WorkspaceID, arg.PromoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoReward
	for rows.Next() {
		var i PromoReward
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PromoID,
			&i.RewardKey,
			&i.RewardType,
			&i.Quantity,
			&i.Scale,
			&i.DurationUnit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshDailyStats = `-- name: RefreshDailyStats :exec
INSERT INTO promo_stats_daily (
    workspace_id, promo_id, stats_date, redemption_count, unique_users
)
SELECT
    e.workspace_id,
    e.promo_id,
    e.occurred_at::date,
    COUNT(*),
    COUNT(*)
FROM promo_redemption_event e
WHERE e.workspace_id = $3
  AND e.occurred_at >= $1 AND e.occurred_at < $2
GROUP BY e.workspace_id, e.promo_id, e.occurred_at::date
ON CONFLICT (workspace_id, promo_id, stats_date) DO UPDATE SET
    redemption_count = EXCLUDED.redemption_count,
    unique_users = EXCLUDED.unique_users,
    updated_at = now()
`

type RefreshDailyStatsParams struct {
	OccurredAt   time.Time `json:"occurred_at"`
	OccurredAt_2 time.Time `json:"occurred_at_2"`
	WorkspaceID  string    `json:"workspace_id"`
}

func (q *Queries) RefreshDailyStats(ctx context.Context, arg RefreshDailyStatsParams) error {
	_, err := q.exec(ctx, q.refreshDailyStatsStmt, refreshDailyStats, arg.OccurredAt, arg.OccurredAt_2, arg.WorkspaceID)
	return err
}
