// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.adminCreateItemStmt, err = db.PrepareContext(ctx, adminCreateItem); err != nil {
		return nil, fmt.Errorf("error preparing query AdminCreateItem: %w", err)
	}
	if q.adminDangerousChangeTypeStmt, err = db.PrepareContext(ctx, adminDangerousChangeType); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDangerousChangeType: %w", err)
	}
	if q.adminDeleteLocalizationStmt, err = db.PrepareContext(ctx, adminDeleteLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminDeleteLocalization: %w", err)
	}
	if q.adminGetItemBundleStmt, err = db.PrepareContext(ctx, adminGetItemBundle); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetItemBundle: %w", err)
	}
	if q.adminGetLocalizationStmt, err = db.PrepareContext(ctx, adminGetLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetLocalization: %w", err)
	}
	if q.adminGetStatsStmt, err = db.PrepareContext(ctx, adminGetStats); err != nil {
		return nil, fmt.Errorf("error preparing query AdminGetStats: %w", err)
	}
	if q.adminListItemsStmt, err = db.PrepareContext(ctx, adminListItems); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListItems: %w", err)
	}
	if q.adminListLocalizationsStmt, err = db.PrepareContext(ctx, adminListLocalizations); err != nil {
		return nil, fmt.Errorf("error preparing query AdminListLocalizations: %w", err)
	}
	if q.adminRestoreItemStmt, err = db.PrepareContext(ctx, adminRestoreItem); err != nil {
		return nil, fmt.Errorf("error preparing query AdminRestoreItem: %w", err)
	}
	if q.adminSoftDeleteItemStmt, err = db.PrepareContext(ctx, adminSoftDeleteItem); err != nil {
		return nil, fmt.Errorf("error preparing query AdminSoftDeleteItem: %w", err)
	}
	if q.adminUpdateItemStmt, err = db.PrepareContext(ctx, adminUpdateItem); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpdateItem: %w", err)
	}
	if q.adminUpsertLocalizationStmt, err = db.PrepareContext(ctx, adminUpsertLocalization); err != nil {
		return nil, fmt.Errorf("error preparing query AdminUpsertLocalization: %w", err)
	}
	if q.getItemBundleStmt, err = db.PrepareContext(ctx, getItemBundle); err != nil {
		return nil, fmt.Errorf("error preparing query GetItemBundle: %w", err)
	}
	if q.listExportItemsStmt, err = db.PrepareContext(ctx, listExportItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListExportItems: %w", err)
	}
	if q.listExportLocalizationsStmt, err = db.PrepareContext(ctx, listExportLocalizations); err != nil {
		return nil, fmt.Errorf("error preparing query ListExportLocalizations: %w", err)
	}
	if q.listImportItemKeysStmt, err = db.PrepareContext(ctx, listImportItemKeys); err != nil {
		return nil, fmt.Errorf("error preparing query ListImportItemKeys: %w", err)
	}
	if q.listItemBundlesStmt, err = db.PrepareContext(ctx, listItemBundles); err != nil {
		return nil, fmt.Errorf("error preparing query ListItemBundles: %w", err)
	}
	if q.resolveItemBundlesStmt, err = db.PrepareContext(ctx, resolveItemBundles); err != nil {
		return nil, fmt.Errorf("error preparing query ResolveItemBundles: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.adminCreateItemStmt != nil {
		if cerr := q.adminCreateItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminCreateItemStmt: %w", cerr)
		}
	}
	if q.adminDangerousChangeTypeStmt != nil {
		if cerr := q.adminDangerousChangeTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDangerousChangeTypeStmt: %w", cerr)
		}
	}
	if q.adminDeleteLocalizationStmt != nil {
		if cerr := q.adminDeleteLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminDeleteLocalizationStmt: %w", cerr)
		}
	}
	if q.adminGetItemBundleStmt != nil {
		if cerr := q.adminGetItemBundleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetItemBundleStmt: %w", cerr)
		}
	}
	if q.adminGetLocalizationStmt != nil {
		if cerr := q.adminGetLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetLocalizationStmt: %w", cerr)
		}
	}
	if q.adminGetStatsStmt != nil {
		if cerr := q.adminGetStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminGetStatsStmt: %w", cerr)
		}
	}
	if q.adminListItemsStmt != nil {
		if cerr := q.adminListItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListItemsStmt: %w", cerr)
		}
	}
	if q.adminListLocalizationsStmt != nil {
		if cerr := q.adminListLocalizationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminListLocalizationsStmt: %w", cerr)
		}
	}
	if q.adminRestoreItemStmt != nil {
		if cerr := q.adminRestoreItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminRestoreItemStmt: %w", cerr)
		}
	}
	if q.adminSoftDeleteItemStmt != nil {
		if cerr := q.adminSoftDeleteItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminSoftDeleteItemStmt: %w", cerr)
		}
	}
	if q.adminUpdateItemStmt != nil {
		if cerr := q.adminUpdateItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpdateItemStmt: %w", cerr)
		}
	}
	if q.adminUpsertLocalizationStmt != nil {
		if cerr := q.adminUpsertLocalizationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adminUpsertLocalizationStmt: %w", cerr)
		}
	}
	if q.getItemBundleStmt != nil {
		if cerr := q.getItemBundleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getItemBundleStmt: %w", cerr)
		}
	}
	if q.listExportItemsStmt != nil {
		if cerr := q.listExportItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listExportItemsStmt: %w", cerr)
		}
	}
	if q.listExportLocalizationsStmt != nil {
		if cerr := q.listExportLocalizationsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listExportLocalizationsStmt: %w", cerr)
		}
	}
	if q.listImportItemKeysStmt != nil {
		if cerr := q.listImportItemKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listImportItemKeysStmt: %w", cerr)
		}
	}
	if q.listItemBundlesStmt != nil {
		if cerr := q.listItemBundlesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listItemBundlesStmt: %w", cerr)
		}
	}
	if q.resolveItemBundlesStmt != nil {
		if cerr := q.resolveItemBundlesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing resolveItemBundlesStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	adminCreateItemStmt          *sql.Stmt
	adminDangerousChangeTypeStmt *sql.Stmt
	adminDeleteLocalizationStmt  *sql.Stmt
	adminGetItemBundleStmt       *sql.Stmt
	adminGetLocalizationStmt     *sql.Stmt
	adminGetStatsStmt            *sql.Stmt
	adminListItemsStmt           *sql.Stmt
	adminListLocalizationsStmt   *sql.Stmt
	adminRestoreItemStmt         *sql.Stmt
	adminSoftDeleteItemStmt      *sql.Stmt
	adminUpdateItemStmt          *sql.Stmt
	adminUpsertLocalizationStmt  *sql.Stmt
	getItemBundleStmt            *sql.Stmt
	listExportItemsStmt          *sql.Stmt
	listExportLocalizationsStmt  *sql.Stmt
	listImportItemKeysStmt       *sql.Stmt
	listItemBundlesStmt          *sql.Stmt
	resolveItemBundlesStmt       *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		adminCreateItemStmt:          q.adminCreateItemStmt,
		adminDangerousChangeTypeStmt: q.adminDangerousChangeTypeStmt,
		adminDeleteLocalizationStmt:  q.adminDeleteLocalizationStmt,
		adminGetItemBundleStmt:       q.adminGetItemBundleStmt,
		adminGetLocalizationStmt:     q.adminGetLocalizationStmt,
		adminGetStatsStmt:            q.adminGetStatsStmt,
		adminListItemsStmt:           q.adminListItemsStmt,
		adminListLocalizationsStmt:   q.adminListLocalizationsStmt,
		adminRestoreItemStmt:         q.adminRestoreItemStmt,
		adminSoftDeleteItemStmt:      q.adminSoftDeleteItemStmt,
		adminUpdateItemStmt:          q.adminUpdateItemStmt,
		adminUpsertLocalizationStmt:  q.adminUpsertLocalizationStmt,
		getItemBundleStmt:            q.getItemBundleStmt,
		listExportItemsStmt:          q.listExportItemsStmt,
		listExportLocalizationsStmt:  q.listExportLocalizationsStmt,
		listImportItemKeysStmt:       q.listImportItemKeysStmt,
		listItemBundlesStmt:          q.listItemBundlesStmt,
		resolveItemBundlesStmt:       q.resolveItemBundlesStmt,
	}
}
