// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const adminCreateItem = `-- name: AdminCreateItem :exec
INSERT INTO reference_item (
    workspace_id, key, item_type, payload, is_active
) VALUES ($1, $2, $3, $4, $5)
`

type AdminCreateItemParams struct {
	WorkspaceID string          `json:"workspace_id"`
	Key         string          `json:"key"`
	ItemType    string          `json:"item_type"`
	Payload     json.RawMessage `json:"payload"`
	IsActive    bool            `json:"is_active"`
}

func (q *Queries) AdminCreateItem(ctx context.Context, arg AdminCreateItemParams) error {
	_, err := q.exec(ctx, q.adminCreateItemStmt, adminCreateItem,
		arg.WorkspaceID,
		arg.Key,
		arg.ItemType,
		arg.Payload,
		arg.IsActive,
	)
	return err
}

const adminDangerousChangeType = `-- name: AdminDangerousChangeType :execrows
UPDATE reference_item
SET item_type = $1
WHERE workspace_id = $2
  AND key = $3
  AND item_type = $4
  AND deleted_at IS NULL
`

type AdminDangerousChangeTypeParams struct {
	ItemType    string `json:"item_type"`
	WorkspaceID string `json:"workspace_id"`
	Key         string `json:"key"`
	ItemType_2  string `json:"item_type_2"`
}

func (q *Queries) AdminDangerousChangeType(ctx context.Context, arg AdminDangerousChangeTypeParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDangerousChangeTypeStmt, adminDangerousChangeType,
		arg.ItemType,
		arg.WorkspaceID,
		arg.Key,
		arg.ItemType_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminDeleteLocalization = `-- name: AdminDeleteLocalization :execrows
DELETE FROM reference_localization
WHERE workspace_id = $1
  AND item_key = $2
  AND locale = $3
`

type AdminDeleteLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	ItemKey     string `json:"item_key"`
	Locale      string `json:"locale"`
}

func (q *Queries) AdminDeleteLocalization(ctx context.Context, arg AdminDeleteLocalizationParams) (int64, error) {
	result, err := q.exec(ctx, q.adminDeleteLocalizationStmt, adminDeleteLocalization, arg.WorkspaceID, arg.ItemKey, arg.Locale)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminGetItemBundle = `-- name: AdminGetItemBundle :many
SELECT
    i.workspace_id,
    i.key,
    i.item_type::text AS item_type,
    i.payload,
    i.is_active,
    i.deleted_at,
    i.created_at,
    i.updated_at,
    l.locale,
    l.title,
    l.description
FROM reference_item i
LEFT JOIN reference_localization l
  ON l.workspace_id = i.workspace_id
 AND l.item_key = i.key
WHERE i.workspace_id = $1
  AND i.key = $2
ORDER BY l.locale
`

type AdminGetItemBundleParams struct {
	WorkspaceID string `json:"workspace_id"`
	Key         string `json:"key"`
}

type AdminGetItemBundleRow struct {
	WorkspaceID string          `json:"workspace_id"`
	Key         string          `json:"key"`
	ItemType    string          `json:"item_type"`
	Payload     json.RawMessage `json:"payload"`
	IsActive    bool            `json:"is_active"`
	DeletedAt   sql.NullTime    `json:"deleted_at"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Locale      sql.NullString  `json:"locale"`
	Title       sql.NullString  `json:"title"`
	Description sql.NullString  `json:"description"`
}

func (q *Queries) AdminGetItemBundle(ctx context.Context, arg AdminGetItemBundleParams) ([]AdminGetItemBundleRow, error) {
	rows, err := q.query(ctx, q.adminGetItemBundleStmt, adminGetItemBundle, arg.WorkspaceID, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminGetItemBundleRow
	for rows.Next() {
		var i AdminGetItemBundleRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Key,
			&i.ItemType,
			&i.Payload,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Locale,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetLocalization = `-- name: AdminGetLocalization :one
SELECT
    workspace_id, item_key, locale, title, description, created_at, updated_at
FROM reference_localization
WHERE workspace_id = $1
  AND item_key = $2
  AND locale = $3
LIMIT 1
`

type AdminGetLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	ItemKey     string `json:"item_key"`
	Locale      string `json:"locale"`
}

func (q *Queries) AdminGetLocalization(ctx context.Context, arg AdminGetLocalizationParams) (ReferenceLocalization, error) {
	row := q.queryRow(ctx, q.adminGetLocalizationStmt, adminGetLocalization, arg.WorkspaceID, arg.ItemKey, arg.Locale)
	var i ReferenceLocalization
	err := row.Scan(
		&i.WorkspaceID,
		&i.ItemKey,
		&i.Locale,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetStats = `-- name: AdminGetStats :one
SELECT
    COUNT(*)::bigint AS items_total,
    COUNT(*) FILTER (WHERE deleted_at IS NULL)::bigint AS items_not_deleted,
    COUNT(*) FILTER (WHERE deleted_at IS NULL AND is_active = TRUE)::bigint AS active_items,
    COUNT(*) FILTER (WHERE deleted_at IS NOT NULL)::bigint AS deleted_items,
    COUNT(*) FILTER (WHERE deleted_at IS NULL AND item_type = 'quantity')::bigint AS quantity_items,
    COUNT(*) FILTER (WHERE deleted_at IS NULL AND item_type = 'duration')::bigint AS duration_items
FROM reference_item
WHERE workspace_id = $1
`

type AdminGetStatsRow struct {
	ItemsTotal      int64 `json:"items_total"`
	ItemsNotDeleted int64 `json:"items_not_deleted"`
	ActiveItems     int64 `json:"active_items"`
	DeletedItems    int64 `json:"deleted_items"`
	QuantityItems   int64 `json:"quantity_items"`
	DurationItems   int64 `json:"duration_items"`
}

func (q *Queries) AdminGetStats(ctx context.Context, workspaceID string) (AdminGetStatsRow, error) {
	row := q.queryRow(ctx, q.adminGetStatsStmt, adminGetStats, workspaceID)
	var i AdminGetStatsRow
	err := row.Scan(
		&i.ItemsTotal,
		&i.ItemsNotDeleted,
		&i.ActiveItems,
		&i.DeletedItems,
		&i.QuantityItems,
		&i.DurationItems,
	)
	return i, err
}

const adminListItems = `-- name: AdminListItems :many
SELECT
    workspace_id,
    key,
    item_type::text AS item_type,
    payload,
    is_active,
    deleted_at,
    created_at,
    updated_at
FROM reference_item
WHERE workspace_id = $1
  AND ($2 = '' OR item_type = $3)
  AND ($4 = FALSE OR deleted_at IS NULL)
ORDER BY key
LIMIT $5 OFFSET $6
`

type AdminListItemsParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Column2     interface{} `json:"column_2"`
	ItemType    string      `json:"item_type"`
	Column4     interface{} `json:"column_4"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type AdminListItemsRow struct {
	WorkspaceID string          `json:"workspace_id"`
	Key         string          `json:"key"`
	ItemType    string          `json:"item_type"`
	Payload     json.RawMessage `json:"payload"`
	IsActive    bool            `json:"is_active"`
	DeletedAt   sql.NullTime    `json:"deleted_at"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) AdminListItems(ctx context.Context, arg AdminListItemsParams) ([]AdminListItemsRow, error) {
	rows, err := q.query(ctx, q.adminListItemsStmt, adminListItems,
		arg.WorkspaceID,
		arg.Column2,
		arg.ItemType,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListItemsRow
	for rows.Next() {
		var i AdminListItemsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Key,
			&i.ItemType,
			&i.Payload,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListLocalizations = `-- name: AdminListLocalizations :many
SELECT
    workspace_id, item_key, locale, title, description, created_at, updated_at
FROM reference_localization
WHERE workspace_id = $1
  AND item_key = $2
ORDER BY locale
`

type AdminListLocalizationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	ItemKey     string `json:"item_key"`
}

func (q *Queries) AdminListLocalizations(ctx context.Context, arg AdminListLocalizationsParams) ([]ReferenceLocalization, error) {
	rows, err := q.query(ctx, q.adminListLocalizationsStmt, adminListLocalizations, arg.WorkspaceID, arg.ItemKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferenceLocalization
	for rows.Next() {
		var i ReferenceLocalization
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ItemKey,
			&i.Locale,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRestoreItem = `-- name: AdminRestoreItem :execrows
UPDATE reference_item
SET is_active = $1,
    deleted_at = NULL,
    updated_at = now()
WHERE workspace_id = $2
  AND key = $3
  AND deleted_at IS NOT NULL
`

type AdminRestoreItemParams struct {
	IsActive    bool   `json:"is_active"`
	WorkspaceID string `json:"workspace_id"`
	Key         string `json:"key"`
}

func (q *Queries) AdminRestoreItem(ctx context.Context, arg AdminRestoreItemParams) (int64, error) {
	result, err := q.exec(ctx, q.adminRestoreItemStmt, adminRestoreItem, arg.IsActive, arg.WorkspaceID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminSoftDeleteItem = `-- name: AdminSoftDeleteItem :execrows
UPDATE reference_item
SET is_active = FALSE,
    deleted_at = now(),
    updated_at = now()
WHERE workspace_id = $1
  AND key = $2
  AND deleted_at IS NULL
`

type AdminSoftDeleteItemParams struct {
	WorkspaceID string `json:"workspace_id"`
	Key         string `json:"key"`
}

func (q *Queries) AdminSoftDeleteItem(ctx context.Context, arg AdminSoftDeleteItemParams) (int64, error) {
	result, err := q.exec(ctx, q.adminSoftDeleteItemStmt, adminSoftDeleteItem, arg.WorkspaceID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpdateItem = `-- name: AdminUpdateItem :execrows
UPDATE reference_item
SET payload = $1,
    is_active = $2,
    updated_at = now()
WHERE workspace_id = $3
  AND key = $4
  AND deleted_at IS NULL
`

type AdminUpdateItemParams struct {
	Payload     json.RawMessage `json:"payload"`
	IsActive    bool            `json:"is_active"`
	WorkspaceID string          `json:"workspace_id"`
	Key         string          `json:"key"`
}

func (q *Queries) AdminUpdateItem(ctx context.Context, arg AdminUpdateItemParams) (int64, error) {
	result, err := q.exec(ctx, q.adminUpdateItemStmt, adminUpdateItem,
		arg.Payload,
		arg.IsActive,
		arg.WorkspaceID,
		arg.Key,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const adminUpsertLocalization = `-- name: AdminUpsertLocalization :exec
INSERT INTO reference_localization (
    workspace_id, item_key, locale, title, description
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, item_key, locale) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    updated_at = now()
`

type AdminUpsertLocalizationParams struct {
	WorkspaceID string `json:"workspace_id"`
	ItemKey     string `json:"item_key"`
	Locale      string `json:"locale"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) AdminUpsertLocalization(ctx context.Context, arg AdminUpsertLocalizationParams) error {
	_, err := q.exec(ctx, q.adminUpsertLocalizationStmt, adminUpsertLocalization,
		arg.WorkspaceID,
		arg.ItemKey,
		arg.Locale,
		arg.Title,
		arg.Description,
	)
	return err
}

const getItemBundle = `-- name: GetItemBundle :many
SELECT
    i.workspace_id,
    i.key,
    i.item_type::text AS item_type,
    i.payload,
    i.is_active,
    i.deleted_at,
    i.created_at,
    i.updated_at,
    l.locale,
    l.title,
    l.description
FROM reference_item i
LEFT JOIN reference_localization l
  ON l.workspace_id = i.workspace_id
 AND l.item_key = i.key
 AND l.locale = $1
WHERE i.workspace_id = $2
  AND i.key = $3
  AND i.deleted_at IS NULL
  AND i.is_active = TRUE
LIMIT 1
`

type GetItemBundleParams struct {
	Locale      string `json:"locale"`
	WorkspaceID string `json:"workspace_id"`
	Key         string `json:"key"`
}

type GetItemBundleRow struct {
	WorkspaceID string          `json:"workspace_id"`
	Key         string          `json:"key"`
	ItemType    string          `json:"item_type"`
	Payload     json.RawMessage `json:"payload"`
	IsActive    bool            `json:"is_active"`
	DeletedAt   sql.NullTime    `json:"deleted_at"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Locale      sql.NullString  `json:"locale"`
	Title       sql.NullString  `json:"title"`
	Description sql.NullString  `json:"description"`
}

func (q *Queries) GetItemBundle(ctx context.Context, arg GetItemBundleParams) ([]GetItemBundleRow, error) {
	rows, err := q.query(ctx, q.getItemBundleStmt, getItemBundle, arg.Locale, arg.WorkspaceID, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemBundleRow
	for rows.Next() {
		var i GetItemBundleRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Key,
			&i.ItemType,
			&i.Payload,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Locale,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportItems = `-- name: ListExportItems :many
SELECT
    workspace_id,
    key,
    item_type::text AS item_type,
    payload,
    is_active,
    deleted_at,
    created_at,
    updated_at
FROM reference_item
WHERE workspace_id = $1
  AND ($2 = FALSE OR deleted_at IS NULL)
ORDER BY key
`

type ListExportItemsParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Column2     interface{} `json:"column_2"`
}

type ListExportItemsRow struct {
	WorkspaceID string          `json:"workspace_id"`
	Key         string          `json:"key"`
	ItemType    string          `json:"item_type"`
	Payload     json.RawMessage `json:"payload"`
	IsActive    bool            `json:"is_active"`
	DeletedAt   sql.NullTime    `json:"deleted_at"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) ListExportItems(ctx context.Context, arg ListExportItemsParams) ([]ListExportItemsRow, error) {
	rows, err := q.query(ctx, q.listExportItemsStmt, listExportItems, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExportItemsRow
	for rows.Next() {
		var i ListExportItemsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Key,
			&i.ItemType,
			&i.Payload,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportLocalizations = `-- name: ListExportLocalizations :many
SELECT
    workspace_id,
    item_key,
    locale,
    title,
    description,
    created_at,
    updated_at
FROM reference_localization
WHERE workspace_id = $1
ORDER BY item_key, locale
`

func (q *Queries) ListExportLocalizations(ctx context.Context, workspaceID string) ([]ReferenceLocalization, error) {
	rows, err := q.query(ctx, q.listExportLocalizationsStmt, listExportLocalizations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferenceLocalization
	for rows.Next() {
		var i ReferenceLocalization
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ItemKey,
			&i.Locale,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportItemKeys = `-- name: ListImportItemKeys :many
SELECT key
FROM reference_item
WHERE workspace_id = $1
`

func (q *Queries) ListImportItemKeys(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.query(ctx, q.listImportItemKeysStmt, listImportItemKeys, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemBundles = `-- name: ListItemBundles :many
SELECT
    i.workspace_id,
    i.key,
    i.item_type::text AS item_type,
    i.payload,
    i.is_active,
    i.deleted_at,
    i.created_at,
    i.updated_at,
    l.locale,
    l.title,
    l.description
FROM reference_item i
LEFT JOIN reference_localization l
  ON l.workspace_id = i.workspace_id
 AND l.item_key = i.key
 AND l.locale = $1
WHERE i.workspace_id = $2
  AND i.deleted_at IS NULL
  AND i.is_active = TRUE
ORDER BY i.key
LIMIT $3 OFFSET $4
`

type ListItemBundlesParams struct {
	Locale      string `json:"locale"`
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type ListItemBundlesRow struct {
	WorkspaceID string          `json:"workspace_id"`
	Key         string          `json:"key"`
	ItemType    string          `json:"item_type"`
	Payload     json.RawMessage `json:"payload"`
	IsActive    bool            `json:"is_active"`
	DeletedAt   sql.NullTime    `json:"deleted_at"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Locale      sql.NullString  `json:"locale"`
	Title       sql.NullString  `json:"title"`
	Description sql.NullString  `json:"description"`
}

func (q *Queries) ListItemBundles(ctx context.Context, arg ListItemBundlesParams) ([]ListItemBundlesRow, error) {
	rows, err := q.query(ctx, q.listItemBundlesStmt, listItemBundles,
		arg.Locale,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemBundlesRow
	for rows.Next() {
		var i ListItemBundlesRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Key,
			&i.ItemType,
			&i.Payload,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Locale,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveItemBundles = `-- name: ResolveItemBundles :many
SELECT
    i.workspace_id,
    i.key,
    i.item_type::text AS item_type,
    i.payload,
    i.is_active,
    i.deleted_at,
    i.created_at,
    i.updated_at,
    l.locale,
    l.title,
    l.description
FROM reference_item i
JOIN unnest($3::text[]) WITH ORDINALITY AS requested(key, position)
  ON requested.key = i.key
LEFT JOIN reference_localization l
  ON l.workspace_id = i.workspace_id
 AND l.item_key = i.key
 AND l.locale = $1
WHERE i.workspace_id = $2
  AND i.deleted_at IS NULL
  AND i.is_active = TRUE
ORDER BY requested.position
`

type ResolveItemBundlesParams struct {
	Locale      string   `json:"locale"`
	WorkspaceID string   `json:"workspace_id"`
	Column3     []string `json:"column_3"`
}

type ResolveItemBundlesRow struct {
	WorkspaceID string          `json:"workspace_id"`
	Key         string          `json:"key"`
	ItemType    string          `json:"item_type"`
	Payload     json.RawMessage `json:"payload"`
	IsActive    bool            `json:"is_active"`
	DeletedAt   sql.NullTime    `json:"deleted_at"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Locale      sql.NullString  `json:"locale"`
	Title       sql.NullString  `json:"title"`
	Description sql.NullString  `json:"description"`
}

func (q *Queries) ResolveItemBundles(ctx context.Context, arg ResolveItemBundlesParams) ([]ResolveItemBundlesRow, error) {
	rows, err := q.query(ctx, q.resolveItemBundlesStmt, resolveItemBundles, arg.Locale, arg.WorkspaceID, pq.Array(arg.Column3))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveItemBundlesRow
	for rows.Next() {
		var i ResolveItemBundlesRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Key,
			&i.ItemType,
			&i.Payload,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Locale,
			&i.Title,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
