package ton

import serviceerrors "github.com/elum2b/services/errors"

var (
	ErrNetworkInvalid               = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton network must be mainnet or testnet")
	ErrWalletAddressRequired        = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton wallet address is required")
	ErrWalletAddressInvalid         = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton wallet address is invalid")
	ErrWalletNotConfigured          = serviceerrors.New(serviceerrors.CodeFailedPrecondition, "ton wallet is not configured for workspace")
	ErrDestinationRequired          = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton destination is required")
	ErrWorkspaceIDRequired          = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton workspace id is required")
	ErrNetworkConfigURLRequired     = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton network config url is required")
	ErrJettonMasterAddressRequired  = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton jetton master address is required")
	ErrRefundUnsupported            = serviceerrors.New(serviceerrors.CodeUnsupported, "ton outgoing wallet signer is not configured")
	ErrSubscriberNotInitialized     = serviceerrors.New(serviceerrors.CodeNotReady, "ton subscriber is not initialized")
	ErrJettonCallbackNotConfigured  = serviceerrors.New(serviceerrors.CodeNotReady, "ton jetton callback is not configured")
	ErrTONCallbackNotConfigured     = serviceerrors.New(serviceerrors.CodeNotReady, "ton TON callback is not configured")
	ErrJettonMasterAddressEmpty     = serviceerrors.New(serviceerrors.CodeNotFound, "ton jetton master address is empty")
	ErrAmountOverflow               = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton amount exceeds supported range")
	ErrAssetChainMismatch           = serviceerrors.New(serviceerrors.CodeFailedPrecondition, "ton asset belongs to a different chain")
	ErrAssetNetworkMismatch         = serviceerrors.New(serviceerrors.CodeFailedPrecondition, "ton asset belongs to a different network")
	ErrSourceWalletRequired         = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton source wallet is required")
	ErrDestinationAddressInvalid    = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton destination address is invalid")
	ErrResponseAddressInvalid       = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton response destination address is invalid")
	ErrNetworkConfigLoadFailed      = serviceerrors.New(serviceerrors.CodeUnavailable, "ton network config load failed")
	ErrLiteConnectionsFailed        = serviceerrors.New(serviceerrors.CodeUnavailable, "ton lite connections initialization failed")
	ErrMasterAddressInvalid         = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton jetton master address is invalid")
	ErrOwnerWalletInvalid           = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton owner wallet address is invalid")
	ErrRecipientWalletResolveFailed = serviceerrors.New(serviceerrors.CodeUnavailable, "ton recipient jetton wallet resolve failed")
	ErrJettonAssetNotFound          = serviceerrors.New(serviceerrors.CodeNotFound, "ton active jetton asset was not found")
	ErrInternalMessageRequired      = serviceerrors.New(serviceerrors.CodeInvalidFields, "ton internal message is required")
	ErrBodyParseFailed              = serviceerrors.New(serviceerrors.CodeInternalError, "ton message body parse failed")
	ErrQueryIDReadFailed            = serviceerrors.New(serviceerrors.CodeInternalError, "ton query id read failed")
	ErrAmountReadFailed             = serviceerrors.New(serviceerrors.CodeInternalError, "ton amount read failed")
	ErrSenderAddressReadFailed      = serviceerrors.New(serviceerrors.CodeInternalError, "ton sender address read failed")
	ErrPayloadReferenceReadFailed   = serviceerrors.New(serviceerrors.CodeInternalError, "ton payload reference read failed")
	ErrTextCommentReadFailed        = serviceerrors.New(serviceerrors.CodeInternalError, "ton text comment read failed")
	ErrSumTypeReadFailed            = serviceerrors.New(serviceerrors.CodeInternalError, "ton sumType read failed")
)
